// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package kahla

import (
	json "encoding/json"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
	http "net/http"
	url "net/url"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Auth_IndexResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WikiPath             string   `protobuf:"bytes,3,opt,name=wikiPath,proto3" json:"wikiPath,omitempty"`
	ServerTime           string   `protobuf:"bytes,4,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	UtcTime              string   `protobuf:"bytes,5,opt,name=utcTime,proto3" json:"utcTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_IndexResponse) Reset()         { *m = Auth_IndexResponse{} }
func (m *Auth_IndexResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_IndexResponse) ProtoMessage()    {}
func (*Auth_IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Auth_IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_IndexResponse.Unmarshal(m, b)
}
func (m *Auth_IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_IndexResponse.Marshal(b, m, deterministic)
}
func (m *Auth_IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_IndexResponse.Merge(m, src)
}
func (m *Auth_IndexResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_IndexResponse.Size(m)
}
func (m *Auth_IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_IndexResponse proto.InternalMessageInfo

func (m *Auth_IndexResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_IndexResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Auth_IndexResponse) GetWikiPath() string {
	if m != nil {
		return m.WikiPath
	}
	return ""
}

func (m *Auth_IndexResponse) GetServerTime() string {
	if m != nil {
		return m.ServerTime
	}
	return ""
}

func (m *Auth_IndexResponse) GetUtcTime() string {
	if m != nil {
		return m.UtcTime
	}
	return ""
}

type Auth_VersionResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatestVersion        string   `protobuf:"bytes,3,opt,name=latestVersion,proto3" json:"latestVersion,omitempty"`
	LatestCLIVersion     string   `protobuf:"bytes,4,opt,name=latestCLIVersion,proto3" json:"latestCLIVersion,omitempty"`
	DownloadAddress      string   `protobuf:"bytes,5,opt,name=downloadAddress,proto3" json:"downloadAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_VersionResponse) Reset()         { *m = Auth_VersionResponse{} }
func (m *Auth_VersionResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_VersionResponse) ProtoMessage()    {}
func (*Auth_VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Auth_VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_VersionResponse.Unmarshal(m, b)
}
func (m *Auth_VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_VersionResponse.Marshal(b, m, deterministic)
}
func (m *Auth_VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_VersionResponse.Merge(m, src)
}
func (m *Auth_VersionResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_VersionResponse.Size(m)
}
func (m *Auth_VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_VersionResponse proto.InternalMessageInfo

func (m *Auth_VersionResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_VersionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Auth_VersionResponse) GetLatestVersion() string {
	if m != nil {
		return m.LatestVersion
	}
	return ""
}

func (m *Auth_VersionResponse) GetLatestCLIVersion() string {
	if m != nil {
		return m.LatestCLIVersion
	}
	return ""
}

func (m *Auth_VersionResponse) GetDownloadAddress() string {
	if m != nil {
		return m.DownloadAddress
	}
	return ""
}

type Auth_AuthByPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_AuthByPasswordRequest) Reset()         { *m = Auth_AuthByPasswordRequest{} }
func (m *Auth_AuthByPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_AuthByPasswordRequest) ProtoMessage()    {}
func (*Auth_AuthByPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Auth_AuthByPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_AuthByPasswordRequest.Unmarshal(m, b)
}
func (m *Auth_AuthByPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_AuthByPasswordRequest.Marshal(b, m, deterministic)
}
func (m *Auth_AuthByPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_AuthByPasswordRequest.Merge(m, src)
}
func (m *Auth_AuthByPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_AuthByPasswordRequest.Size(m)
}
func (m *Auth_AuthByPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_AuthByPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_AuthByPasswordRequest proto.InternalMessageInfo

func (m *Auth_AuthByPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Auth_AuthByPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Auth_AuthByPasswordResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_AuthByPasswordResponse) Reset()         { *m = Auth_AuthByPasswordResponse{} }
func (m *Auth_AuthByPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_AuthByPasswordResponse) ProtoMessage()    {}
func (*Auth_AuthByPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Auth_AuthByPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_AuthByPasswordResponse.Unmarshal(m, b)
}
func (m *Auth_AuthByPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_AuthByPasswordResponse.Marshal(b, m, deterministic)
}
func (m *Auth_AuthByPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_AuthByPasswordResponse.Merge(m, src)
}
func (m *Auth_AuthByPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_AuthByPasswordResponse.Size(m)
}
func (m *Auth_AuthByPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_AuthByPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_AuthByPasswordResponse proto.InternalMessageInfo

func (m *Auth_AuthByPasswordResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_AuthByPasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Auth_RegisterKahlaRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_RegisterKahlaRequest) Reset()         { *m = Auth_RegisterKahlaRequest{} }
func (m *Auth_RegisterKahlaRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_RegisterKahlaRequest) ProtoMessage()    {}
func (*Auth_RegisterKahlaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Auth_RegisterKahlaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_RegisterKahlaRequest.Unmarshal(m, b)
}
func (m *Auth_RegisterKahlaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_RegisterKahlaRequest.Marshal(b, m, deterministic)
}
func (m *Auth_RegisterKahlaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_RegisterKahlaRequest.Merge(m, src)
}
func (m *Auth_RegisterKahlaRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_RegisterKahlaRequest.Size(m)
}
func (m *Auth_RegisterKahlaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_RegisterKahlaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_RegisterKahlaRequest proto.InternalMessageInfo

func (m *Auth_RegisterKahlaRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Auth_RegisterKahlaRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Auth_RegisterKahlaRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type Auth_RegisterKahlaResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_RegisterKahlaResponse) Reset()         { *m = Auth_RegisterKahlaResponse{} }
func (m *Auth_RegisterKahlaResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_RegisterKahlaResponse) ProtoMessage()    {}
func (*Auth_RegisterKahlaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *Auth_RegisterKahlaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_RegisterKahlaResponse.Unmarshal(m, b)
}
func (m *Auth_RegisterKahlaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_RegisterKahlaResponse.Marshal(b, m, deterministic)
}
func (m *Auth_RegisterKahlaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_RegisterKahlaResponse.Merge(m, src)
}
func (m *Auth_RegisterKahlaResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_RegisterKahlaResponse.Size(m)
}
func (m *Auth_RegisterKahlaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_RegisterKahlaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_RegisterKahlaResponse proto.InternalMessageInfo

func (m *Auth_RegisterKahlaResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_RegisterKahlaResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Auth_AuthResultRequest struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_AuthResultRequest) Reset()         { *m = Auth_AuthResultRequest{} }
func (m *Auth_AuthResultRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_AuthResultRequest) ProtoMessage()    {}
func (*Auth_AuthResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *Auth_AuthResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_AuthResultRequest.Unmarshal(m, b)
}
func (m *Auth_AuthResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_AuthResultRequest.Marshal(b, m, deterministic)
}
func (m *Auth_AuthResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_AuthResultRequest.Merge(m, src)
}
func (m *Auth_AuthResultRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_AuthResultRequest.Size(m)
}
func (m *Auth_AuthResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_AuthResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_AuthResultRequest proto.InternalMessageInfo

func (m *Auth_AuthResultRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Auth_AuthResultRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Auth_SignInStatusResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                bool     `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_SignInStatusResponse) Reset()         { *m = Auth_SignInStatusResponse{} }
func (m *Auth_SignInStatusResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_SignInStatusResponse) ProtoMessage()    {}
func (*Auth_SignInStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *Auth_SignInStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_SignInStatusResponse.Unmarshal(m, b)
}
func (m *Auth_SignInStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_SignInStatusResponse.Marshal(b, m, deterministic)
}
func (m *Auth_SignInStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_SignInStatusResponse.Merge(m, src)
}
func (m *Auth_SignInStatusResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_SignInStatusResponse.Size(m)
}
func (m *Auth_SignInStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_SignInStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_SignInStatusResponse proto.InternalMessageInfo

func (m *Auth_SignInStatusResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_SignInStatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Auth_SignInStatusResponse) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Auth_MeResponse struct {
	Code                 int32                  `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                *Auth_MeResponse_Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Auth_MeResponse) Reset()         { *m = Auth_MeResponse{} }
func (m *Auth_MeResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_MeResponse) ProtoMessage()    {}
func (*Auth_MeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *Auth_MeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_MeResponse.Unmarshal(m, b)
}
func (m *Auth_MeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_MeResponse.Marshal(b, m, deterministic)
}
func (m *Auth_MeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_MeResponse.Merge(m, src)
}
func (m *Auth_MeResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_MeResponse.Size(m)
}
func (m *Auth_MeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_MeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_MeResponse proto.InternalMessageInfo

func (m *Auth_MeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_MeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Auth_MeResponse) GetValue() *Auth_MeResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Auth_MeResponse_Value struct {
	AccountCreateTime       string   `protobuf:"bytes,1,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	Bio                     string   `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Email                   string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailConfirmed          bool     `protobuf:"varint,4,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool     `protobuf:"varint,5,opt,name=enableEmailNotification,proto3" json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32   `protobuf:"varint,6,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	Id                      string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	MakeEmailPublic         bool     `protobuf:"varint,8,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	NickName                string   `protobuf:"bytes,9,opt,name=nickName,proto3" json:"nickName,omitempty"`
	PreferedLanguage        string   `protobuf:"bytes,10,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	Sex                     string   `protobuf:"bytes,11,opt,name=sex,proto3" json:"sex,omitempty"`
	ThemeId                 int32    `protobuf:"varint,12,opt,name=themeId,proto3" json:"themeId,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Auth_MeResponse_Value) Reset()         { *m = Auth_MeResponse_Value{} }
func (m *Auth_MeResponse_Value) String() string { return proto.CompactTextString(m) }
func (*Auth_MeResponse_Value) ProtoMessage()    {}
func (*Auth_MeResponse_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8, 0}
}

func (m *Auth_MeResponse_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_MeResponse_Value.Unmarshal(m, b)
}
func (m *Auth_MeResponse_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_MeResponse_Value.Marshal(b, m, deterministic)
}
func (m *Auth_MeResponse_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_MeResponse_Value.Merge(m, src)
}
func (m *Auth_MeResponse_Value) XXX_Size() int {
	return xxx_messageInfo_Auth_MeResponse_Value.Size(m)
}
func (m *Auth_MeResponse_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_MeResponse_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_MeResponse_Value proto.InternalMessageInfo

func (m *Auth_MeResponse_Value) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

func (m *Auth_MeResponse_Value) GetEnableEmailNotification() bool {
	if m != nil {
		return m.EnableEmailNotification
	}
	return false
}

func (m *Auth_MeResponse_Value) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Auth_MeResponse_Value) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Auth_MeResponse_Value) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Auth_MeResponse_Value) GetThemeId() int32 {
	if m != nil {
		return m.ThemeId
	}
	return 0
}

type Auth_UpdateInfoRequest struct {
	NickName             string   `protobuf:"bytes,1,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Bio                  string   `protobuf:"bytes,2,opt,name=Bio,proto3" json:"Bio,omitempty"`
	HeadImgKey           uint32   `protobuf:"varint,3,opt,name=HeadImgKey,proto3" json:"HeadImgKey,omitempty"`
	HideMyEmail          bool     `protobuf:"varint,4,opt,name=HideMyEmail,proto3" json:"HideMyEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_UpdateInfoRequest) Reset()         { *m = Auth_UpdateInfoRequest{} }
func (m *Auth_UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_UpdateInfoRequest) ProtoMessage()    {}
func (*Auth_UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *Auth_UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *Auth_UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (m *Auth_UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_UpdateInfoRequest.Merge(m, src)
}
func (m *Auth_UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_UpdateInfoRequest.Size(m)
}
func (m *Auth_UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_UpdateInfoRequest proto.InternalMessageInfo

func (m *Auth_UpdateInfoRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Auth_UpdateInfoRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Auth_UpdateInfoRequest) GetHeadImgKey() uint32 {
	if m != nil {
		return m.HeadImgKey
	}
	return 0
}

func (m *Auth_UpdateInfoRequest) GetHideMyEmail() bool {
	if m != nil {
		return m.HideMyEmail
	}
	return false
}

type Auth_UpdateInfoResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_UpdateInfoResponse) Reset()         { *m = Auth_UpdateInfoResponse{} }
func (m *Auth_UpdateInfoResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_UpdateInfoResponse) ProtoMessage()    {}
func (*Auth_UpdateInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *Auth_UpdateInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_UpdateInfoResponse.Unmarshal(m, b)
}
func (m *Auth_UpdateInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_UpdateInfoResponse.Marshal(b, m, deterministic)
}
func (m *Auth_UpdateInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_UpdateInfoResponse.Merge(m, src)
}
func (m *Auth_UpdateInfoResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_UpdateInfoResponse.Size(m)
}
func (m *Auth_UpdateInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_UpdateInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_UpdateInfoResponse proto.InternalMessageInfo

func (m *Auth_UpdateInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_UpdateInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Auth_UpdateClientSettingRequest struct {
	ThemeId                 uint32   `protobuf:"varint,1,opt,name=ThemeId,proto3" json:"ThemeId,omitempty"`
	EnableEmailNotification bool     `protobuf:"varint,2,opt,name=EnableEmailNotification,proto3" json:"EnableEmailNotification,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Auth_UpdateClientSettingRequest) Reset()         { *m = Auth_UpdateClientSettingRequest{} }
func (m *Auth_UpdateClientSettingRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_UpdateClientSettingRequest) ProtoMessage()    {}
func (*Auth_UpdateClientSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *Auth_UpdateClientSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_UpdateClientSettingRequest.Unmarshal(m, b)
}
func (m *Auth_UpdateClientSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_UpdateClientSettingRequest.Marshal(b, m, deterministic)
}
func (m *Auth_UpdateClientSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_UpdateClientSettingRequest.Merge(m, src)
}
func (m *Auth_UpdateClientSettingRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_UpdateClientSettingRequest.Size(m)
}
func (m *Auth_UpdateClientSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_UpdateClientSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_UpdateClientSettingRequest proto.InternalMessageInfo

func (m *Auth_UpdateClientSettingRequest) GetThemeId() uint32 {
	if m != nil {
		return m.ThemeId
	}
	return 0
}

func (m *Auth_UpdateClientSettingRequest) GetEnableEmailNotification() bool {
	if m != nil {
		return m.EnableEmailNotification
	}
	return false
}

type Auth_UpdateClientSettingResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_UpdateClientSettingResponse) Reset()         { *m = Auth_UpdateClientSettingResponse{} }
func (m *Auth_UpdateClientSettingResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_UpdateClientSettingResponse) ProtoMessage()    {}
func (*Auth_UpdateClientSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *Auth_UpdateClientSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_UpdateClientSettingResponse.Unmarshal(m, b)
}
func (m *Auth_UpdateClientSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_UpdateClientSettingResponse.Marshal(b, m, deterministic)
}
func (m *Auth_UpdateClientSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_UpdateClientSettingResponse.Merge(m, src)
}
func (m *Auth_UpdateClientSettingResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_UpdateClientSettingResponse.Size(m)
}
func (m *Auth_UpdateClientSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_UpdateClientSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_UpdateClientSettingResponse proto.InternalMessageInfo

func (m *Auth_UpdateClientSettingResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_UpdateClientSettingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Auth_ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	RepeatPassword       string   `protobuf:"bytes,3,opt,name=RepeatPassword,proto3" json:"RepeatPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_ChangePasswordRequest) Reset()         { *m = Auth_ChangePasswordRequest{} }
func (m *Auth_ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_ChangePasswordRequest) ProtoMessage()    {}
func (*Auth_ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *Auth_ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *Auth_ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *Auth_ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_ChangePasswordRequest.Merge(m, src)
}
func (m *Auth_ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_ChangePasswordRequest.Size(m)
}
func (m *Auth_ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_ChangePasswordRequest proto.InternalMessageInfo

func (m *Auth_ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *Auth_ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *Auth_ChangePasswordRequest) GetRepeatPassword() string {
	if m != nil {
		return m.RepeatPassword
	}
	return ""
}

type Auth_ChangePasswordResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_ChangePasswordResponse) Reset()         { *m = Auth_ChangePasswordResponse{} }
func (m *Auth_ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_ChangePasswordResponse) ProtoMessage()    {}
func (*Auth_ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *Auth_ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *Auth_ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *Auth_ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_ChangePasswordResponse.Merge(m, src)
}
func (m *Auth_ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_ChangePasswordResponse.Size(m)
}
func (m *Auth_ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_ChangePasswordResponse proto.InternalMessageInfo

func (m *Auth_ChangePasswordResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_ChangePasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Auth_SendEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_SendEmailRequest) Reset()         { *m = Auth_SendEmailRequest{} }
func (m *Auth_SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_SendEmailRequest) ProtoMessage()    {}
func (*Auth_SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *Auth_SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_SendEmailRequest.Unmarshal(m, b)
}
func (m *Auth_SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *Auth_SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_SendEmailRequest.Merge(m, src)
}
func (m *Auth_SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_SendEmailRequest.Size(m)
}
func (m *Auth_SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_SendEmailRequest proto.InternalMessageInfo

func (m *Auth_SendEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Auth_SendEmailResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_SendEmailResponse) Reset()         { *m = Auth_SendEmailResponse{} }
func (m *Auth_SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_SendEmailResponse) ProtoMessage()    {}
func (*Auth_SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{16}
}

func (m *Auth_SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_SendEmailResponse.Unmarshal(m, b)
}
func (m *Auth_SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *Auth_SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_SendEmailResponse.Merge(m, src)
}
func (m *Auth_SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_SendEmailResponse.Size(m)
}
func (m *Auth_SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_SendEmailResponse proto.InternalMessageInfo

func (m *Auth_SendEmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_SendEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Auth_InitPusherResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerPath           string   `protobuf:"bytes,3,opt,name=serverPath,proto3" json:"serverPath,omitempty"`
	ChannelId            uint32   `protobuf:"varint,4,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ConnectKey           string   `protobuf:"bytes,5,opt,name=connectKey,proto3" json:"connectKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_InitPusherResponse) Reset()         { *m = Auth_InitPusherResponse{} }
func (m *Auth_InitPusherResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_InitPusherResponse) ProtoMessage()    {}
func (*Auth_InitPusherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{17}
}

func (m *Auth_InitPusherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_InitPusherResponse.Unmarshal(m, b)
}
func (m *Auth_InitPusherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_InitPusherResponse.Marshal(b, m, deterministic)
}
func (m *Auth_InitPusherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_InitPusherResponse.Merge(m, src)
}
func (m *Auth_InitPusherResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_InitPusherResponse.Size(m)
}
func (m *Auth_InitPusherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_InitPusherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_InitPusherResponse proto.InternalMessageInfo

func (m *Auth_InitPusherResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_InitPusherResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Auth_InitPusherResponse) GetServerPath() string {
	if m != nil {
		return m.ServerPath
	}
	return ""
}

func (m *Auth_InitPusherResponse) GetChannelId() uint32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *Auth_InitPusherResponse) GetConnectKey() string {
	if m != nil {
		return m.ConnectKey
	}
	return ""
}

type Auth_LogOffRequest struct {
	DeviceId             int32    `protobuf:"zigzag32,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_LogOffRequest) Reset()         { *m = Auth_LogOffRequest{} }
func (m *Auth_LogOffRequest) String() string { return proto.CompactTextString(m) }
func (*Auth_LogOffRequest) ProtoMessage()    {}
func (*Auth_LogOffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{18}
}

func (m *Auth_LogOffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_LogOffRequest.Unmarshal(m, b)
}
func (m *Auth_LogOffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_LogOffRequest.Marshal(b, m, deterministic)
}
func (m *Auth_LogOffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_LogOffRequest.Merge(m, src)
}
func (m *Auth_LogOffRequest) XXX_Size() int {
	return xxx_messageInfo_Auth_LogOffRequest.Size(m)
}
func (m *Auth_LogOffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_LogOffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_LogOffRequest proto.InternalMessageInfo

func (m *Auth_LogOffRequest) GetDeviceId() int32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type Auth_LogOffResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_LogOffResponse) Reset()         { *m = Auth_LogOffResponse{} }
func (m *Auth_LogOffResponse) String() string { return proto.CompactTextString(m) }
func (*Auth_LogOffResponse) ProtoMessage()    {}
func (*Auth_LogOffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{19}
}

func (m *Auth_LogOffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_LogOffResponse.Unmarshal(m, b)
}
func (m *Auth_LogOffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_LogOffResponse.Marshal(b, m, deterministic)
}
func (m *Auth_LogOffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_LogOffResponse.Merge(m, src)
}
func (m *Auth_LogOffResponse) XXX_Size() int {
	return xxx_messageInfo_Auth_LogOffResponse.Size(m)
}
func (m *Auth_LogOffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_LogOffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_LogOffResponse proto.InternalMessageInfo

func (m *Auth_LogOffResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Auth_LogOffResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Auth_IndexResponse)(nil), "kahla.Auth_IndexResponse")
	proto.RegisterType((*Auth_VersionResponse)(nil), "kahla.Auth_VersionResponse")
	proto.RegisterType((*Auth_AuthByPasswordRequest)(nil), "kahla.Auth_AuthByPasswordRequest")
	proto.RegisterType((*Auth_AuthByPasswordResponse)(nil), "kahla.Auth_AuthByPasswordResponse")
	proto.RegisterType((*Auth_RegisterKahlaRequest)(nil), "kahla.Auth_RegisterKahlaRequest")
	proto.RegisterType((*Auth_RegisterKahlaResponse)(nil), "kahla.Auth_RegisterKahlaResponse")
	proto.RegisterType((*Auth_AuthResultRequest)(nil), "kahla.Auth_AuthResultRequest")
	proto.RegisterType((*Auth_SignInStatusResponse)(nil), "kahla.Auth_SignInStatusResponse")
	proto.RegisterType((*Auth_MeResponse)(nil), "kahla.Auth_MeResponse")
	proto.RegisterType((*Auth_MeResponse_Value)(nil), "kahla.Auth_MeResponse.Value")
	proto.RegisterType((*Auth_UpdateInfoRequest)(nil), "kahla.Auth_UpdateInfoRequest")
	proto.RegisterType((*Auth_UpdateInfoResponse)(nil), "kahla.Auth_UpdateInfoResponse")
	proto.RegisterType((*Auth_UpdateClientSettingRequest)(nil), "kahla.Auth_UpdateClientSettingRequest")
	proto.RegisterType((*Auth_UpdateClientSettingResponse)(nil), "kahla.Auth_UpdateClientSettingResponse")
	proto.RegisterType((*Auth_ChangePasswordRequest)(nil), "kahla.Auth_ChangePasswordRequest")
	proto.RegisterType((*Auth_ChangePasswordResponse)(nil), "kahla.Auth_ChangePasswordResponse")
	proto.RegisterType((*Auth_SendEmailRequest)(nil), "kahla.Auth_SendEmailRequest")
	proto.RegisterType((*Auth_SendEmailResponse)(nil), "kahla.Auth_SendEmailResponse")
	proto.RegisterType((*Auth_InitPusherResponse)(nil), "kahla.Auth_InitPusherResponse")
	proto.RegisterType((*Auth_LogOffRequest)(nil), "kahla.Auth_LogOffRequest")
	proto.RegisterType((*Auth_LogOffResponse)(nil), "kahla.Auth_LogOffResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x85, 0x2c, 0xcb, 0x96, 0xc7, 0x97, 0xc4, 0x1b, 0x37, 0x61, 0xe8, 0xc4, 0x55, 0x88, 0x22,
	0x35, 0x8a, 0x56, 0x29, 0xdc, 0x02, 0x2d, 0xfa, 0x90, 0x22, 0x56, 0x9c, 0x5a, 0xf5, 0x4d, 0xa0,
	0xd3, 0x00, 0x05, 0x02, 0x04, 0x6b, 0x71, 0x24, 0x2d, 0x4c, 0x2d, 0x55, 0x72, 0xe9, 0xcb, 0x1f,
	0x04, 0xe8, 0x73, 0x81, 0xfe, 0x40, 0xdf, 0xfa, 0x11, 0x7d, 0xec, 0x67, 0x15, 0xbb, 0x4b, 0x52,
	0x4b, 0x4a, 0x74, 0x01, 0xbe, 0x08, 0x9a, 0xb3, 0xbb, 0x67, 0x67, 0x66, 0x67, 0x0e, 0x07, 0x80,
	0xc6, 0x62, 0xd4, 0x9e, 0x84, 0x81, 0x08, 0x48, 0xe3, 0x92, 0x8e, 0x7c, 0x6a, 0xaf, 0xe1, 0x8d,
	0x40, 0xee, 0x69, 0xd0, 0xde, 0x1e, 0x06, 0xc1, 0xd0, 0xc7, 0x17, 0xca, 0xba, 0x88, 0x07, 0x2f,
	0x70, 0x3c, 0x11, 0xb7, 0x7a, 0xd1, 0xf9, 0xb3, 0x06, 0xe4, 0x55, 0x2c, 0x46, 0x1f, 0xba, 0xdc,
	0xc3, 0x1b, 0x17, 0xa3, 0x49, 0xc0, 0x23, 0x24, 0x04, 0x16, 0xfb, 0x81, 0x87, 0x56, 0xad, 0x55,
	0xdb, 0xdd, 0x74, 0xd5, 0x7f, 0x62, 0xc1, 0xf2, 0x18, 0xa3, 0x88, 0x0e, 0xd1, 0x5a, 0x68, 0xd5,
	0x76, 0x57, 0xdc, 0xd4, 0x24, 0x36, 0x34, 0xaf, 0xd9, 0x25, 0xeb, 0x51, 0x31, 0xb2, 0xea, 0x6a,
	0x29, 0xb3, 0xc9, 0x0e, 0x40, 0x84, 0xe1, 0x15, 0x86, 0x6f, 0xd9, 0x18, 0xad, 0x45, 0xb5, 0x6a,
	0x20, 0x92, 0x35, 0x16, 0x7d, 0xb5, 0xd8, 0xd0, 0xac, 0x89, 0xe9, 0xfc, 0x53, 0x83, 0x2d, 0xe5,
	0xda, 0x3b, 0x0c, 0x23, 0x16, 0xf0, 0x8a, 0xce, 0x7d, 0x06, 0xeb, 0x3e, 0x15, 0x18, 0x89, 0x84,
	0x26, 0xf1, 0x30, 0x0f, 0x92, 0x2f, 0xe0, 0xbe, 0x06, 0x3a, 0xc7, 0xdd, 0x74, 0xa3, 0x76, 0x76,
	0x06, 0x27, 0xbb, 0x70, 0xcf, 0x0b, 0xae, 0xb9, 0x1f, 0x50, 0xef, 0x95, 0xe7, 0x85, 0x18, 0x45,
	0x89, 0xeb, 0x45, 0xd8, 0x39, 0x05, 0x5b, 0x45, 0x20, 0x7f, 0xf6, 0x6f, 0x7b, 0x34, 0x8a, 0xae,
	0x83, 0xd0, 0x73, 0xf1, 0xb7, 0x18, 0x23, 0x41, 0xb6, 0xa0, 0x81, 0x63, 0xca, 0x7c, 0x15, 0xc8,
	0x8a, 0xab, 0x0d, 0x99, 0xcc, 0x49, 0xb2, 0x31, 0x09, 0x25, 0xb3, 0x9d, 0x23, 0xd8, 0x9e, 0xcb,
	0x57, 0x25, 0x31, 0xce, 0x35, 0x3c, 0x56, 0x64, 0x2e, 0x0e, 0x59, 0x24, 0x30, 0x3c, 0x92, 0xb5,
	0x63, 0xf8, 0x76, 0x60, 0xfa, 0x76, 0x90, 0xfa, 0xd6, 0x2b, 0xf8, 0x96, 0xda, 0x32, 0x2b, 0x9d,
	0x80, 0x0f, 0x58, 0x38, 0xce, 0xb6, 0xe8, 0x4c, 0x17, 0x61, 0xe7, 0xe7, 0x24, 0x2b, 0x85, 0x8b,
	0x2b, 0x05, 0xb1, 0x0f, 0x0f, 0xb3, 0x8c, 0xb8, 0x18, 0xc5, 0xbe, 0x30, 0x22, 0x88, 0x04, 0x15,
	0x98, 0x46, 0xa0, 0x8c, 0x8c, 0x5d, 0xd2, 0xac, 0x6b, 0x76, 0xe7, 0x43, 0x92, 0x88, 0x73, 0x36,
	0xe4, 0x5d, 0x7e, 0x2e, 0xa8, 0x88, 0xa3, 0x8a, 0xc5, 0xb6, 0x05, 0x8d, 0x2b, 0xea, 0xc7, 0xa8,
	0x42, 0x6f, 0xba, 0xda, 0x70, 0x7e, 0x5f, 0x84, 0x7b, 0xea, 0x86, 0x13, 0xac, 0xc8, 0xbb, 0x67,
	0xf2, 0xae, 0xee, 0x3d, 0x69, 0xab, 0x46, 0x6f, 0x17, 0x48, 0xdb, 0xef, 0xe4, 0x9e, 0xe4, 0x56,
	0xfb, 0x8f, 0x3a, 0x34, 0x14, 0x40, 0xbe, 0x84, 0x4d, 0xda, 0xef, 0x07, 0x31, 0x17, 0x9d, 0x10,
	0xa9, 0x40, 0xd5, 0x6d, 0x3a, 0x2d, 0xb3, 0x0b, 0xe4, 0x3e, 0xd4, 0x2f, 0x58, 0x90, 0x78, 0x20,
	0xff, 0x4e, 0x0b, 0xb5, 0x6e, 0x16, 0xea, 0x73, 0xd8, 0x50, 0x7f, 0x92, 0xe7, 0x45, 0x4f, 0x35,
	0x4c, 0xd3, 0x2d, 0xa0, 0xe4, 0x7b, 0x78, 0x84, 0x9c, 0x5e, 0xf8, 0xa8, 0x6a, 0xe8, 0x34, 0x10,
	0x6c, 0xc0, 0xfa, 0x54, 0xc8, 0x0e, 0x6b, 0xa8, 0x03, 0x65, 0xcb, 0xf2, 0x86, 0x11, 0x52, 0xaf,
	0x3b, 0x1e, 0xbe, 0x61, 0x3e, 0x1e, 0xe1, 0xad, 0xb5, 0xa4, 0x9e, 0xad, 0x80, 0x92, 0x0d, 0x58,
	0x60, 0x9e, 0xb5, 0xac, 0x9c, 0x5b, 0x60, 0xaa, 0x14, 0xc7, 0xf4, 0x52, 0x13, 0xf6, 0xe2, 0x0b,
	0x9f, 0xf5, 0xad, 0xa6, 0xba, 0xa9, 0x08, 0xcb, 0x82, 0xe6, 0xac, 0x7f, 0x79, 0x4a, 0xc7, 0x68,
	0xad, 0xe8, 0x82, 0x4e, 0x6d, 0x29, 0x09, 0x93, 0x10, 0x07, 0x18, 0xa2, 0x77, 0x4c, 0xf9, 0x30,
	0x96, 0xcf, 0x02, 0x5a, 0x12, 0x8a, 0xb8, 0xcc, 0x59, 0x84, 0x37, 0xd6, 0xaa, 0xce, 0x59, 0x84,
	0x37, 0xf2, 0x2d, 0xc5, 0x08, 0xc7, 0xd8, 0xf5, 0xac, 0xb5, 0x56, 0x6d, 0xb7, 0xe1, 0xa6, 0xa6,
	0xf3, 0xb1, 0x96, 0xd4, 0xec, 0x2f, 0x13, 0x8f, 0x0a, 0xec, 0xf2, 0x41, 0x90, 0xd6, 0xac, 0x0d,
	0xcd, 0xd3, 0xd4, 0x1d, 0xfd, 0x3e, 0x99, 0x2d, 0xaf, 0xd8, 0x9f, 0x3e, 0xcb, 0x3e, 0x0b, 0xa4,
	0xb4, 0x1e, 0xea, 0x44, 0xc8, 0xd4, 0xd4, 0x55, 0x6a, 0x0c, 0x84, 0xb4, 0x60, 0xf5, 0x90, 0x79,
	0x78, 0x72, 0xab, 0x3b, 0x59, 0xbf, 0x8e, 0x09, 0x39, 0x3f, 0xc1, 0xa3, 0x19, 0x4f, 0x2a, 0xb5,
	0x61, 0x0c, 0x9f, 0x1a, 0x44, 0x1d, 0x9f, 0x21, 0x17, 0xe7, 0x28, 0x04, 0xe3, 0xc3, 0x34, 0x36,
	0x0b, 0x96, 0xdf, 0x26, 0x09, 0xa9, 0x29, 0x57, 0x53, 0x53, 0x16, 0xc8, 0x41, 0x49, 0x81, 0x2c,
	0xe8, 0x02, 0x29, 0x59, 0x76, 0x7a, 0xd0, 0x2a, 0xbf, 0xb6, 0x52, 0x20, 0x1f, 0x6b, 0x89, 0x38,
	0x75, 0x46, 0x94, 0x0f, 0xb1, 0x28, 0xd9, 0x2d, 0x58, 0x3d, 0xf3, 0xbd, 0x4c, 0xe0, 0xf4, 0x1b,
	0x99, 0x90, 0xdc, 0x71, 0x8a, 0xd7, 0x05, 0x95, 0x34, 0x21, 0x59, 0xd5, 0x2e, 0x4e, 0x90, 0x8a,
	0x82, 0x4e, 0x16, 0xd0, 0x4c, 0xec, 0x8b, 0x9e, 0x54, 0x8a, 0xeb, 0x2b, 0xf8, 0x44, 0x6b, 0x1c,
	0x72, 0x4f, 0xe5, 0xf1, 0xce, 0x8f, 0x90, 0xf3, 0x26, 0x29, 0x51, 0x63, 0x7b, 0xa5, 0x6b, 0xff,
	0xaa, 0x25, 0x15, 0xd6, 0xe5, 0x4c, 0xf4, 0xe2, 0x68, 0x84, 0x61, 0x45, 0x05, 0xcc, 0xe6, 0x08,
	0x63, 0xca, 0x30, 0x10, 0xf2, 0x04, 0x56, 0xfa, 0x23, 0xca, 0x39, 0xfa, 0x5d, 0x2d, 0x44, 0xeb,
	0xee, 0x14, 0x90, 0xa7, 0xfb, 0x01, 0xe7, 0xd8, 0x17, 0xb2, 0x55, 0xf4, 0xd7, 0xda, 0x40, 0x9c,
	0xaf, 0x93, 0x29, 0xe8, 0x38, 0x18, 0x9e, 0x0d, 0x06, 0x46, 0x3b, 0xbe, 0xc6, 0x2b, 0xd6, 0x4f,
	0x6b, 0x76, 0xd3, 0xcd, 0x6c, 0xa7, 0x03, 0x0f, 0x72, 0x27, 0xaa, 0x04, 0xb5, 0xf7, 0x77, 0x13,
	0x16, 0x25, 0x0b, 0xf9, 0x01, 0x1a, 0x6a, 0x00, 0x23, 0x0f, 0xdb, 0x7a, 0x5a, 0x6b, 0xa7, 0xd3,
	0x5a, 0xfb, 0x40, 0x4e, 0x6b, 0xf6, 0x63, 0x53, 0xf1, 0xf3, 0xb3, 0xda, 0x4b, 0x58, 0x4e, 0x27,
	0x93, 0xb2, 0xd3, 0xdb, 0xe6, 0xe9, 0xe2, 0x38, 0xf5, 0x1e, 0x36, 0xf2, 0xf3, 0x04, 0x79, 0x66,
	0x6e, 0x9f, 0x3b, 0xbb, 0xd8, 0xce, 0x5d, 0x5b, 0x34, 0xb1, 0x53, 0xff, 0xf7, 0x65, 0x8d, 0xfc,
	0x0a, 0xeb, 0xb9, 0xef, 0x3c, 0x69, 0x99, 0x27, 0xe7, 0xcd, 0x1e, 0xf6, 0xb3, 0x3b, 0x76, 0x98,
	0xd4, 0xdf, 0x41, 0xe3, 0x4c, 0x65, 0xaf, 0x2c, 0xec, 0x12, 0x9c, 0x74, 0x00, 0xa6, 0xf3, 0x02,
	0x79, 0x5a, 0x0c, 0x25, 0x37, 0x47, 0x94, 0x92, 0x1c, 0xc2, 0x9a, 0x39, 0x30, 0x94, 0x3a, 0x91,
	0x8b, 0x77, 0xee, 0x88, 0xf1, 0x2d, 0x2c, 0x9c, 0xe0, 0x1d, 0x41, 0xcc, 0xfd, 0xd6, 0x93, 0x1e,
	0xc0, 0x54, 0xb6, 0xf3, 0x41, 0xcc, 0x7c, 0x58, 0xec, 0x9d, 0xb2, 0x65, 0x33, 0x9f, 0x97, 0xf0,
	0x60, 0x8e, 0x90, 0x92, 0xe7, 0xb3, 0x67, 0xe7, 0x09, 0xbc, 0xfd, 0xf9, 0xff, 0xee, 0x33, 0x2f,
	0x7b, 0x0f, 0x1b, 0x79, 0x61, 0xcb, 0x57, 0xdd, 0x5c, 0xf9, 0xcd, 0x57, 0xdd, 0x7c, 0x5d, 0xd4,
	0xec, 0x27, 0xb0, 0x92, 0x49, 0x17, 0xc9, 0x4d, 0x4b, 0x45, 0x01, 0xb4, 0x9f, 0x96, 0xac, 0x9a,
	0x74, 0xaf, 0x01, 0xa6, 0x02, 0x56, 0xfa, 0x52, 0x3b, 0xf9, 0x1e, 0x9d, 0x11, 0xbc, 0x1f, 0x61,
	0x49, 0xab, 0x05, 0xc9, 0x75, 0x73, 0x4e, 0x73, 0x6c, 0x7b, 0xde, 0x92, 0x26, 0xb8, 0x58, 0x52,
	0x17, 0x7e, 0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xb3, 0xd1, 0xc6, 0xf3, 0x0d, 0x00,
	0x00,
}

// Generated by go-rest-client
type AuthService struct {
	client  *http.Client
	baseUrl string
}

func NewAuthService(client *http.Client, baseUrl string) *AuthService {
	return &AuthService{
		client:  client,
		baseUrl: baseUrl,
	}
}
func (s *AuthService) Index() (*Auth_IndexResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/Index", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_IndexResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) Version() (*Auth_VersionResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/Version", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_VersionResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) AuthByPassword(in *Auth_AuthByPasswordRequest) (*Auth_AuthByPasswordResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("email", in.Email)
	v.Add("password", in.Password)
	req, err := http.NewRequest("POST", s.baseUrl+"/Auth/AuthByPassword", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_AuthByPasswordResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) RegisterKahla(in *Auth_RegisterKahlaRequest) (*Auth_RegisterKahlaResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("Email", in.Email)
	v.Add("Password", in.Password)
	v.Add("ConfirmPassword", in.ConfirmPassword)
	req, err := http.NewRequest("POST", s.baseUrl+"/Auth/RegisterKahla", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_RegisterKahlaResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) OAuth() (*http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/OAuth", nil)
	if err != nil {
		return nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return resp, err
	}
	defer resp.Body.Close()
	return resp, nil
}
func (s *AuthService) AuthResult(in *Auth_AuthResultRequest) (*http.Response, error) {
	v := url.Values{}
	v.Add("state", in.State)
	v.Add("code", strconv.FormatUint(uint64(in.Code), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/AuthResult?"+v.Encode(), nil)
	if err != nil {
		return nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return resp, err
	}
	defer resp.Body.Close()
	return resp, nil
}
func (s *AuthService) SignInStatus() (*Auth_SignInStatusResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/SignInStatus", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_SignInStatusResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) Me() (*Auth_MeResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/Me", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_MeResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) UpdateInfo(in *Auth_UpdateInfoRequest) (*Auth_UpdateInfoResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("NickName", in.NickName)
	v.Add("Bio", in.Bio)
	v.Add("HeadImgKey", strconv.FormatUint(uint64(in.HeadImgKey), 10))
	v.Add("HideMyEmail", strconv.FormatBool(in.HideMyEmail))
	req, err := http.NewRequest("POST", s.baseUrl+"/Auth/UpdateInfo", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_UpdateInfoResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) UpdateClientSetting(in *Auth_UpdateClientSettingRequest) (*Auth_UpdateClientSettingResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("ThemeId", strconv.FormatUint(uint64(in.ThemeId), 10))
	v.Add("EnableEmailNotification", strconv.FormatBool(in.EnableEmailNotification))
	req, err := http.NewRequest("POST", s.baseUrl+"/Auth/UpdateClientSetting", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_UpdateClientSettingResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) ChangePassword(in *Auth_ChangePasswordRequest) (*Auth_ChangePasswordResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("OldPassword", in.OldPassword)
	v.Add("NewPassword", in.NewPassword)
	v.Add("RepeatPassword", in.RepeatPassword)
	req, err := http.NewRequest("POST", s.baseUrl+"/Auth/ChangePassword", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_ChangePasswordResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) SendEmail(in *Auth_SendEmailRequest) (*Auth_SendEmailResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("email", in.Email)
	req, err := http.NewRequest("POST", s.baseUrl+"/Auth/SendEmail", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_SendEmailResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) InitPusher() (*Auth_InitPusherResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/InitPusher", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_InitPusherResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *AuthService) LogOff(in *Auth_LogOffRequest) (*Auth_LogOffResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("DeviceId", strconv.FormatInt(int64(in.DeviceId), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Auth/LogOff?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Auth_LogOffResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
