// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conversation.proto

package kahla

import (
	json "encoding/json"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	http "net/http"
	url "net/url"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Conversation_Discriminator int32

const (
	Conversation_Discriminator_PrivateConversation Conversation_Discriminator = 0
	Conversation_Discriminator_GroupConversation   Conversation_Discriminator = 1
)

var Conversation_Discriminator_name = map[int32]string{
	0: "PrivateConversation",
	1: "GroupConversation",
}

var Conversation_Discriminator_value = map[string]int32{
	"PrivateConversation": 0,
	"GroupConversation":   1,
}

func (x Conversation_Discriminator) String() string {
	return proto.EnumName(Conversation_Discriminator_name, int32(x))
}

func (Conversation_Discriminator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{0}
}

type Conversation_AllRequest struct {
	Take                 uint32   `protobuf:"varint,1,opt,name=Take,proto3" json:"Take,omitempty"`
	Skip                 uint32   `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_AllRequest) Reset()         { *m = Conversation_AllRequest{} }
func (m *Conversation_AllRequest) String() string { return proto.CompactTextString(m) }
func (*Conversation_AllRequest) ProtoMessage()    {}
func (*Conversation_AllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{0}
}

func (m *Conversation_AllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_AllRequest.Unmarshal(m, b)
}
func (m *Conversation_AllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_AllRequest.Marshal(b, m, deterministic)
}
func (m *Conversation_AllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_AllRequest.Merge(m, src)
}
func (m *Conversation_AllRequest) XXX_Size() int {
	return xxx_messageInfo_Conversation_AllRequest.Size(m)
}
func (m *Conversation_AllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_AllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_AllRequest proto.InternalMessageInfo

func (m *Conversation_AllRequest) GetTake() uint32 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *Conversation_AllRequest) GetSkip() uint32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type Conversation_AllResponse struct {
	Code                 int32                            `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items                []*Conversation_AllResponse_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Conversation_AllResponse) Reset()         { *m = Conversation_AllResponse{} }
func (m *Conversation_AllResponse) String() string { return proto.CompactTextString(m) }
func (*Conversation_AllResponse) ProtoMessage()    {}
func (*Conversation_AllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{1}
}

func (m *Conversation_AllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_AllResponse.Unmarshal(m, b)
}
func (m *Conversation_AllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_AllResponse.Marshal(b, m, deterministic)
}
func (m *Conversation_AllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_AllResponse.Merge(m, src)
}
func (m *Conversation_AllResponse) XXX_Size() int {
	return xxx_messageInfo_Conversation_AllResponse.Size(m)
}
func (m *Conversation_AllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_AllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_AllResponse proto.InternalMessageInfo

func (m *Conversation_AllResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Conversation_AllResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Conversation_AllResponse) GetItems() []*Conversation_AllResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Conversation_AllResponse_Item struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	DisplayImageKey      uint32   `protobuf:"varint,2,opt,name=displayImageKey,proto3" json:"displayImageKey,omitempty"`
	LatestMessage        string   `protobuf:"bytes,3,opt,name=latestMessage,proto3" json:"latestMessage,omitempty"`
	LatestMessageTime    string   `protobuf:"bytes,4,opt,name=latestMessageTime,proto3" json:"latestMessageTime,omitempty"`
	UnReadAmount         uint32   `protobuf:"varint,5,opt,name=unReadAmount,proto3" json:"unReadAmount,omitempty"`
	ConversationId       uint32   `protobuf:"varint,6,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	Discriminator        string   `protobuf:"bytes,7,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	UserId               string   `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	AesKey               string   `protobuf:"bytes,9,opt,name=aesKey,proto3" json:"aesKey,omitempty"`
	Muted                bool     `protobuf:"varint,10,opt,name=muted,proto3" json:"muted,omitempty"`
	SomeoneAtMe          bool     `protobuf:"varint,11,opt,name=someoneAtMe,proto3" json:"someoneAtMe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_AllResponse_Item) Reset()         { *m = Conversation_AllResponse_Item{} }
func (m *Conversation_AllResponse_Item) String() string { return proto.CompactTextString(m) }
func (*Conversation_AllResponse_Item) ProtoMessage()    {}
func (*Conversation_AllResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{1, 0}
}

func (m *Conversation_AllResponse_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_AllResponse_Item.Unmarshal(m, b)
}
func (m *Conversation_AllResponse_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_AllResponse_Item.Marshal(b, m, deterministic)
}
func (m *Conversation_AllResponse_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_AllResponse_Item.Merge(m, src)
}
func (m *Conversation_AllResponse_Item) XXX_Size() int {
	return xxx_messageInfo_Conversation_AllResponse_Item.Size(m)
}
func (m *Conversation_AllResponse_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_AllResponse_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_AllResponse_Item proto.InternalMessageInfo

func (m *Conversation_AllResponse_Item) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Conversation_AllResponse_Item) GetDisplayImageKey() uint32 {
	if m != nil {
		return m.DisplayImageKey
	}
	return 0
}

func (m *Conversation_AllResponse_Item) GetLatestMessage() string {
	if m != nil {
		return m.LatestMessage
	}
	return ""
}

func (m *Conversation_AllResponse_Item) GetLatestMessageTime() string {
	if m != nil {
		return m.LatestMessageTime
	}
	return ""
}

func (m *Conversation_AllResponse_Item) GetUnReadAmount() uint32 {
	if m != nil {
		return m.UnReadAmount
	}
	return 0
}

func (m *Conversation_AllResponse_Item) GetConversationId() uint32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *Conversation_AllResponse_Item) GetDiscriminator() string {
	if m != nil {
		return m.Discriminator
	}
	return ""
}

func (m *Conversation_AllResponse_Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Conversation_AllResponse_Item) GetAesKey() string {
	if m != nil {
		return m.AesKey
	}
	return ""
}

func (m *Conversation_AllResponse_Item) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *Conversation_AllResponse_Item) GetSomeoneAtMe() bool {
	if m != nil {
		return m.SomeoneAtMe
	}
	return false
}

type Conversation_GetMessageRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkipTill             uint32   `protobuf:"varint,2,opt,name=skipTill,proto3" json:"skipTill,omitempty"`
	Take                 uint32   `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_GetMessageRequest) Reset()         { *m = Conversation_GetMessageRequest{} }
func (m *Conversation_GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*Conversation_GetMessageRequest) ProtoMessage()    {}
func (*Conversation_GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{2}
}

func (m *Conversation_GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_GetMessageRequest.Unmarshal(m, b)
}
func (m *Conversation_GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_GetMessageRequest.Marshal(b, m, deterministic)
}
func (m *Conversation_GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_GetMessageRequest.Merge(m, src)
}
func (m *Conversation_GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_Conversation_GetMessageRequest.Size(m)
}
func (m *Conversation_GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_GetMessageRequest proto.InternalMessageInfo

func (m *Conversation_GetMessageRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation_GetMessageRequest) GetSkipTill() uint32 {
	if m != nil {
		return m.SkipTill
	}
	return 0
}

func (m *Conversation_GetMessageRequest) GetTake() uint32 {
	if m != nil {
		return m.Take
	}
	return 0
}

type Conversation_GetMessageResponse struct {
	Code                 int32                                   `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items                []*Conversation_GetMessageResponse_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *Conversation_GetMessageResponse) Reset()         { *m = Conversation_GetMessageResponse{} }
func (m *Conversation_GetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*Conversation_GetMessageResponse) ProtoMessage()    {}
func (*Conversation_GetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{3}
}

func (m *Conversation_GetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_GetMessageResponse.Unmarshal(m, b)
}
func (m *Conversation_GetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_GetMessageResponse.Marshal(b, m, deterministic)
}
func (m *Conversation_GetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_GetMessageResponse.Merge(m, src)
}
func (m *Conversation_GetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_Conversation_GetMessageResponse.Size(m)
}
func (m *Conversation_GetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_GetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_GetMessageResponse proto.InternalMessageInfo

func (m *Conversation_GetMessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Conversation_GetMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Conversation_GetMessageResponse) GetItems() []*Conversation_GetMessageResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Conversation_GetMessageResponse_Item struct {
	Id                   uint32                                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId       uint32                                       `protobuf:"varint,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	Ats                  []*Conversation_GetMessageResponse_Item_At   `protobuf:"bytes,3,rep,name=ats,proto3" json:"ats,omitempty"`
	SenderId             string                                       `protobuf:"bytes,4,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Sender               *Conversation_GetMessageResponse_Item_Sender `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	SendTime             string                                       `protobuf:"bytes,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	Content              string                                       `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Read                 bool                                         `protobuf:"varint,8,opt,name=read,proto3" json:"read,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *Conversation_GetMessageResponse_Item) Reset()         { *m = Conversation_GetMessageResponse_Item{} }
func (m *Conversation_GetMessageResponse_Item) String() string { return proto.CompactTextString(m) }
func (*Conversation_GetMessageResponse_Item) ProtoMessage()    {}
func (*Conversation_GetMessageResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{3, 0}
}

func (m *Conversation_GetMessageResponse_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item.Unmarshal(m, b)
}
func (m *Conversation_GetMessageResponse_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item.Marshal(b, m, deterministic)
}
func (m *Conversation_GetMessageResponse_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_GetMessageResponse_Item.Merge(m, src)
}
func (m *Conversation_GetMessageResponse_Item) XXX_Size() int {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item.Size(m)
}
func (m *Conversation_GetMessageResponse_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_GetMessageResponse_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_GetMessageResponse_Item proto.InternalMessageInfo

func (m *Conversation_GetMessageResponse_Item) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation_GetMessageResponse_Item) GetConversationId() uint32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *Conversation_GetMessageResponse_Item) GetAts() []*Conversation_GetMessageResponse_Item_At {
	if m != nil {
		return m.Ats
	}
	return nil
}

func (m *Conversation_GetMessageResponse_Item) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item) GetSender() *Conversation_GetMessageResponse_Item_Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Conversation_GetMessageResponse_Item) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

type Conversation_GetMessageResponse_Item_At struct {
	TargetUserId         string   `protobuf:"bytes,1,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_GetMessageResponse_Item_At) Reset() {
	*m = Conversation_GetMessageResponse_Item_At{}
}
func (m *Conversation_GetMessageResponse_Item_At) String() string { return proto.CompactTextString(m) }
func (*Conversation_GetMessageResponse_Item_At) ProtoMessage()    {}
func (*Conversation_GetMessageResponse_Item_At) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{3, 0, 0}
}

func (m *Conversation_GetMessageResponse_Item_At) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item_At.Unmarshal(m, b)
}
func (m *Conversation_GetMessageResponse_Item_At) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item_At.Marshal(b, m, deterministic)
}
func (m *Conversation_GetMessageResponse_Item_At) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_GetMessageResponse_Item_At.Merge(m, src)
}
func (m *Conversation_GetMessageResponse_Item_At) XXX_Size() int {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item_At.Size(m)
}
func (m *Conversation_GetMessageResponse_Item_At) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_GetMessageResponse_Item_At.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_GetMessageResponse_Item_At proto.InternalMessageInfo

func (m *Conversation_GetMessageResponse_Item_At) GetTargetUserId() string {
	if m != nil {
		return m.TargetUserId
	}
	return ""
}

type Conversation_GetMessageResponse_Item_Sender struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_GetMessageResponse_Item_Sender) Reset() {
	*m = Conversation_GetMessageResponse_Item_Sender{}
}
func (m *Conversation_GetMessageResponse_Item_Sender) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_GetMessageResponse_Item_Sender) ProtoMessage() {}
func (*Conversation_GetMessageResponse_Item_Sender) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{3, 0, 1}
}

func (m *Conversation_GetMessageResponse_Item_Sender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item_Sender.Unmarshal(m, b)
}
func (m *Conversation_GetMessageResponse_Item_Sender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item_Sender.Marshal(b, m, deterministic)
}
func (m *Conversation_GetMessageResponse_Item_Sender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_GetMessageResponse_Item_Sender.Merge(m, src)
}
func (m *Conversation_GetMessageResponse_Item_Sender) XXX_Size() int {
	return xxx_messageInfo_Conversation_GetMessageResponse_Item_Sender.Size(m)
}
func (m *Conversation_GetMessageResponse_Item_Sender) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_GetMessageResponse_Item_Sender.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_GetMessageResponse_Item_Sender proto.InternalMessageInfo

func (m *Conversation_GetMessageResponse_Item_Sender) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Conversation_GetMessageResponse_Item_Sender) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Conversation_SendMessageRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	At                   []string `protobuf:"bytes,3,rep,name=At,proto3" json:"At,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_SendMessageRequest) Reset()         { *m = Conversation_SendMessageRequest{} }
func (m *Conversation_SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*Conversation_SendMessageRequest) ProtoMessage()    {}
func (*Conversation_SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{4}
}

func (m *Conversation_SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_SendMessageRequest.Unmarshal(m, b)
}
func (m *Conversation_SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *Conversation_SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_SendMessageRequest.Merge(m, src)
}
func (m *Conversation_SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_Conversation_SendMessageRequest.Size(m)
}
func (m *Conversation_SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_SendMessageRequest proto.InternalMessageInfo

func (m *Conversation_SendMessageRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation_SendMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Conversation_SendMessageRequest) GetAt() []string {
	if m != nil {
		return m.At
	}
	return nil
}

type Conversation_SendMessageResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_SendMessageResponse) Reset()         { *m = Conversation_SendMessageResponse{} }
func (m *Conversation_SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*Conversation_SendMessageResponse) ProtoMessage()    {}
func (*Conversation_SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{5}
}

func (m *Conversation_SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_SendMessageResponse.Unmarshal(m, b)
}
func (m *Conversation_SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *Conversation_SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_SendMessageResponse.Merge(m, src)
}
func (m *Conversation_SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_Conversation_SendMessageResponse.Size(m)
}
func (m *Conversation_SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_SendMessageResponse proto.InternalMessageInfo

func (m *Conversation_SendMessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Conversation_SendMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Conversation_ConversationDetailRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_ConversationDetailRequest) Reset() {
	*m = Conversation_ConversationDetailRequest{}
}
func (m *Conversation_ConversationDetailRequest) String() string { return proto.CompactTextString(m) }
func (*Conversation_ConversationDetailRequest) ProtoMessage()    {}
func (*Conversation_ConversationDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{6}
}

func (m *Conversation_ConversationDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailRequest.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailRequest.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailRequest.Merge(m, src)
}
func (m *Conversation_ConversationDetailRequest) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailRequest.Size(m)
}
func (m *Conversation_ConversationDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailRequest proto.InternalMessageInfo

func (m *Conversation_ConversationDetailRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Conversation_ConversationDetailResponse struct {
	Code                 int32                                          `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                *Conversation_ConversationDetailResponse_Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Conversation_ConversationDetailResponse) Reset() {
	*m = Conversation_ConversationDetailResponse{}
}
func (m *Conversation_ConversationDetailResponse) String() string { return proto.CompactTextString(m) }
func (*Conversation_ConversationDetailResponse) ProtoMessage()    {}
func (*Conversation_ConversationDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7}
}

func (m *Conversation_ConversationDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailResponse.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailResponse.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailResponse.Merge(m, src)
}
func (m *Conversation_ConversationDetailResponse) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailResponse.Size(m)
}
func (m *Conversation_ConversationDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailResponse proto.InternalMessageInfo

func (m *Conversation_ConversationDetailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse) GetValue() *Conversation_ConversationDetailResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Conversation_ConversationDetailResponse_Value struct {
	// For GroupConversation
	Users []*Conversation_ConversationDetailResponse_Value_User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// For GroupConversation
	GroupImageKey uint32 `protobuf:"varint,2,opt,name=groupImageKey,proto3" json:"groupImageKey,omitempty"`
	// For GroupConversation
	GroupName string `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	// For GroupConversation
	HasPassword bool `protobuf:"varint,4,opt,name=hasPassword,proto3" json:"hasPassword,omitempty"`
	// For GroupConversation
	OwnerId string `protobuf:"bytes,5,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	// For PrivateConversation
	RequesterId string `protobuf:"bytes,13,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	// For PrivateConversation
	RequestUser *Conversation_ConversationDetailResponse_Value_RequestUser `protobuf:"bytes,14,opt,name=requestUser,proto3" json:"requestUser,omitempty"`
	// For PrivateConversation
	TargetId string `protobuf:"bytes,15,opt,name=targetId,proto3" json:"targetId,omitempty"`
	// For PrivateConversation
	TargetUser *Conversation_ConversationDetailResponse_Value_TargetUser `protobuf:"bytes,16,opt,name=targetUser,proto3" json:"targetUser,omitempty"`
	// For PrivateConversation
	AnotherUserId string `protobuf:"bytes,17,opt,name=anotherUserId,proto3" json:"anotherUserId,omitempty"`
	// For GroupConversation, PrivateConversation
	Id uint32 `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	// For GroupConversation, PrivateConversation
	Discriminator string `protobuf:"bytes,7,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	// For GroupConversation, PrivateConversation
	AesKey string `protobuf:"bytes,8,opt,name=aesKey,proto3" json:"aesKey,omitempty"`
	// For GroupConversation, PrivateConversation
	MaxLiveSeconds uint32 `protobuf:"varint,9,opt,name=maxLiveSeconds,proto3" json:"maxLiveSeconds,omitempty"`
	// For GroupConversation, PrivateConversation
	ConversationCreateTime string `protobuf:"bytes,10,opt,name=conversationCreateTime,proto3" json:"conversationCreateTime,omitempty"`
	// For GroupConversation, PrivateConversation
	DisplayName string `protobuf:"bytes,11,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// For GroupConversation, PrivateConversation
	DisplayImage         uint32   `protobuf:"varint,12,opt,name=displayImage,proto3" json:"displayImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_ConversationDetailResponse_Value) Reset() {
	*m = Conversation_ConversationDetailResponse_Value{}
}
func (m *Conversation_ConversationDetailResponse_Value) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_ConversationDetailResponse_Value) ProtoMessage() {}
func (*Conversation_ConversationDetailResponse_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7, 0}
}

func (m *Conversation_ConversationDetailResponse_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailResponse_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailResponse_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value.Merge(m, src)
}
func (m *Conversation_ConversationDetailResponse_Value) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value.Size(m)
}
func (m *Conversation_ConversationDetailResponse_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailResponse_Value proto.InternalMessageInfo

func (m *Conversation_ConversationDetailResponse_Value) GetUsers() []*Conversation_ConversationDetailResponse_Value_User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Conversation_ConversationDetailResponse_Value) GetGroupImageKey() uint32 {
	if m != nil {
		return m.GroupImageKey
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetHasPassword() bool {
	if m != nil {
		return m.HasPassword
	}
	return false
}

func (m *Conversation_ConversationDetailResponse_Value) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetRequesterId() string {
	if m != nil {
		return m.RequesterId
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetRequestUser() *Conversation_ConversationDetailResponse_Value_RequestUser {
	if m != nil {
		return m.RequestUser
	}
	return nil
}

func (m *Conversation_ConversationDetailResponse_Value) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetTargetUser() *Conversation_ConversationDetailResponse_Value_TargetUser {
	if m != nil {
		return m.TargetUser
	}
	return nil
}

func (m *Conversation_ConversationDetailResponse_Value) GetAnotherUserId() string {
	if m != nil {
		return m.AnotherUserId
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value) GetDiscriminator() string {
	if m != nil {
		return m.Discriminator
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetAesKey() string {
	if m != nil {
		return m.AesKey
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetMaxLiveSeconds() uint32 {
	if m != nil {
		return m.MaxLiveSeconds
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value) GetConversationCreateTime() string {
	if m != nil {
		return m.ConversationCreateTime
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value) GetDisplayImage() uint32 {
	if m != nil {
		return m.DisplayImage
	}
	return 0
}

type Conversation_ConversationDetailResponse_Value_User struct {
	Id                   uint32                                                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JoinTime             string                                                   `protobuf:"bytes,2,opt,name=joinTime,proto3" json:"joinTime,omitempty"`
	Muted                bool                                                     `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	User                 *Conversation_ConversationDetailResponse_Value_User_User `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	GroupId              uint32                                                   `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ReadTimeStamp        string                                                   `protobuf:"bytes,6,opt,name=readTimeStamp,proto3" json:"readTimeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *Conversation_ConversationDetailResponse_Value_User) Reset() {
	*m = Conversation_ConversationDetailResponse_Value_User{}
}
func (m *Conversation_ConversationDetailResponse_Value_User) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_ConversationDetailResponse_Value_User) ProtoMessage() {}
func (*Conversation_ConversationDetailResponse_Value_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7, 0, 0}
}

func (m *Conversation_ConversationDetailResponse_Value_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailResponse_Value_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailResponse_Value_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User.Merge(m, src)
}
func (m *Conversation_ConversationDetailResponse_Value_User) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User.Size(m)
}
func (m *Conversation_ConversationDetailResponse_Value_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User proto.InternalMessageInfo

func (m *Conversation_ConversationDetailResponse_Value_User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value_User) GetJoinTime() string {
	if m != nil {
		return m.JoinTime
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *Conversation_ConversationDetailResponse_Value_User) GetUser() *Conversation_ConversationDetailResponse_Value_User_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Conversation_ConversationDetailResponse_Value_User) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value_User) GetReadTimeStamp() string {
	if m != nil {
		return m.ReadTimeStamp
	}
	return ""
}

type Conversation_ConversationDetailResponse_Value_User_User struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) Reset() {
	*m = Conversation_ConversationDetailResponse_Value_User_User{}
}
func (m *Conversation_ConversationDetailResponse_Value_User_User) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_ConversationDetailResponse_Value_User_User) ProtoMessage() {}
func (*Conversation_ConversationDetailResponse_Value_User_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7, 0, 0, 0}
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User_User.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailResponse_Value_User_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User_User.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailResponse_Value_User_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User_User.Merge(m, src)
}
func (m *Conversation_ConversationDetailResponse_Value_User_User) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User_User.Size(m)
}
func (m *Conversation_ConversationDetailResponse_Value_User_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User_User.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailResponse_Value_User_User proto.InternalMessageInfo

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_User_User) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Conversation_ConversationDetailResponse_Value_RequestUser struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) Reset() {
	*m = Conversation_ConversationDetailResponse_Value_RequestUser{}
}
func (m *Conversation_ConversationDetailResponse_Value_RequestUser) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_ConversationDetailResponse_Value_RequestUser) ProtoMessage() {}
func (*Conversation_ConversationDetailResponse_Value_RequestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7, 0, 1}
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_RequestUser.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailResponse_Value_RequestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_RequestUser.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailResponse_Value_RequestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_RequestUser.Merge(m, src)
}
func (m *Conversation_ConversationDetailResponse_Value_RequestUser) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_RequestUser.Size(m)
}
func (m *Conversation_ConversationDetailResponse_Value_RequestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_RequestUser.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailResponse_Value_RequestUser proto.InternalMessageInfo

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_RequestUser) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Conversation_ConversationDetailResponse_Value_TargetUser struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) Reset() {
	*m = Conversation_ConversationDetailResponse_Value_TargetUser{}
}
func (m *Conversation_ConversationDetailResponse_Value_TargetUser) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_ConversationDetailResponse_Value_TargetUser) ProtoMessage() {}
func (*Conversation_ConversationDetailResponse_Value_TargetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7, 0, 2}
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_TargetUser.Unmarshal(m, b)
}
func (m *Conversation_ConversationDetailResponse_Value_TargetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_TargetUser.Marshal(b, m, deterministic)
}
func (m *Conversation_ConversationDetailResponse_Value_TargetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_TargetUser.Merge(m, src)
}
func (m *Conversation_ConversationDetailResponse_Value_TargetUser) XXX_Size() int {
	return xxx_messageInfo_Conversation_ConversationDetailResponse_Value_TargetUser.Size(m)
}
func (m *Conversation_ConversationDetailResponse_Value_TargetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_ConversationDetailResponse_Value_TargetUser.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_ConversationDetailResponse_Value_TargetUser proto.InternalMessageInfo

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Conversation_ConversationDetailResponse_Value_TargetUser) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Conversation_UpdateMessageLifeTimeRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NewLifeTime          uint32   `protobuf:"varint,2,opt,name=NewLifeTime,proto3" json:"NewLifeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_UpdateMessageLifeTimeRequest) Reset() {
	*m = Conversation_UpdateMessageLifeTimeRequest{}
}
func (m *Conversation_UpdateMessageLifeTimeRequest) String() string { return proto.CompactTextString(m) }
func (*Conversation_UpdateMessageLifeTimeRequest) ProtoMessage()    {}
func (*Conversation_UpdateMessageLifeTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{8}
}

func (m *Conversation_UpdateMessageLifeTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_UpdateMessageLifeTimeRequest.Unmarshal(m, b)
}
func (m *Conversation_UpdateMessageLifeTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_UpdateMessageLifeTimeRequest.Marshal(b, m, deterministic)
}
func (m *Conversation_UpdateMessageLifeTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_UpdateMessageLifeTimeRequest.Merge(m, src)
}
func (m *Conversation_UpdateMessageLifeTimeRequest) XXX_Size() int {
	return xxx_messageInfo_Conversation_UpdateMessageLifeTimeRequest.Size(m)
}
func (m *Conversation_UpdateMessageLifeTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_UpdateMessageLifeTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_UpdateMessageLifeTimeRequest proto.InternalMessageInfo

func (m *Conversation_UpdateMessageLifeTimeRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation_UpdateMessageLifeTimeRequest) GetNewLifeTime() uint32 {
	if m != nil {
		return m.NewLifeTime
	}
	return 0
}

type Conversation_UpdateMessageLifeTimeResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation_UpdateMessageLifeTimeResponse) Reset() {
	*m = Conversation_UpdateMessageLifeTimeResponse{}
}
func (m *Conversation_UpdateMessageLifeTimeResponse) String() string {
	return proto.CompactTextString(m)
}
func (*Conversation_UpdateMessageLifeTimeResponse) ProtoMessage() {}
func (*Conversation_UpdateMessageLifeTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{9}
}

func (m *Conversation_UpdateMessageLifeTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation_UpdateMessageLifeTimeResponse.Unmarshal(m, b)
}
func (m *Conversation_UpdateMessageLifeTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation_UpdateMessageLifeTimeResponse.Marshal(b, m, deterministic)
}
func (m *Conversation_UpdateMessageLifeTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation_UpdateMessageLifeTimeResponse.Merge(m, src)
}
func (m *Conversation_UpdateMessageLifeTimeResponse) XXX_Size() int {
	return xxx_messageInfo_Conversation_UpdateMessageLifeTimeResponse.Size(m)
}
func (m *Conversation_UpdateMessageLifeTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation_UpdateMessageLifeTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation_UpdateMessageLifeTimeResponse proto.InternalMessageInfo

func (m *Conversation_UpdateMessageLifeTimeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Conversation_UpdateMessageLifeTimeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("kahla.Conversation_Discriminator", Conversation_Discriminator_name, Conversation_Discriminator_value)
	proto.RegisterType((*Conversation_AllRequest)(nil), "kahla.Conversation_AllRequest")
	proto.RegisterType((*Conversation_AllResponse)(nil), "kahla.Conversation_AllResponse")
	proto.RegisterType((*Conversation_AllResponse_Item)(nil), "kahla.Conversation_AllResponse.Item")
	proto.RegisterType((*Conversation_GetMessageRequest)(nil), "kahla.Conversation_GetMessageRequest")
	proto.RegisterType((*Conversation_GetMessageResponse)(nil), "kahla.Conversation_GetMessageResponse")
	proto.RegisterType((*Conversation_GetMessageResponse_Item)(nil), "kahla.Conversation_GetMessageResponse.Item")
	proto.RegisterType((*Conversation_GetMessageResponse_Item_At)(nil), "kahla.Conversation_GetMessageResponse.Item.At")
	proto.RegisterType((*Conversation_GetMessageResponse_Item_Sender)(nil), "kahla.Conversation_GetMessageResponse.Item.Sender")
	proto.RegisterType((*Conversation_SendMessageRequest)(nil), "kahla.Conversation_SendMessageRequest")
	proto.RegisterType((*Conversation_SendMessageResponse)(nil), "kahla.Conversation_SendMessageResponse")
	proto.RegisterType((*Conversation_ConversationDetailRequest)(nil), "kahla.Conversation_ConversationDetailRequest")
	proto.RegisterType((*Conversation_ConversationDetailResponse)(nil), "kahla.Conversation_ConversationDetailResponse")
	proto.RegisterType((*Conversation_ConversationDetailResponse_Value)(nil), "kahla.Conversation_ConversationDetailResponse.Value")
	proto.RegisterType((*Conversation_ConversationDetailResponse_Value_User)(nil), "kahla.Conversation_ConversationDetailResponse.Value.User")
	proto.RegisterType((*Conversation_ConversationDetailResponse_Value_User_User)(nil), "kahla.Conversation_ConversationDetailResponse.Value.User.User")
	proto.RegisterType((*Conversation_ConversationDetailResponse_Value_RequestUser)(nil), "kahla.Conversation_ConversationDetailResponse.Value.RequestUser")
	proto.RegisterType((*Conversation_ConversationDetailResponse_Value_TargetUser)(nil), "kahla.Conversation_ConversationDetailResponse.Value.TargetUser")
	proto.RegisterType((*Conversation_UpdateMessageLifeTimeRequest)(nil), "kahla.Conversation_UpdateMessageLifeTimeRequest")
	proto.RegisterType((*Conversation_UpdateMessageLifeTimeResponse)(nil), "kahla.Conversation_UpdateMessageLifeTimeResponse")
}

func init() { proto.RegisterFile("conversation.proto", fileDescriptor_d6ae46d001825652) }

var fileDescriptor_d6ae46d001825652 = []byte{
	// 1246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4b, 0x73, 0x1b, 0xc5,
	0x13, 0xff, 0xeb, 0x69, 0xb9, 0xe5, 0xe7, 0xfc, 0x49, 0xb2, 0xb5, 0x45, 0x25, 0xaa, 0xad, 0xe0,
	0x18, 0x03, 0x2a, 0x10, 0x14, 0x05, 0x1c, 0x42, 0x54, 0x0e, 0x49, 0x29, 0x38, 0xc1, 0x35, 0x76,
	0x38, 0x90, 0xa2, 0xc2, 0x58, 0x3b, 0x96, 0x07, 0xed, 0x43, 0xec, 0x8c, 0x6c, 0xe7, 0x06, 0x27,
	0xce, 0x7c, 0x02, 0x8a, 0x2b, 0x1f, 0x80, 0x33, 0xc5, 0x01, 0x38, 0xf2, 0x91, 0xa8, 0x9e, 0x19,
	0x49, 0xbb, 0x7a, 0x60, 0x7b, 0xcf, 0xbe, 0x4d, 0xff, 0x76, 0xa6, 0xe7, 0xd1, 0xbf, 0x5f, 0x77,
	0x4b, 0x40, 0xba, 0x71, 0x74, 0xca, 0x13, 0xc9, 0x94, 0x88, 0xa3, 0xe6, 0x20, 0x89, 0x55, 0x4c,
	0x2a, 0x7d, 0x76, 0x12, 0x30, 0x77, 0x85, 0x9f, 0x2b, 0x1e, 0xf9, 0x06, 0xf4, 0xda, 0x70, 0x6b,
	0x37, 0x35, 0xf5, 0x65, 0x3b, 0x08, 0x28, 0xff, 0x6e, 0xc8, 0xa5, 0x22, 0x04, 0xca, 0x87, 0xac,
	0xcf, 0x9d, 0x42, 0xa3, 0xb0, 0xbd, 0x4a, 0xf5, 0x18, 0xb1, 0x83, 0xbe, 0x18, 0x38, 0x45, 0x83,
	0xe1, 0xd8, 0xfb, 0xb1, 0x0c, 0xce, 0xac, 0x0f, 0x39, 0x88, 0x23, 0xa9, 0x17, 0x74, 0x63, 0xdf,
	0x38, 0xd9, 0xa4, 0x7a, 0x4c, 0x1c, 0x58, 0x0a, 0xb9, 0x94, 0xac, 0xc7, 0xb5, 0x9f, 0x65, 0x3a,
	0x32, 0xc9, 0x27, 0x50, 0x11, 0x8a, 0x87, 0xd2, 0x29, 0x35, 0x4a, 0xdb, 0xf5, 0xd6, 0xdd, 0xa6,
	0x3e, 0x72, 0x73, 0x91, 0xf7, 0x66, 0x47, 0xf1, 0x90, 0x9a, 0x25, 0xee, 0xf7, 0x25, 0x28, 0xa3,
	0x4d, 0x1a, 0x50, 0xf7, 0x85, 0x1c, 0x04, 0xec, 0xd5, 0x33, 0x16, 0x9a, 0x9d, 0x97, 0x69, 0x1a,
	0x22, 0xdb, 0xb0, 0x6e, 0xcd, 0x4e, 0xc8, 0x7a, 0xfc, 0x73, 0xfe, 0xca, 0x5e, 0x68, 0x1a, 0x26,
	0x77, 0x61, 0x35, 0x60, 0x8a, 0x4b, 0xf5, 0xd4, 0x1e, 0xb8, 0xa4, 0xbd, 0x65, 0x41, 0xf2, 0x36,
	0x6c, 0x66, 0x80, 0x43, 0x11, 0x72, 0xa7, 0xac, 0x67, 0xce, 0x7e, 0x20, 0x1e, 0xac, 0x0c, 0x23,
	0xca, 0x99, 0xdf, 0x0e, 0xe3, 0x61, 0xa4, 0x9c, 0x8a, 0xde, 0x3a, 0x83, 0x91, 0x2d, 0x58, 0x4b,
	0x47, 0xb0, 0xe3, 0x3b, 0x55, 0x3d, 0x6b, 0x0a, 0xc5, 0xf3, 0xf9, 0x42, 0x76, 0x13, 0x11, 0x8a,
	0x88, 0xa9, 0x38, 0x71, 0x96, 0xcc, 0xf9, 0x32, 0x20, 0xb9, 0x09, 0xd5, 0xa1, 0xe4, 0x49, 0xc7,
	0x77, 0x6a, 0xfa, 0xb3, 0xb5, 0x10, 0x67, 0x5c, 0xe2, 0xf5, 0x97, 0x0d, 0x6e, 0x2c, 0xf2, 0x1a,
	0x54, 0xc2, 0xa1, 0xe2, 0xbe, 0x03, 0x8d, 0xc2, 0x76, 0x8d, 0x1a, 0x03, 0xdf, 0x55, 0xc6, 0x21,
	0x8f, 0x23, 0xde, 0x56, 0x4f, 0xb9, 0x53, 0xd7, 0xdf, 0xd2, 0x90, 0xf7, 0x0d, 0xdc, 0xce, 0x84,
	0xea, 0x31, 0x1f, 0x5d, 0x7c, 0xc4, 0xa9, 0x35, 0x28, 0x0a, 0xdf, 0x32, 0xaa, 0x28, 0x7c, 0xe2,
	0x42, 0x4d, 0xf6, 0xc5, 0xe0, 0x50, 0x04, 0x81, 0x0d, 0xc1, 0xd8, 0x46, 0xea, 0x28, 0xe4, 0x5f,
	0xc9, 0x70, 0x0d, 0xc7, 0xde, 0x6f, 0x55, 0xb8, 0xb3, 0x70, 0x8b, 0x5c, 0x94, 0x6b, 0x67, 0x29,
	0xf7, 0xd6, 0x3c, 0xca, 0xcd, 0x6e, 0x92, 0x61, 0xde, 0x2f, 0x15, 0xcb, 0xbc, 0xe9, 0xdb, 0xcd,
	0x46, 0xb1, 0x38, 0x37, 0x8a, 0x0f, 0xa0, 0xc4, 0xd4, 0xe8, 0x04, 0xcd, 0x2b, 0x9c, 0xa0, 0xd9,
	0x56, 0x14, 0x97, 0xea, 0x77, 0xe4, 0x91, 0xaf, 0x63, 0x6c, 0x88, 0x37, 0xb6, 0xc9, 0x13, 0xa8,
	0x9a, 0xb1, 0x66, 0x5a, 0xbd, 0xd5, 0xba, 0xca, 0x06, 0x07, 0x7a, 0x25, 0xb5, 0x1e, 0x46, 0xfb,
	0x68, 0x82, 0x57, 0x27, 0xfb, 0x68, 0x5e, 0x3b, 0xb0, 0xd4, 0x8d, 0x23, 0xc5, 0x23, 0x65, 0x59,
	0x38, 0x32, 0x31, 0x22, 0x09, 0x67, 0x86, 0x7d, 0x35, 0xaa, 0xc7, 0xee, 0x36, 0x14, 0xdb, 0x0a,
	0xb5, 0xa0, 0x58, 0xd2, 0xe3, 0xea, 0xb9, 0xe1, 0xa7, 0x11, 0x6b, 0x06, 0x73, 0xff, 0x28, 0x42,
	0xd5, 0x1c, 0x03, 0x85, 0x1b, 0xb2, 0x3e, 0xff, 0x2c, 0x64, 0x22, 0xd8, 0x1f, 0x1e, 0x05, 0xa2,
	0xab, 0x57, 0xd4, 0xe8, 0x34, 0x8c, 0x14, 0xe6, 0x68, 0xda, 0x70, 0x1b, 0xc3, 0x06, 0xc8, 0x68,
	0x18, 0x03, 0xb4, 0x01, 0xa5, 0x23, 0x11, 0xdb, 0x17, 0xc3, 0x21, 0x5e, 0x30, 0x12, 0xdd, 0xbe,
	0xce, 0x1c, 0x15, 0x73, 0xc1, 0x91, 0x8d, 0xb3, 0x25, 0x3f, 0xb7, 0xf7, 0xc6, 0x21, 0x06, 0xf8,
	0x84, 0x33, 0xbf, 0x13, 0xf6, 0x1e, 0x89, 0x40, 0xe7, 0x91, 0x25, 0x13, 0xe0, 0x2c, 0x4a, 0x76,
	0x60, 0x63, 0x90, 0xf0, 0x63, 0x9e, 0x70, 0x7f, 0x8f, 0x45, 0xbd, 0x21, 0xf2, 0xd0, 0x48, 0x71,
	0x06, 0xc7, 0x64, 0xc2, 0xba, 0x5d, 0xcc, 0x02, 0xbb, 0x09, 0x67, 0xca, 0x24, 0x13, 0xa3, 0xcf,
	0xd9, 0x0f, 0x78, 0x02, 0x7d, 0xb5, 0xdd, 0x38, 0x3a, 0x16, 0x49, 0x38, 0xd6, 0xec, 0x14, 0xea,
	0xbd, 0x98, 0xd2, 0x0d, 0x3e, 0xe8, 0xac, 0x36, 0x3b, 0x63, 0xf6, 0x76, 0x7c, 0x8c, 0xe7, 0xae,
	0x8d, 0xa7, 0xd5, 0x8c, 0x35, 0x71, 0x66, 0x5b, 0x69, 0xba, 0x2e, 0xd3, 0x62, 0x5b, 0x79, 0xfb,
	0xd0, 0x58, 0xec, 0x3c, 0x8f, 0x2a, 0xbd, 0x8f, 0x60, 0x2b, 0xe3, 0x31, 0x6d, 0x3c, 0xe4, 0x8a,
	0x89, 0x60, 0x41, 0x46, 0xf1, 0xfe, 0xd9, 0x80, 0x7b, 0x17, 0x2e, 0xcd, 0x95, 0x29, 0x9e, 0x40,
	0xe5, 0x94, 0x05, 0x43, 0x93, 0x90, 0xea, 0xad, 0x0f, 0xe6, 0xc9, 0x68, 0xf1, 0x66, 0xcd, 0x2f,
	0x71, 0x2d, 0x35, 0x2e, 0xdc, 0x5f, 0xd7, 0xa1, 0xa2, 0x01, 0xf2, 0x05, 0x54, 0x30, 0x1b, 0x4b,
	0xa7, 0xa0, 0xd5, 0xff, 0x71, 0x1e, 0xaf, 0x4d, 0x54, 0x0a, 0x35, 0x7e, 0xb0, 0x24, 0xf4, 0x92,
	0x78, 0x38, 0x98, 0x2a, 0x6d, 0x59, 0x90, 0xbc, 0x0e, 0xcb, 0x1a, 0xd0, 0x44, 0x37, 0x82, 0x98,
	0x00, 0x98, 0xea, 0x4f, 0x98, 0xdc, 0x67, 0x52, 0x9e, 0xc5, 0x89, 0xc9, 0x28, 0x35, 0x9a, 0x86,
	0xf0, 0x99, 0xe2, 0xb3, 0x48, 0x6b, 0xd6, 0xc8, 0x64, 0x64, 0xe2, 0xda, 0xc4, 0xc4, 0x46, 0x7f,
	0x5d, 0x35, 0xe5, 0x37, 0x05, 0x91, 0xa3, 0xf1, 0x0c, 0x3c, 0xb7, 0xb3, 0xa6, 0x9f, 0xf3, 0x41,
	0xae, 0x8b, 0xd3, 0x89, 0x1f, 0x9a, 0x76, 0x8a, 0x3a, 0x36, 0x49, 0xa4, 0xe3, 0x3b, 0xeb, 0x46,
	0xc7, 0x23, 0x9b, 0xbc, 0x04, 0x98, 0x24, 0x18, 0x67, 0x43, 0x6f, 0xff, 0x69, 0xae, 0xed, 0x0f,
	0xc7, 0x6e, 0x68, 0xca, 0x25, 0x86, 0x80, 0x45, 0xb1, 0x3a, 0xe1, 0x89, 0x4d, 0x6b, 0x9b, 0xa6,
	0x2a, 0x67, 0x40, 0xcb, 0xdc, 0xea, 0xb8, 0x5a, 0x5c, 0xba, 0x96, 0xdb, 0x9a, 0x5d, 0xcb, 0xd4,
	0xec, 0x2d, 0x58, 0x0b, 0xd9, 0xf9, 0x9e, 0x38, 0xe5, 0x07, 0xbc, 0x1b, 0x47, 0xbe, 0xd4, 0x39,
	0x63, 0x95, 0x4e, 0xa1, 0xe4, 0x43, 0xb8, 0x99, 0xae, 0x3e, 0xa9, 0x1c, 0x03, 0xda, 0xdf, 0x82,
	0xaf, 0xd3, 0x5d, 0x55, 0x7d, 0xb6, 0xab, 0xf2, 0x60, 0x25, 0xdd, 0x3e, 0x39, 0x2b, 0xa6, 0xaf,
	0x49, 0x63, 0xee, 0xcf, 0x65, 0x28, 0xeb, 0x27, 0x9a, 0xd3, 0x08, 0x7c, 0x1b, 0x8b, 0x48, 0x1f,
	0xc4, 0xe8, 0x6e, 0x6c, 0x4f, 0xda, 0x91, 0x52, 0xba, 0x1d, 0xa1, 0x50, 0x46, 0xc2, 0x6b, 0x72,
	0xd6, 0x5b, 0xf7, 0x73, 0xeb, 0xc6, 0x88, 0x47, 0xfb, 0x42, 0x56, 0x1b, 0x99, 0xf8, 0xb6, 0x2b,
	0x1b, 0x99, 0x18, 0x1c, 0x2c, 0x5b, 0x78, 0x9e, 0x03, 0xc5, 0xc2, 0x81, 0xad, 0x02, 0x59, 0xd0,
	0xfd, 0xbd, 0x68, 0xaf, 0x77, 0x5d, 0xa8, 0x72, 0x16, 0x2a, 0xf7, 0xaf, 0x22, 0xd4, 0x53, 0xaa,
	0xbe, 0x7e, 0xc9, 0xdc, 0x2f, 0xf9, 0x67, 0x11, 0x60, 0x92, 0xa0, 0xae, 0x1f, 0x32, 0x77, 0xef,
	0xf4, 0x35, 0xbc, 0x99, 0x49, 0x2b, 0xcf, 0x07, 0x3e, 0x53, 0xdc, 0x36, 0x38, 0x7b, 0xe2, 0x58,
	0x7b, 0x5b, 0xd4, 0x45, 0x35, 0xa0, 0xfe, 0x8c, 0x9f, 0x8d, 0x66, 0xd9, 0x62, 0x9c, 0x86, 0xbc,
	0xaf, 0x60, 0xe7, 0x32, 0xee, 0xf3, 0xf4, 0x2c, 0x3b, 0x7b, 0xe0, 0x66, 0x7c, 0x3f, 0xcc, 0xd4,
	0x92, 0x5b, 0xf0, 0xff, 0xfd, 0x44, 0x9c, 0x32, 0xc5, 0xd3, 0x93, 0x36, 0xfe, 0x47, 0x6e, 0xc0,
	0xe6, 0x63, 0x4c, 0x7c, 0x19, 0xb8, 0xd0, 0xfa, 0xa9, 0x0c, 0x2b, 0x69, 0x88, 0x3c, 0x82, 0x52,
	0x3b, 0x08, 0xc8, 0xed, 0x85, 0xbf, 0xd3, 0xf5, 0x9b, 0xb8, 0x77, 0x2e, 0xf8, 0x1d, 0x4f, 0x5e,
	0x00, 0x4c, 0x7e, 0x80, 0x90, 0x37, 0x2e, 0xfa, 0x81, 0x62, 0xbc, 0x6e, 0x5d, 0xee, 0x77, 0x0c,
	0xe9, 0x42, 0x3d, 0xd5, 0x90, 0x92, 0xb9, 0xcb, 0x66, 0xdb, 0x61, 0xf7, 0xde, 0x85, 0xf3, 0x8c,
	0x7f, 0xaf, 0xf4, 0xf7, 0xfd, 0x02, 0x91, 0x40, 0x66, 0xab, 0x0d, 0x79, 0xe7, 0xb2, 0x55, 0xc9,
	0x6c, 0xd9, 0xbc, 0x5a, 0x11, 0x23, 0x3f, 0x14, 0xe0, 0xc6, 0x5c, 0xb6, 0x90, 0x77, 0xe7, 0x79,
	0xfa, 0x2f, 0xde, 0xba, 0xef, 0x5d, 0x61, 0x45, 0xea, 0xe2, 0x47, 0x55, 0xfd, 0x3f, 0xd2, 0xfb,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x7c, 0xe9, 0xa8, 0x72, 0x12, 0x00, 0x00,
}

// Generated by go-rest-client
type ConversationService struct {
	client  *http.Client
	baseUrl string
}

func NewConversationService(client *http.Client, baseUrl string) *ConversationService {
	return &ConversationService{
		client:  client,
		baseUrl: baseUrl,
	}
}
func (s *ConversationService) All(in *Conversation_AllRequest) (*Conversation_AllResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("Take", strconv.FormatUint(uint64(in.Take), 10))
	v.Add("Skip", strconv.FormatUint(uint64(in.Skip), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Conversation/All?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Conversation_AllResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *ConversationService) GetMessage(in *Conversation_GetMessageRequest) (*Conversation_GetMessageResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("id", strconv.FormatUint(uint64(in.Id), 10))
	v.Add("skipTill", strconv.FormatUint(uint64(in.SkipTill), 10))
	v.Add("take", strconv.FormatUint(uint64(in.Take), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Conversation/GetMessage?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Conversation_GetMessageResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *ConversationService) SendMessage(in *Conversation_SendMessageRequest) (*Conversation_SendMessageResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("Id", strconv.FormatUint(uint64(in.Id), 10))
	v.Add("Content", in.Content)
	for _, v1 := range in.At {
		v.Add("At", v1)
	}
	req, err := http.NewRequest("POST", s.baseUrl+"/Conversation/SendMessage", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Conversation_SendMessageResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *ConversationService) ConversationDetail(in *Conversation_ConversationDetailRequest) (*Conversation_ConversationDetailResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("id", strconv.FormatUint(uint64(in.Id), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Conversation/ConversationDetail?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Conversation_ConversationDetailResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *ConversationService) UpdateMessageLifeTime(in *Conversation_UpdateMessageLifeTimeRequest) (*Conversation_UpdateMessageLifeTimeResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("Id", strconv.FormatUint(uint64(in.Id), 10))
	v.Add("NewLifeTime", strconv.FormatUint(uint64(in.NewLifeTime), 10))
	req, err := http.NewRequest("POST", s.baseUrl+"/Conversation/UpdateMessageLifeTime", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Conversation_UpdateMessageLifeTimeResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
