// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devices.proto

package kahla

import (
	json "encoding/json"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
	http "net/http"
	url "net/url"
	strconv "strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Devices_AddDeviceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	PushEndpoint         string   `protobuf:"bytes,2,opt,name=PushEndpoint,proto3" json:"PushEndpoint,omitempty"`
	PushP256DH           string   `protobuf:"bytes,3,opt,name=PushP256DH,proto3" json:"PushP256DH,omitempty"`
	PushAuth             string   `protobuf:"bytes,4,opt,name=PushAuth,proto3" json:"PushAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices_AddDeviceRequest) Reset()         { *m = Devices_AddDeviceRequest{} }
func (m *Devices_AddDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*Devices_AddDeviceRequest) ProtoMessage()    {}
func (*Devices_AddDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{0}
}

func (m *Devices_AddDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_AddDeviceRequest.Unmarshal(m, b)
}
func (m *Devices_AddDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_AddDeviceRequest.Marshal(b, m, deterministic)
}
func (m *Devices_AddDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_AddDeviceRequest.Merge(m, src)
}
func (m *Devices_AddDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_Devices_AddDeviceRequest.Size(m)
}
func (m *Devices_AddDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_AddDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_AddDeviceRequest proto.InternalMessageInfo

func (m *Devices_AddDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Devices_AddDeviceRequest) GetPushEndpoint() string {
	if m != nil {
		return m.PushEndpoint
	}
	return ""
}

func (m *Devices_AddDeviceRequest) GetPushP256DH() string {
	if m != nil {
		return m.PushP256DH
	}
	return ""
}

func (m *Devices_AddDeviceRequest) GetPushAuth() string {
	if m != nil {
		return m.PushAuth
	}
	return ""
}

type Devices_AddDeviceResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices_AddDeviceResponse) Reset()         { *m = Devices_AddDeviceResponse{} }
func (m *Devices_AddDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*Devices_AddDeviceResponse) ProtoMessage()    {}
func (*Devices_AddDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{1}
}

func (m *Devices_AddDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_AddDeviceResponse.Unmarshal(m, b)
}
func (m *Devices_AddDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_AddDeviceResponse.Marshal(b, m, deterministic)
}
func (m *Devices_AddDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_AddDeviceResponse.Merge(m, src)
}
func (m *Devices_AddDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_Devices_AddDeviceResponse.Size(m)
}
func (m *Devices_AddDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_AddDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_AddDeviceResponse proto.InternalMessageInfo

func (m *Devices_AddDeviceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Devices_AddDeviceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Devices_UpdateDeviceRequest struct {
	DeviceId             uint32   `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	PushEndpoint         string   `protobuf:"bytes,3,opt,name=PushEndpoint,proto3" json:"PushEndpoint,omitempty"`
	PushP256DH           string   `protobuf:"bytes,4,opt,name=PushP256DH,proto3" json:"PushP256DH,omitempty"`
	PushAuth             string   `protobuf:"bytes,5,opt,name=PushAuth,proto3" json:"PushAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices_UpdateDeviceRequest) Reset()         { *m = Devices_UpdateDeviceRequest{} }
func (m *Devices_UpdateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*Devices_UpdateDeviceRequest) ProtoMessage()    {}
func (*Devices_UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{2}
}

func (m *Devices_UpdateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_UpdateDeviceRequest.Unmarshal(m, b)
}
func (m *Devices_UpdateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_UpdateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *Devices_UpdateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_UpdateDeviceRequest.Merge(m, src)
}
func (m *Devices_UpdateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_Devices_UpdateDeviceRequest.Size(m)
}
func (m *Devices_UpdateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_UpdateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_UpdateDeviceRequest proto.InternalMessageInfo

func (m *Devices_UpdateDeviceRequest) GetDeviceId() uint32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Devices_UpdateDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Devices_UpdateDeviceRequest) GetPushEndpoint() string {
	if m != nil {
		return m.PushEndpoint
	}
	return ""
}

func (m *Devices_UpdateDeviceRequest) GetPushP256DH() string {
	if m != nil {
		return m.PushP256DH
	}
	return ""
}

func (m *Devices_UpdateDeviceRequest) GetPushAuth() string {
	if m != nil {
		return m.PushAuth
	}
	return ""
}

type Devices_UpdateDeviceResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices_UpdateDeviceResponse) Reset()         { *m = Devices_UpdateDeviceResponse{} }
func (m *Devices_UpdateDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*Devices_UpdateDeviceResponse) ProtoMessage()    {}
func (*Devices_UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{3}
}

func (m *Devices_UpdateDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_UpdateDeviceResponse.Unmarshal(m, b)
}
func (m *Devices_UpdateDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_UpdateDeviceResponse.Marshal(b, m, deterministic)
}
func (m *Devices_UpdateDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_UpdateDeviceResponse.Merge(m, src)
}
func (m *Devices_UpdateDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_Devices_UpdateDeviceResponse.Size(m)
}
func (m *Devices_UpdateDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_UpdateDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_UpdateDeviceResponse proto.InternalMessageInfo

func (m *Devices_UpdateDeviceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Devices_UpdateDeviceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Devices_MyDevicesResponse struct {
	Code                 int32                             `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items                []*Devices_MyDevicesResponse_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Devices_MyDevicesResponse) Reset()         { *m = Devices_MyDevicesResponse{} }
func (m *Devices_MyDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*Devices_MyDevicesResponse) ProtoMessage()    {}
func (*Devices_MyDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{4}
}

func (m *Devices_MyDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_MyDevicesResponse.Unmarshal(m, b)
}
func (m *Devices_MyDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_MyDevicesResponse.Marshal(b, m, deterministic)
}
func (m *Devices_MyDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_MyDevicesResponse.Merge(m, src)
}
func (m *Devices_MyDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_Devices_MyDevicesResponse.Size(m)
}
func (m *Devices_MyDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_MyDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_MyDevicesResponse proto.InternalMessageInfo

func (m *Devices_MyDevicesResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Devices_MyDevicesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Devices_MyDevicesResponse) GetItems() []*Devices_MyDevicesResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Devices_MyDevicesResponse_Item struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress            string   `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	AddTime              string   `protobuf:"bytes,5,opt,name=addTime,proto3" json:"addTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices_MyDevicesResponse_Item) Reset()         { *m = Devices_MyDevicesResponse_Item{} }
func (m *Devices_MyDevicesResponse_Item) String() string { return proto.CompactTextString(m) }
func (*Devices_MyDevicesResponse_Item) ProtoMessage()    {}
func (*Devices_MyDevicesResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{4, 0}
}

func (m *Devices_MyDevicesResponse_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_MyDevicesResponse_Item.Unmarshal(m, b)
}
func (m *Devices_MyDevicesResponse_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_MyDevicesResponse_Item.Marshal(b, m, deterministic)
}
func (m *Devices_MyDevicesResponse_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_MyDevicesResponse_Item.Merge(m, src)
}
func (m *Devices_MyDevicesResponse_Item) XXX_Size() int {
	return xxx_messageInfo_Devices_MyDevicesResponse_Item.Size(m)
}
func (m *Devices_MyDevicesResponse_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_MyDevicesResponse_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_MyDevicesResponse_Item proto.InternalMessageInfo

func (m *Devices_MyDevicesResponse_Item) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Devices_MyDevicesResponse_Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Devices_MyDevicesResponse_Item) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Devices_MyDevicesResponse_Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Devices_MyDevicesResponse_Item) GetAddTime() string {
	if m != nil {
		return m.AddTime
	}
	return ""
}

type Devices_PushTestMessageResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devices_PushTestMessageResponse) Reset()         { *m = Devices_PushTestMessageResponse{} }
func (m *Devices_PushTestMessageResponse) String() string { return proto.CompactTextString(m) }
func (*Devices_PushTestMessageResponse) ProtoMessage()    {}
func (*Devices_PushTestMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d27ec3f2c0e2043, []int{5}
}

func (m *Devices_PushTestMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices_PushTestMessageResponse.Unmarshal(m, b)
}
func (m *Devices_PushTestMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices_PushTestMessageResponse.Marshal(b, m, deterministic)
}
func (m *Devices_PushTestMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices_PushTestMessageResponse.Merge(m, src)
}
func (m *Devices_PushTestMessageResponse) XXX_Size() int {
	return xxx_messageInfo_Devices_PushTestMessageResponse.Size(m)
}
func (m *Devices_PushTestMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices_PushTestMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Devices_PushTestMessageResponse proto.InternalMessageInfo

func (m *Devices_PushTestMessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Devices_PushTestMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Devices_AddDeviceRequest)(nil), "kahla.Devices_AddDeviceRequest")
	proto.RegisterType((*Devices_AddDeviceResponse)(nil), "kahla.Devices_AddDeviceResponse")
	proto.RegisterType((*Devices_UpdateDeviceRequest)(nil), "kahla.Devices_UpdateDeviceRequest")
	proto.RegisterType((*Devices_UpdateDeviceResponse)(nil), "kahla.Devices_UpdateDeviceResponse")
	proto.RegisterType((*Devices_MyDevicesResponse)(nil), "kahla.Devices_MyDevicesResponse")
	proto.RegisterType((*Devices_MyDevicesResponse_Item)(nil), "kahla.Devices_MyDevicesResponse.Item")
	proto.RegisterType((*Devices_PushTestMessageResponse)(nil), "kahla.Devices_PushTestMessageResponse")
}

func init() { proto.RegisterFile("devices.proto", fileDescriptor_6d27ec3f2c0e2043) }

var fileDescriptor_6d27ec3f2c0e2043 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x1f, 0x69, 0xeb, 0x4b, 0x0a, 0x62, 0x16, 0x95, 0x71, 0x2b, 0x1a, 0x19, 0x81, 0xba,
	0x72, 0xa5, 0x20, 0xd8, 0xb0, 0x8a, 0xd4, 0x48, 0x58, 0xa2, 0xa5, 0x58, 0x41, 0x2c, 0x91, 0x93,
	0xb9, 0x24, 0x16, 0xf1, 0x83, 0xcc, 0x18, 0x11, 0x96, 0x7c, 0x00, 0x7f, 0xc2, 0x9f, 0xf0, 0x51,
	0x68, 0x1e, 0x76, 0x12, 0x27, 0x0e, 0x52, 0x76, 0xf7, 0xdc, 0x99, 0x39, 0x3a, 0xe7, 0xf8, 0xfa,
	0xc2, 0x29, 0xc5, 0xef, 0xc9, 0x04, 0x59, 0x50, 0x2c, 0x72, 0x9e, 0x93, 0xce, 0xd7, 0x78, 0x36,
	0x8f, 0xbd, 0x2e, 0xfe, 0xe0, 0x98, 0x51, 0xd5, 0xf4, 0xce, 0xa7, 0x79, 0x3e, 0x9d, 0xe3, 0xb5,
	0x44, 0xe3, 0xf2, 0xcb, 0x35, 0xa6, 0x05, 0x5f, 0xaa, 0x43, 0xff, 0xb7, 0x01, 0xee, 0x8d, 0xe2,
	0xf8, 0x3c, 0xa0, 0x54, 0x95, 0x11, 0x7e, 0x2b, 0x91, 0x71, 0x42, 0xc0, 0xbe, 0x8b, 0x53, 0x74,
	0x8d, 0x9e, 0x71, 0xe5, 0x44, 0xb2, 0x26, 0x3e, 0x74, 0xef, 0x4b, 0x36, 0x1b, 0x66, 0xb4, 0xc8,
	0x93, 0x8c, 0xbb, 0xa6, 0x3c, 0xdb, 0xe8, 0x91, 0xa7, 0x00, 0x02, 0xdf, 0xf7, 0x5f, 0xbd, 0xbe,
	0x79, 0xeb, 0x5a, 0xf2, 0xc6, 0x5a, 0x87, 0x78, 0x70, 0x22, 0xd0, 0xa0, 0xe4, 0x33, 0xd7, 0x96,
	0xa7, 0x35, 0xf6, 0x43, 0x78, 0xb2, 0x43, 0x0f, 0x2b, 0xf2, 0x8c, 0xa1, 0x10, 0x34, 0xc9, 0xa9,
	0x12, 0xf4, 0x38, 0x92, 0x35, 0x71, 0xe1, 0x38, 0x45, 0xc6, 0xe2, 0x29, 0x6a, 0x2d, 0x15, 0xf4,
	0xff, 0x18, 0x70, 0x5e, 0x71, 0x7d, 0x2c, 0x68, 0xcc, 0x71, 0xd3, 0x9e, 0x07, 0x27, 0xaa, 0x11,
	0x52, 0xc9, 0x78, 0x1a, 0xd5, 0xb8, 0xb6, 0x6e, 0xee, 0xb1, 0x6e, 0xfd, 0xd7, 0xba, 0xbd, 0xd7,
	0x7a, 0xa7, 0x61, 0xfd, 0x1d, 0x5c, 0xec, 0x96, 0x7b, 0x90, 0xfb, 0x5f, 0xe6, 0x2a, 0xc9, 0xdb,
	0xa5, 0xae, 0x0e, 0xe3, 0x22, 0x6f, 0xa0, 0x93, 0x70, 0x4c, 0x99, 0x6b, 0xf5, 0xac, 0xab, 0x07,
	0xfd, 0xe7, 0x81, 0x9c, 0xb3, 0xa0, 0x95, 0x3e, 0x08, 0x39, 0xa6, 0x91, 0x7a, 0xe3, 0xfd, 0x04,
	0x5b, 0x40, 0xf2, 0x10, 0xcc, 0xa4, 0x0a, 0xda, 0x4c, 0x64, 0xc4, 0xd9, 0x5a, 0xc4, 0xa2, 0x26,
	0x17, 0xe0, 0x24, 0xc5, 0x80, 0xd2, 0x05, 0x32, 0xa6, 0xf3, 0x5d, 0x35, 0xc8, 0x19, 0x1c, 0x95,
	0x0c, 0x17, 0x21, 0xd5, 0xc1, 0x6a, 0x24, 0x84, 0xc7, 0x94, 0x8e, 0x92, 0x14, 0x75, 0xa6, 0x15,
	0xf4, 0xdf, 0xc3, 0x65, 0x25, 0x52, 0xc4, 0x3c, 0x42, 0xc6, 0x6f, 0x95, 0xa7, 0xc3, 0x92, 0xe8,
	0xff, 0x35, 0xe1, 0x58, 0x33, 0x92, 0x3b, 0x70, 0xea, 0x11, 0x25, 0x97, 0x8d, 0x4c, 0x9a, 0x3f,
	0x93, 0xd7, 0x6b, 0xbf, 0xa0, 0x95, 0x7c, 0x82, 0xee, 0xfa, 0x77, 0x27, 0x7e, 0xe3, 0xc5, 0x8e,
	0x19, 0xf6, 0x9e, 0xed, 0xbd, 0xa3, 0x89, 0x87, 0xe0, 0xd4, 0x9f, 0x88, 0x9c, 0x05, 0x6a, 0x1f,
	0x04, 0xd5, 0x3e, 0x08, 0x86, 0x62, 0x1f, 0x6c, 0xe9, 0xdb, 0x9e, 0x99, 0x0f, 0xf0, 0xa8, 0x11,
	0x62, 0x2b, 0xd9, 0x8b, 0x06, 0x59, 0x4b, 0xf8, 0xe3, 0x23, 0xf9, 0xee, 0xe5, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0xa4, 0x92, 0xff, 0xc8, 0x04, 0x00, 0x00,
}

// Generated by go-rest-client
type DevicesService struct {
	client  *http.Client
	baseUrl string
}

func NewDevicesService(client *http.Client, baseUrl string) *DevicesService {
	return &DevicesService{
		client:  client,
		baseUrl: baseUrl,
	}
}
func (s *DevicesService) AddDevice(in *Devices_AddDeviceRequest) (*Devices_AddDeviceResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("Name", in.Name)
	v.Add("PushEndpoint", in.PushEndpoint)
	v.Add("PushP256DH", in.PushP256DH)
	v.Add("PushAuth", in.PushAuth)
	req, err := http.NewRequest("GET", s.baseUrl+"/Devices/AddDevice?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Devices_AddDeviceResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *DevicesService) UpdateDevice(in *Devices_UpdateDeviceRequest) (*Devices_UpdateDeviceResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("DeviceId", strconv.FormatUint(uint64(in.DeviceId), 10))
	v.Add("Name", in.Name)
	v.Add("PushEndpoint", in.PushEndpoint)
	v.Add("PushP256DH", in.PushP256DH)
	v.Add("PushAuth", in.PushAuth)
	req, err := http.NewRequest("GET", s.baseUrl+"/Devices/UpdateDevice?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Devices_UpdateDeviceResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *DevicesService) MyDevices() (*Devices_MyDevicesResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Devices/MyDevices", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Devices_MyDevicesResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *DevicesService) PushTestMessage() (*Devices_PushTestMessageResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Devices/PushTestMessage", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Devices_PushTestMessageResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
