// Code generated by protoc-gen-go. DO NOT EDIT.
// source: files.proto

package kahla

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"mime/multipart"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Files_UploadIconRequest struct {
	// TODO implement MultiPartForm File
	File                 *RequestFile `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Files_UploadIconRequest) Reset()         { *m = Files_UploadIconRequest{} }
func (m *Files_UploadIconRequest) String() string { return proto.CompactTextString(m) }
func (*Files_UploadIconRequest) ProtoMessage()    {}
func (*Files_UploadIconRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{0}
}

func (m *Files_UploadIconRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_UploadIconRequest.Unmarshal(m, b)
}
func (m *Files_UploadIconRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_UploadIconRequest.Marshal(b, m, deterministic)
}
func (m *Files_UploadIconRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_UploadIconRequest.Merge(m, src)
}
func (m *Files_UploadIconRequest) XXX_Size() int {
	return xxx_messageInfo_Files_UploadIconRequest.Size(m)
}
func (m *Files_UploadIconRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_UploadIconRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Files_UploadIconRequest proto.InternalMessageInfo

func (m *Files_UploadIconRequest) GetFile() *RequestFile {
	if m != nil {
		return m.File
	}
	return nil
}

type Files_UploadIconResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileKey              uint32   `protobuf:"varint,3,opt,name=fileKey,proto3" json:"fileKey,omitempty"`
	DownloadPath         string   `protobuf:"bytes,4,opt,name=downloadPath,proto3" json:"downloadPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files_UploadIconResponse) Reset()         { *m = Files_UploadIconResponse{} }
func (m *Files_UploadIconResponse) String() string { return proto.CompactTextString(m) }
func (*Files_UploadIconResponse) ProtoMessage()    {}
func (*Files_UploadIconResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{1}
}

func (m *Files_UploadIconResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_UploadIconResponse.Unmarshal(m, b)
}
func (m *Files_UploadIconResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_UploadIconResponse.Marshal(b, m, deterministic)
}
func (m *Files_UploadIconResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_UploadIconResponse.Merge(m, src)
}
func (m *Files_UploadIconResponse) XXX_Size() int {
	return xxx_messageInfo_Files_UploadIconResponse.Size(m)
}
func (m *Files_UploadIconResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_UploadIconResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Files_UploadIconResponse proto.InternalMessageInfo

func (m *Files_UploadIconResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Files_UploadIconResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Files_UploadIconResponse) GetFileKey() uint32 {
	if m != nil {
		return m.FileKey
	}
	return 0
}

func (m *Files_UploadIconResponse) GetDownloadPath() string {
	if m != nil {
		return m.DownloadPath
	}
	return ""
}

type Files_UploadMediaRequest struct {
	// TODO implement MultiPartForm File
	File                 *RequestFile `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Files_UploadMediaRequest) Reset()         { *m = Files_UploadMediaRequest{} }
func (m *Files_UploadMediaRequest) String() string { return proto.CompactTextString(m) }
func (*Files_UploadMediaRequest) ProtoMessage()    {}
func (*Files_UploadMediaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{2}
}

func (m *Files_UploadMediaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_UploadMediaRequest.Unmarshal(m, b)
}
func (m *Files_UploadMediaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_UploadMediaRequest.Marshal(b, m, deterministic)
}
func (m *Files_UploadMediaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_UploadMediaRequest.Merge(m, src)
}
func (m *Files_UploadMediaRequest) XXX_Size() int {
	return xxx_messageInfo_Files_UploadMediaRequest.Size(m)
}
func (m *Files_UploadMediaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_UploadMediaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Files_UploadMediaRequest proto.InternalMessageInfo

func (m *Files_UploadMediaRequest) GetFile() *RequestFile {
	if m != nil {
		return m.File
	}
	return nil
}

type Files_UploadMediaResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileKey              string   `protobuf:"bytes,3,opt,name=fileKey,proto3" json:"fileKey,omitempty"`
	DownloadPath         string   `protobuf:"bytes,4,opt,name=downloadPath,proto3" json:"downloadPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files_UploadMediaResponse) Reset()         { *m = Files_UploadMediaResponse{} }
func (m *Files_UploadMediaResponse) String() string { return proto.CompactTextString(m) }
func (*Files_UploadMediaResponse) ProtoMessage()    {}
func (*Files_UploadMediaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{3}
}

func (m *Files_UploadMediaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_UploadMediaResponse.Unmarshal(m, b)
}
func (m *Files_UploadMediaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_UploadMediaResponse.Marshal(b, m, deterministic)
}
func (m *Files_UploadMediaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_UploadMediaResponse.Merge(m, src)
}
func (m *Files_UploadMediaResponse) XXX_Size() int {
	return xxx_messageInfo_Files_UploadMediaResponse.Size(m)
}
func (m *Files_UploadMediaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_UploadMediaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Files_UploadMediaResponse proto.InternalMessageInfo

func (m *Files_UploadMediaResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Files_UploadMediaResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Files_UploadMediaResponse) GetFileKey() string {
	if m != nil {
		return m.FileKey
	}
	return ""
}

func (m *Files_UploadMediaResponse) GetDownloadPath() string {
	if m != nil {
		return m.DownloadPath
	}
	return ""
}

type Files_UploadFileRequest struct {
	// TODO implement MultiPartForm File
	ConversationId       uint32       `protobuf:"varint,1,opt,name=ConversationId,proto3" json:"ConversationId,omitempty"`
	File                 *RequestFile `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Files_UploadFileRequest) Reset()         { *m = Files_UploadFileRequest{} }
func (m *Files_UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*Files_UploadFileRequest) ProtoMessage()    {}
func (*Files_UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{4}
}

func (m *Files_UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_UploadFileRequest.Unmarshal(m, b)
}
func (m *Files_UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *Files_UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_UploadFileRequest.Merge(m, src)
}
func (m *Files_UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_Files_UploadFileRequest.Size(m)
}
func (m *Files_UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Files_UploadFileRequest proto.InternalMessageInfo

func (m *Files_UploadFileRequest) GetConversationId() uint32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *Files_UploadFileRequest) GetFile() *RequestFile {
	if m != nil {
		return m.File
	}
	return nil
}

type Files_UploadFileResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SavedFileName        string   `protobuf:"bytes,3,opt,name=savedFileName,proto3" json:"savedFileName,omitempty"`
	FileKey              uint32   `protobuf:"varint,4,opt,name=fileKey,proto3" json:"fileKey,omitempty"`
	FileSize             uint64   `protobuf:"varint,5,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files_UploadFileResponse) Reset()         { *m = Files_UploadFileResponse{} }
func (m *Files_UploadFileResponse) String() string { return proto.CompactTextString(m) }
func (*Files_UploadFileResponse) ProtoMessage()    {}
func (*Files_UploadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{5}
}

func (m *Files_UploadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_UploadFileResponse.Unmarshal(m, b)
}
func (m *Files_UploadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_UploadFileResponse.Marshal(b, m, deterministic)
}
func (m *Files_UploadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_UploadFileResponse.Merge(m, src)
}
func (m *Files_UploadFileResponse) XXX_Size() int {
	return xxx_messageInfo_Files_UploadFileResponse.Size(m)
}
func (m *Files_UploadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_UploadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Files_UploadFileResponse proto.InternalMessageInfo

func (m *Files_UploadFileResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Files_UploadFileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Files_UploadFileResponse) GetSavedFileName() string {
	if m != nil {
		return m.SavedFileName
	}
	return ""
}

func (m *Files_UploadFileResponse) GetFileKey() uint32 {
	if m != nil {
		return m.FileKey
	}
	return 0
}

func (m *Files_UploadFileResponse) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type Files_FileDownloadAddressRequest struct {
	FileKey              uint32   `protobuf:"varint,1,opt,name=FileKey,proto3" json:"FileKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files_FileDownloadAddressRequest) Reset()         { *m = Files_FileDownloadAddressRequest{} }
func (m *Files_FileDownloadAddressRequest) String() string { return proto.CompactTextString(m) }
func (*Files_FileDownloadAddressRequest) ProtoMessage()    {}
func (*Files_FileDownloadAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{6}
}

func (m *Files_FileDownloadAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_FileDownloadAddressRequest.Unmarshal(m, b)
}
func (m *Files_FileDownloadAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_FileDownloadAddressRequest.Marshal(b, m, deterministic)
}
func (m *Files_FileDownloadAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_FileDownloadAddressRequest.Merge(m, src)
}
func (m *Files_FileDownloadAddressRequest) XXX_Size() int {
	return xxx_messageInfo_Files_FileDownloadAddressRequest.Size(m)
}
func (m *Files_FileDownloadAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_FileDownloadAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Files_FileDownloadAddressRequest proto.InternalMessageInfo

func (m *Files_FileDownloadAddressRequest) GetFileKey() uint32 {
	if m != nil {
		return m.FileKey
	}
	return 0
}

type Files_FileDownloadAddressResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	DownloadPath         string   `protobuf:"bytes,4,opt,name=downloadPath,proto3" json:"downloadPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files_FileDownloadAddressResponse) Reset()         { *m = Files_FileDownloadAddressResponse{} }
func (m *Files_FileDownloadAddressResponse) String() string { return proto.CompactTextString(m) }
func (*Files_FileDownloadAddressResponse) ProtoMessage()    {}
func (*Files_FileDownloadAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{7}
}

func (m *Files_FileDownloadAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files_FileDownloadAddressResponse.Unmarshal(m, b)
}
func (m *Files_FileDownloadAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files_FileDownloadAddressResponse.Marshal(b, m, deterministic)
}
func (m *Files_FileDownloadAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files_FileDownloadAddressResponse.Merge(m, src)
}
func (m *Files_FileDownloadAddressResponse) XXX_Size() int {
	return xxx_messageInfo_Files_FileDownloadAddressResponse.Size(m)
}
func (m *Files_FileDownloadAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Files_FileDownloadAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Files_FileDownloadAddressResponse proto.InternalMessageInfo

func (m *Files_FileDownloadAddressResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Files_FileDownloadAddressResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Files_FileDownloadAddressResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Files_FileDownloadAddressResponse) GetDownloadPath() string {
	if m != nil {
		return m.DownloadPath
	}
	return ""
}

func init() {
	proto.RegisterType((*Files_UploadIconRequest)(nil), "kahla.Files_UploadIconRequest")
	proto.RegisterType((*Files_UploadIconResponse)(nil), "kahla.Files_UploadIconResponse")
	proto.RegisterType((*Files_UploadMediaRequest)(nil), "kahla.Files_UploadMediaRequest")
	proto.RegisterType((*Files_UploadMediaResponse)(nil), "kahla.Files_UploadMediaResponse")
	proto.RegisterType((*Files_UploadFileRequest)(nil), "kahla.Files_UploadFileRequest")
	proto.RegisterType((*Files_UploadFileResponse)(nil), "kahla.Files_UploadFileResponse")
	proto.RegisterType((*Files_FileDownloadAddressRequest)(nil), "kahla.Files_FileDownloadAddressRequest")
	proto.RegisterType((*Files_FileDownloadAddressResponse)(nil), "kahla.Files_FileDownloadAddressResponse")
}

func init() { proto.RegisterFile("files.proto", fileDescriptor_cac8f32ecfdd343c) }

var fileDescriptor_cac8f32ecfdd343c = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcb, 0xce, 0xd2, 0x40,
	0x14, 0xce, 0xf0, 0x17, 0x90, 0x03, 0x98, 0x30, 0x2e, 0x1c, 0xbb, 0xd0, 0xda, 0x78, 0xe9, 0xaa,
	0x0b, 0xdc, 0x1a, 0x22, 0xd1, 0x90, 0x10, 0xa3, 0x31, 0x35, 0x24, 0xee, 0xcc, 0xc8, 0x1c, 0xa5,
	0x11, 0x3a, 0xd8, 0xa9, 0x78, 0x79, 0x00, 0x5d, 0xfb, 0x0e, 0x3e, 0x0c, 0x8f, 0xe1, 0x93, 0x18,
	0x33, 0xd3, 0x8b, 0x2d, 0xb6, 0x28, 0xc4, 0x4d, 0x33, 0xe7, 0xf6, 0xcd, 0xf7, 0x9d, 0x33, 0xa7,
	0xd0, 0x7f, 0x1d, 0xae, 0x51, 0xf9, 0xdb, 0x58, 0x26, 0x92, 0xb6, 0xdf, 0xf2, 0xd5, 0x9a, 0xdb,
	0x03, 0xfc, 0x98, 0x60, 0x24, 0x52, 0xa7, 0xfb, 0x00, 0xae, 0xce, 0x74, 0xce, 0xcb, 0xc5, 0x76,
	0x2d, 0xb9, 0x98, 0x2f, 0x65, 0x14, 0xe0, 0xbb, 0xf7, 0xa8, 0x12, 0x7a, 0x1b, 0x2c, 0x1d, 0x62,
	0xc4, 0x21, 0x5e, 0x7f, 0x3c, 0xf2, 0x63, 0x54, 0x89, 0x9f, 0x05, 0x75, 0x20, 0x30, 0x61, 0xf7,
	0x0b, 0x01, 0xf6, 0x27, 0x84, 0xda, 0xca, 0x48, 0x21, 0xa5, 0x60, 0x2d, 0xa5, 0x48, 0x31, 0x46,
	0x81, 0x39, 0x53, 0x06, 0xdd, 0x0d, 0x2a, 0xc5, 0xdf, 0x20, 0x6b, 0x39, 0xc4, 0xeb, 0x05, 0xb9,
	0xa9, 0x23, 0x9a, 0xf0, 0x63, 0xfc, 0xc4, 0x2e, 0x1c, 0xe2, 0x0d, 0x83, 0xdc, 0xa4, 0x2e, 0x0c,
	0x84, 0xfc, 0x10, 0x69, 0xfc, 0x67, 0x3c, 0x59, 0x31, 0xcb, 0x14, 0x56, 0x7c, 0xee, 0xb4, 0xca,
	0xe3, 0x09, 0x8a, 0x90, 0x9f, 0xa8, 0xe5, 0x2b, 0x81, 0x6b, 0x35, 0x18, 0xff, 0x43, 0x4c, 0xef,
	0x34, 0x31, 0xab, 0xea, 0x5c, 0x0c, 0xc7, 0x4c, 0xcb, 0x1d, 0xb8, 0xfc, 0x50, 0x46, 0x3b, 0x8c,
	0x15, 0x4f, 0x42, 0x19, 0xcd, 0x85, 0x21, 0x34, 0x0c, 0x0e, 0xbc, 0x85, 0xe6, 0xd6, 0x71, 0xcd,
	0xdf, 0x0f, 0xe6, 0x97, 0x5e, 0x75, 0x96, 0xe4, 0x5b, 0x30, 0x54, 0x7c, 0x87, 0x06, 0xe2, 0x29,
	0xdf, 0x60, 0x26, 0xbc, 0xea, 0x2c, 0x37, 0xc6, 0xaa, 0x4e, 0xd9, 0x86, 0x4b, 0xfa, 0xf8, 0x3c,
	0xfc, 0x8c, 0xac, 0xed, 0x10, 0xcf, 0x0a, 0x0a, 0xdb, 0xbd, 0x0f, 0x4e, 0xca, 0x52, 0x7f, 0x1f,
	0x65, 0xad, 0x9a, 0x0a, 0x11, 0xa3, 0x52, 0x79, 0x67, 0x18, 0x74, 0x67, 0x19, 0x72, 0xda, 0x92,
	0xdc, 0x74, 0xbf, 0x11, 0xb8, 0x79, 0xa4, 0xfc, 0x2c, 0xb5, 0x19, 0xdb, 0x92, 0xd0, 0xc2, 0xfe,
	0x97, 0x11, 0x8f, 0x7f, 0xb6, 0xa0, 0x6d, 0x38, 0xd1, 0x05, 0xc0, 0xef, 0xdd, 0xa1, 0xd7, 0x7d,
	0xb3, 0xa8, 0x7e, 0xc3, 0x5e, 0xda, 0x37, 0x1a, 0xe3, 0xa9, 0x0c, 0xb7, 0xb3, 0x9f, 0x90, 0x1f,
	0x13, 0x42, 0x5f, 0x40, 0xbf, 0xf4, 0x8c, 0x69, 0x5d, 0x5d, 0x79, 0x49, 0x6c, 0xa7, 0x39, 0xe1,
	0x00, 0xb9, 0x20, 0xac, 0x53, 0x6b, 0x09, 0x97, 0x1e, 0x6c, 0x2d, 0xe1, 0xf2, 0x2b, 0x2b, 0x60,
	0x37, 0x70, 0xa5, 0x66, 0x3c, 0xf4, 0x6e, 0xa5, 0xbe, 0x79, 0xfe, 0xb6, 0xf7, 0xf7, 0xc4, 0xec,
	0xc6, 0x8b, 0xfd, 0x84, 0xbc, 0xea, 0x98, 0x5f, 0xe0, 0xbd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x8a, 0xb0, 0x1f, 0xf0, 0x26, 0x05, 0x00, 0x00,
}

// Generated by go-rest-client
type FilesService struct {
	client  *http.Client
	baseUrl string
}

func NewFilesService(client *http.Client, baseUrl string) *FilesService {
	return &FilesService{
		client:  client,
		baseUrl: baseUrl,
	}
}
func (s *FilesService) UploadIcon(in *Files_UploadIconRequest) (*Files_UploadIconResponse, *http.Response, error) {
	var b bytes.Buffer
	w := multipart.NewWriter(&b)
	file := *in.File
	writerFile, err := w.CreateFormFile("File", file.Name())
	if err != nil {
		return nil, nil, err
	}
	_, err = io.Copy(writerFile, file)
	if err != nil {
		return nil, nil, err
	}
	w.Close()
	req, err := http.NewRequest("POST", s.baseUrl+"/Files/UploadIcon", &b)
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", w.FormDataContentType())
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Files_UploadIconResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FilesService) UploadMedia(in *Files_UploadMediaRequest) (*Files_UploadMediaResponse, *http.Response, error) {
	var b bytes.Buffer
	w := multipart.NewWriter(&b)
	file := *in.File
	writerFile, err := w.CreateFormFile("File", file.Name())
	if err != nil {
		return nil, nil, err
	}
	_, err = io.Copy(writerFile, file)
	if err != nil {
		return nil, nil, err
	}
	w.Close()
	req, err := http.NewRequest("POST", s.baseUrl+"/Files/UploadMedia", &b)
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", w.FormDataContentType())
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Files_UploadMediaResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FilesService) UploadFile(in *Files_UploadFileRequest) (*Files_UploadFileResponse, *http.Response, error) {
	var b bytes.Buffer
	w := multipart.NewWriter(&b)
	file := *in.File
	writerFile, err := w.CreateFormFile("File", file.Name())
	if err != nil {
		return nil, nil, err
	}
	_, err = io.Copy(writerFile, file)
	if err != nil {
		return nil, nil, err
	}
	w.Close()
	req, err := http.NewRequest("POST", s.baseUrl+"/Files/UploadFile?ConversationId="+strconv.FormatUint(uint64(in.ConversationId), 10), &b)
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", w.FormDataContentType())
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Files_UploadFileResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FilesService) FileDownloadAddress(in *Files_FileDownloadAddressRequest) (*Files_FileDownloadAddressResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("FileKey", strconv.FormatUint(uint64(in.FileKey), 10))
	req, err := http.NewRequest("POST", s.baseUrl+"/Files/FileDownloadAddress", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Files_FileDownloadAddressResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
