// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friendship.proto

package kahla

import (
	json "encoding/json"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
	http "net/http"
	url "net/url"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Friendship_MineResponse struct {
	Code                 int32                            `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Users                []*Friendship_MineResponse_User  `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Groups               []*Friendship_MineResponse_Group `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Friendship_MineResponse) Reset()         { *m = Friendship_MineResponse{} }
func (m *Friendship_MineResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_MineResponse) ProtoMessage()    {}
func (*Friendship_MineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{0}
}

func (m *Friendship_MineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_MineResponse.Unmarshal(m, b)
}
func (m *Friendship_MineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_MineResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_MineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_MineResponse.Merge(m, src)
}
func (m *Friendship_MineResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_MineResponse.Size(m)
}
func (m *Friendship_MineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_MineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_MineResponse proto.InternalMessageInfo

func (m *Friendship_MineResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_MineResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Friendship_MineResponse) GetUsers() []*Friendship_MineResponse_User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Friendship_MineResponse) GetGroups() []*Friendship_MineResponse_Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Friendship_MineResponse_User struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_MineResponse_User) Reset()         { *m = Friendship_MineResponse_User{} }
func (m *Friendship_MineResponse_User) String() string { return proto.CompactTextString(m) }
func (*Friendship_MineResponse_User) ProtoMessage()    {}
func (*Friendship_MineResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{0, 0}
}

func (m *Friendship_MineResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_MineResponse_User.Unmarshal(m, b)
}
func (m *Friendship_MineResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_MineResponse_User.Marshal(b, m, deterministic)
}
func (m *Friendship_MineResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_MineResponse_User.Merge(m, src)
}
func (m *Friendship_MineResponse_User) XXX_Size() int {
	return xxx_messageInfo_Friendship_MineResponse_User.Size(m)
}
func (m *Friendship_MineResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_MineResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_MineResponse_User proto.InternalMessageInfo

func (m *Friendship_MineResponse_User) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Friendship_MineResponse_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Friendship_MineResponse_User) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Friendship_MineResponse_User) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Friendship_MineResponse_Group struct {
	ImageKey               uint32   `protobuf:"varint,1,opt,name=imageKey,proto3" json:"imageKey,omitempty"`
	Name                   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HasPassword            bool     `protobuf:"varint,3,opt,name=hasPassword,proto3" json:"hasPassword,omitempty"`
	OwnerId                string   `protobuf:"bytes,4,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Id                     uint32   `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	HasTimer               bool     `protobuf:"varint,6,opt,name=hasTimer,proto3" json:"hasTimer,omitempty"`
	ConversationCreateTime string   `protobuf:"bytes,7,opt,name=conversationCreateTime,proto3" json:"conversationCreateTime,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Friendship_MineResponse_Group) Reset()         { *m = Friendship_MineResponse_Group{} }
func (m *Friendship_MineResponse_Group) String() string { return proto.CompactTextString(m) }
func (*Friendship_MineResponse_Group) ProtoMessage()    {}
func (*Friendship_MineResponse_Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{0, 1}
}

func (m *Friendship_MineResponse_Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_MineResponse_Group.Unmarshal(m, b)
}
func (m *Friendship_MineResponse_Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_MineResponse_Group.Marshal(b, m, deterministic)
}
func (m *Friendship_MineResponse_Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_MineResponse_Group.Merge(m, src)
}
func (m *Friendship_MineResponse_Group) XXX_Size() int {
	return xxx_messageInfo_Friendship_MineResponse_Group.Size(m)
}
func (m *Friendship_MineResponse_Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_MineResponse_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_MineResponse_Group proto.InternalMessageInfo

func (m *Friendship_MineResponse_Group) GetImageKey() uint32 {
	if m != nil {
		return m.ImageKey
	}
	return 0
}

func (m *Friendship_MineResponse_Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Friendship_MineResponse_Group) GetHasPassword() bool {
	if m != nil {
		return m.HasPassword
	}
	return false
}

func (m *Friendship_MineResponse_Group) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Friendship_MineResponse_Group) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Friendship_MineResponse_Group) GetHasTimer() bool {
	if m != nil {
		return m.HasTimer
	}
	return false
}

func (m *Friendship_MineResponse_Group) GetConversationCreateTime() string {
	if m != nil {
		return m.ConversationCreateTime
	}
	return ""
}

type Friendship_DeleteFriendRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_DeleteFriendRequest) Reset()         { *m = Friendship_DeleteFriendRequest{} }
func (m *Friendship_DeleteFriendRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_DeleteFriendRequest) ProtoMessage()    {}
func (*Friendship_DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{1}
}

func (m *Friendship_DeleteFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_DeleteFriendRequest.Unmarshal(m, b)
}
func (m *Friendship_DeleteFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_DeleteFriendRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_DeleteFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_DeleteFriendRequest.Merge(m, src)
}
func (m *Friendship_DeleteFriendRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_DeleteFriendRequest.Size(m)
}
func (m *Friendship_DeleteFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_DeleteFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_DeleteFriendRequest proto.InternalMessageInfo

func (m *Friendship_DeleteFriendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Friendship_DeleteFriendResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_DeleteFriendResponse) Reset()         { *m = Friendship_DeleteFriendResponse{} }
func (m *Friendship_DeleteFriendResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_DeleteFriendResponse) ProtoMessage()    {}
func (*Friendship_DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{2}
}

func (m *Friendship_DeleteFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_DeleteFriendResponse.Unmarshal(m, b)
}
func (m *Friendship_DeleteFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_DeleteFriendResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_DeleteFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_DeleteFriendResponse.Merge(m, src)
}
func (m *Friendship_DeleteFriendResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_DeleteFriendResponse.Size(m)
}
func (m *Friendship_DeleteFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_DeleteFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_DeleteFriendResponse proto.InternalMessageInfo

func (m *Friendship_DeleteFriendResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_DeleteFriendResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Friendship_CreateRequestRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_CreateRequestRequest) Reset()         { *m = Friendship_CreateRequestRequest{} }
func (m *Friendship_CreateRequestRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_CreateRequestRequest) ProtoMessage()    {}
func (*Friendship_CreateRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{3}
}

func (m *Friendship_CreateRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_CreateRequestRequest.Unmarshal(m, b)
}
func (m *Friendship_CreateRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_CreateRequestRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_CreateRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_CreateRequestRequest.Merge(m, src)
}
func (m *Friendship_CreateRequestRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_CreateRequestRequest.Size(m)
}
func (m *Friendship_CreateRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_CreateRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_CreateRequestRequest proto.InternalMessageInfo

func (m *Friendship_CreateRequestRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Friendship_CreateRequestResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                uint32   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_CreateRequestResponse) Reset()         { *m = Friendship_CreateRequestResponse{} }
func (m *Friendship_CreateRequestResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_CreateRequestResponse) ProtoMessage()    {}
func (*Friendship_CreateRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{4}
}

func (m *Friendship_CreateRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_CreateRequestResponse.Unmarshal(m, b)
}
func (m *Friendship_CreateRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_CreateRequestResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_CreateRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_CreateRequestResponse.Merge(m, src)
}
func (m *Friendship_CreateRequestResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_CreateRequestResponse.Size(m)
}
func (m *Friendship_CreateRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_CreateRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_CreateRequestResponse proto.InternalMessageInfo

func (m *Friendship_CreateRequestResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_CreateRequestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Friendship_CreateRequestResponse) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Friendship_CompleteRequestRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Accept               bool     `protobuf:"varint,2,opt,name=Accept,proto3" json:"Accept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_CompleteRequestRequest) Reset()         { *m = Friendship_CompleteRequestRequest{} }
func (m *Friendship_CompleteRequestRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_CompleteRequestRequest) ProtoMessage()    {}
func (*Friendship_CompleteRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{5}
}

func (m *Friendship_CompleteRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_CompleteRequestRequest.Unmarshal(m, b)
}
func (m *Friendship_CompleteRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_CompleteRequestRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_CompleteRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_CompleteRequestRequest.Merge(m, src)
}
func (m *Friendship_CompleteRequestRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_CompleteRequestRequest.Size(m)
}
func (m *Friendship_CompleteRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_CompleteRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_CompleteRequestRequest proto.InternalMessageInfo

func (m *Friendship_CompleteRequestRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_CompleteRequestRequest) GetAccept() bool {
	if m != nil {
		return m.Accept
	}
	return false
}

type Friendship_CompleteRequestResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_CompleteRequestResponse) Reset()         { *m = Friendship_CompleteRequestResponse{} }
func (m *Friendship_CompleteRequestResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_CompleteRequestResponse) ProtoMessage()    {}
func (*Friendship_CompleteRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{6}
}

func (m *Friendship_CompleteRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_CompleteRequestResponse.Unmarshal(m, b)
}
func (m *Friendship_CompleteRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_CompleteRequestResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_CompleteRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_CompleteRequestResponse.Merge(m, src)
}
func (m *Friendship_CompleteRequestResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_CompleteRequestResponse.Size(m)
}
func (m *Friendship_CompleteRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_CompleteRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_CompleteRequestResponse proto.InternalMessageInfo

func (m *Friendship_CompleteRequestResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_CompleteRequestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Friendship_MyRequestsResponse struct {
	Code                 int32                                 `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items                []*Friendship_MyRequestsResponse_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Friendship_MyRequestsResponse) Reset()         { *m = Friendship_MyRequestsResponse{} }
func (m *Friendship_MyRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_MyRequestsResponse) ProtoMessage()    {}
func (*Friendship_MyRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{7}
}

func (m *Friendship_MyRequestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_MyRequestsResponse.Unmarshal(m, b)
}
func (m *Friendship_MyRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_MyRequestsResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_MyRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_MyRequestsResponse.Merge(m, src)
}
func (m *Friendship_MyRequestsResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_MyRequestsResponse.Size(m)
}
func (m *Friendship_MyRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_MyRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_MyRequestsResponse proto.InternalMessageInfo

func (m *Friendship_MyRequestsResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_MyRequestsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Friendship_MyRequestsResponse) GetItems() []*Friendship_MyRequestsResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Friendship_MyRequestsResponse_Item struct {
	Id                   uint32                                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId            string                                      `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Creator              *Friendship_MyRequestsResponse_Item_Creator `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	TargetId             string                                      `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	CreateTime           string                                      `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Completed            bool                                        `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Friendship_MyRequestsResponse_Item) Reset()         { *m = Friendship_MyRequestsResponse_Item{} }
func (m *Friendship_MyRequestsResponse_Item) String() string { return proto.CompactTextString(m) }
func (*Friendship_MyRequestsResponse_Item) ProtoMessage()    {}
func (*Friendship_MyRequestsResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{7, 0}
}

func (m *Friendship_MyRequestsResponse_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_MyRequestsResponse_Item.Unmarshal(m, b)
}
func (m *Friendship_MyRequestsResponse_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_MyRequestsResponse_Item.Marshal(b, m, deterministic)
}
func (m *Friendship_MyRequestsResponse_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_MyRequestsResponse_Item.Merge(m, src)
}
func (m *Friendship_MyRequestsResponse_Item) XXX_Size() int {
	return xxx_messageInfo_Friendship_MyRequestsResponse_Item.Size(m)
}
func (m *Friendship_MyRequestsResponse_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_MyRequestsResponse_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_MyRequestsResponse_Item proto.InternalMessageInfo

func (m *Friendship_MyRequestsResponse_Item) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Friendship_MyRequestsResponse_Item) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item) GetCreator() *Friendship_MyRequestsResponse_Item_Creator {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Friendship_MyRequestsResponse_Item) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type Friendship_MyRequestsResponse_Item_Creator struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_MyRequestsResponse_Item_Creator) Reset() {
	*m = Friendship_MyRequestsResponse_Item_Creator{}
}
func (m *Friendship_MyRequestsResponse_Item_Creator) String() string {
	return proto.CompactTextString(m)
}
func (*Friendship_MyRequestsResponse_Item_Creator) ProtoMessage() {}
func (*Friendship_MyRequestsResponse_Item_Creator) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{7, 0, 0}
}

func (m *Friendship_MyRequestsResponse_Item_Creator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_MyRequestsResponse_Item_Creator.Unmarshal(m, b)
}
func (m *Friendship_MyRequestsResponse_Item_Creator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_MyRequestsResponse_Item_Creator.Marshal(b, m, deterministic)
}
func (m *Friendship_MyRequestsResponse_Item_Creator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_MyRequestsResponse_Item_Creator.Merge(m, src)
}
func (m *Friendship_MyRequestsResponse_Item_Creator) XXX_Size() int {
	return xxx_messageInfo_Friendship_MyRequestsResponse_Item_Creator.Size(m)
}
func (m *Friendship_MyRequestsResponse_Item_Creator) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_MyRequestsResponse_Item_Creator.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_MyRequestsResponse_Item_Creator proto.InternalMessageInfo

func (m *Friendship_MyRequestsResponse_Item_Creator) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Friendship_MyRequestsResponse_Item_Creator) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Friendship_SearchEverythingRequest struct {
	SearchInput          string   `protobuf:"bytes,1,opt,name=SearchInput,proto3" json:"SearchInput,omitempty"`
	Take                 uint32   `protobuf:"varint,2,opt,name=Take,proto3" json:"Take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_SearchEverythingRequest) Reset()         { *m = Friendship_SearchEverythingRequest{} }
func (m *Friendship_SearchEverythingRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_SearchEverythingRequest) ProtoMessage()    {}
func (*Friendship_SearchEverythingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{8}
}

func (m *Friendship_SearchEverythingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_SearchEverythingRequest.Unmarshal(m, b)
}
func (m *Friendship_SearchEverythingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_SearchEverythingRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_SearchEverythingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_SearchEverythingRequest.Merge(m, src)
}
func (m *Friendship_SearchEverythingRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_SearchEverythingRequest.Size(m)
}
func (m *Friendship_SearchEverythingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_SearchEverythingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_SearchEverythingRequest proto.InternalMessageInfo

func (m *Friendship_SearchEverythingRequest) GetSearchInput() string {
	if m != nil {
		return m.SearchInput
	}
	return ""
}

func (m *Friendship_SearchEverythingRequest) GetTake() uint32 {
	if m != nil {
		return m.Take
	}
	return 0
}

type Friendship_SearchEverythingResponse struct {
	Code                 int32                                        `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UsersCount           uint32                                       `protobuf:"varint,3,opt,name=usersCount,proto3" json:"usersCount,omitempty"`
	GroupsCount          uint32                                       `protobuf:"varint,4,opt,name=groupsCount,proto3" json:"groupsCount,omitempty"`
	Users                []*Friendship_SearchEverythingResponse_User  `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	Groups               []*Friendship_SearchEverythingResponse_Group `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *Friendship_SearchEverythingResponse) Reset()         { *m = Friendship_SearchEverythingResponse{} }
func (m *Friendship_SearchEverythingResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_SearchEverythingResponse) ProtoMessage()    {}
func (*Friendship_SearchEverythingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{9}
}

func (m *Friendship_SearchEverythingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_SearchEverythingResponse.Unmarshal(m, b)
}
func (m *Friendship_SearchEverythingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_SearchEverythingResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_SearchEverythingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_SearchEverythingResponse.Merge(m, src)
}
func (m *Friendship_SearchEverythingResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_SearchEverythingResponse.Size(m)
}
func (m *Friendship_SearchEverythingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_SearchEverythingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_SearchEverythingResponse proto.InternalMessageInfo

func (m *Friendship_SearchEverythingResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_SearchEverythingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse) GetUsersCount() uint32 {
	if m != nil {
		return m.UsersCount
	}
	return 0
}

func (m *Friendship_SearchEverythingResponse) GetGroupsCount() uint32 {
	if m != nil {
		return m.GroupsCount
	}
	return 0
}

func (m *Friendship_SearchEverythingResponse) GetUsers() []*Friendship_SearchEverythingResponse_User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Friendship_SearchEverythingResponse) GetGroups() []*Friendship_SearchEverythingResponse_Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Friendship_SearchEverythingResponse_User struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_SearchEverythingResponse_User) Reset() {
	*m = Friendship_SearchEverythingResponse_User{}
}
func (m *Friendship_SearchEverythingResponse_User) String() string { return proto.CompactTextString(m) }
func (*Friendship_SearchEverythingResponse_User) ProtoMessage()    {}
func (*Friendship_SearchEverythingResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{9, 0}
}

func (m *Friendship_SearchEverythingResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_SearchEverythingResponse_User.Unmarshal(m, b)
}
func (m *Friendship_SearchEverythingResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_SearchEverythingResponse_User.Marshal(b, m, deterministic)
}
func (m *Friendship_SearchEverythingResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_SearchEverythingResponse_User.Merge(m, src)
}
func (m *Friendship_SearchEverythingResponse_User) XXX_Size() int {
	return xxx_messageInfo_Friendship_SearchEverythingResponse_User.Size(m)
}
func (m *Friendship_SearchEverythingResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_SearchEverythingResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_SearchEverythingResponse_User proto.InternalMessageInfo

func (m *Friendship_SearchEverythingResponse_User) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Friendship_SearchEverythingResponse_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Friendship_SearchEverythingResponse_User) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_User) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Friendship_SearchEverythingResponse_Group struct {
	ImageKey               uint32   `protobuf:"varint,1,opt,name=imageKey,proto3" json:"imageKey,omitempty"`
	Name                   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HasPassword            bool     `protobuf:"varint,3,opt,name=hasPassword,proto3" json:"hasPassword,omitempty"`
	OwnerId                string   `protobuf:"bytes,4,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Id                     uint32   `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	HasTimer               bool     `protobuf:"varint,6,opt,name=hasTimer,proto3" json:"hasTimer,omitempty"`
	ConversationCreateTime string   `protobuf:"bytes,7,opt,name=conversationCreateTime,proto3" json:"conversationCreateTime,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Friendship_SearchEverythingResponse_Group) Reset() {
	*m = Friendship_SearchEverythingResponse_Group{}
}
func (m *Friendship_SearchEverythingResponse_Group) String() string { return proto.CompactTextString(m) }
func (*Friendship_SearchEverythingResponse_Group) ProtoMessage()    {}
func (*Friendship_SearchEverythingResponse_Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{9, 1}
}

func (m *Friendship_SearchEverythingResponse_Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_SearchEverythingResponse_Group.Unmarshal(m, b)
}
func (m *Friendship_SearchEverythingResponse_Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_SearchEverythingResponse_Group.Marshal(b, m, deterministic)
}
func (m *Friendship_SearchEverythingResponse_Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_SearchEverythingResponse_Group.Merge(m, src)
}
func (m *Friendship_SearchEverythingResponse_Group) XXX_Size() int {
	return xxx_messageInfo_Friendship_SearchEverythingResponse_Group.Size(m)
}
func (m *Friendship_SearchEverythingResponse_Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_SearchEverythingResponse_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_SearchEverythingResponse_Group proto.InternalMessageInfo

func (m *Friendship_SearchEverythingResponse_Group) GetImageKey() uint32 {
	if m != nil {
		return m.ImageKey
	}
	return 0
}

func (m *Friendship_SearchEverythingResponse_Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_Group) GetHasPassword() bool {
	if m != nil {
		return m.HasPassword
	}
	return false
}

func (m *Friendship_SearchEverythingResponse_Group) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Friendship_SearchEverythingResponse_Group) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Friendship_SearchEverythingResponse_Group) GetHasTimer() bool {
	if m != nil {
		return m.HasTimer
	}
	return false
}

func (m *Friendship_SearchEverythingResponse_Group) GetConversationCreateTime() string {
	if m != nil {
		return m.ConversationCreateTime
	}
	return ""
}

type Friendship_DiscoverFriendsRequest struct {
	Take                 uint32   `protobuf:"varint,1,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_DiscoverFriendsRequest) Reset()         { *m = Friendship_DiscoverFriendsRequest{} }
func (m *Friendship_DiscoverFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_DiscoverFriendsRequest) ProtoMessage()    {}
func (*Friendship_DiscoverFriendsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{10}
}

func (m *Friendship_DiscoverFriendsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_DiscoverFriendsRequest.Unmarshal(m, b)
}
func (m *Friendship_DiscoverFriendsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_DiscoverFriendsRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_DiscoverFriendsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_DiscoverFriendsRequest.Merge(m, src)
}
func (m *Friendship_DiscoverFriendsRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_DiscoverFriendsRequest.Size(m)
}
func (m *Friendship_DiscoverFriendsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_DiscoverFriendsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_DiscoverFriendsRequest proto.InternalMessageInfo

func (m *Friendship_DiscoverFriendsRequest) GetTake() uint32 {
	if m != nil {
		return m.Take
	}
	return 0
}

type Friendship_DiscoverFriendsResponse struct {
	Code                 int32                                      `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items                []*Friendship_DiscoverFriendsResponse_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Friendship_DiscoverFriendsResponse) Reset()         { *m = Friendship_DiscoverFriendsResponse{} }
func (m *Friendship_DiscoverFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_DiscoverFriendsResponse) ProtoMessage()    {}
func (*Friendship_DiscoverFriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{11}
}

func (m *Friendship_DiscoverFriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse.Unmarshal(m, b)
}
func (m *Friendship_DiscoverFriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_DiscoverFriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_DiscoverFriendsResponse.Merge(m, src)
}
func (m *Friendship_DiscoverFriendsResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse.Size(m)
}
func (m *Friendship_DiscoverFriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_DiscoverFriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_DiscoverFriendsResponse proto.InternalMessageInfo

func (m *Friendship_DiscoverFriendsResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_DiscoverFriendsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse) GetItems() []*Friendship_DiscoverFriendsResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Friendship_DiscoverFriendsResponse_Item struct {
	CommonFriends        uint32                                              `protobuf:"varint,1,opt,name=commonFriends,proto3" json:"commonFriends,omitempty"`
	CommonGroups         uint32                                              `protobuf:"varint,2,opt,name=commonGroups,proto3" json:"commonGroups,omitempty"`
	SentRequest          bool                                                `protobuf:"varint,3,opt,name=sentRequest,proto3" json:"sentRequest,omitempty"`
	TargetUser           *Friendship_DiscoverFriendsResponse_Item_TargetUser `protobuf:"bytes,4,opt,name=targetUser,proto3" json:"targetUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *Friendship_DiscoverFriendsResponse_Item) Reset() {
	*m = Friendship_DiscoverFriendsResponse_Item{}
}
func (m *Friendship_DiscoverFriendsResponse_Item) String() string { return proto.CompactTextString(m) }
func (*Friendship_DiscoverFriendsResponse_Item) ProtoMessage()    {}
func (*Friendship_DiscoverFriendsResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{11, 0}
}

func (m *Friendship_DiscoverFriendsResponse_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item.Unmarshal(m, b)
}
func (m *Friendship_DiscoverFriendsResponse_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item.Marshal(b, m, deterministic)
}
func (m *Friendship_DiscoverFriendsResponse_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item.Merge(m, src)
}
func (m *Friendship_DiscoverFriendsResponse_Item) XXX_Size() int {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item.Size(m)
}
func (m *Friendship_DiscoverFriendsResponse_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item proto.InternalMessageInfo

func (m *Friendship_DiscoverFriendsResponse_Item) GetCommonFriends() uint32 {
	if m != nil {
		return m.CommonFriends
	}
	return 0
}

func (m *Friendship_DiscoverFriendsResponse_Item) GetCommonGroups() uint32 {
	if m != nil {
		return m.CommonGroups
	}
	return 0
}

func (m *Friendship_DiscoverFriendsResponse_Item) GetSentRequest() bool {
	if m != nil {
		return m.SentRequest
	}
	return false
}

func (m *Friendship_DiscoverFriendsResponse_Item) GetTargetUser() *Friendship_DiscoverFriendsResponse_Item_TargetUser {
	if m != nil {
		return m.TargetUser
	}
	return nil
}

type Friendship_DiscoverFriendsResponse_Item_TargetUser struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) Reset() {
	*m = Friendship_DiscoverFriendsResponse_Item_TargetUser{}
}
func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) String() string {
	return proto.CompactTextString(m)
}
func (*Friendship_DiscoverFriendsResponse_Item_TargetUser) ProtoMessage() {}
func (*Friendship_DiscoverFriendsResponse_Item_TargetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{11, 0, 0}
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item_TargetUser.Unmarshal(m, b)
}
func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item_TargetUser.Marshal(b, m, deterministic)
}
func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item_TargetUser.Merge(m, src)
}
func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) XXX_Size() int {
	return xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item_TargetUser.Size(m)
}
func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item_TargetUser.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_DiscoverFriendsResponse_Item_TargetUser proto.InternalMessageInfo

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Friendship_DiscoverFriendsResponse_Item_TargetUser) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Friendship_UserDetailRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_UserDetailRequest) Reset()         { *m = Friendship_UserDetailRequest{} }
func (m *Friendship_UserDetailRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_UserDetailRequest) ProtoMessage()    {}
func (*Friendship_UserDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{12}
}

func (m *Friendship_UserDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_UserDetailRequest.Unmarshal(m, b)
}
func (m *Friendship_UserDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_UserDetailRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_UserDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_UserDetailRequest.Merge(m, src)
}
func (m *Friendship_UserDetailRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_UserDetailRequest.Size(m)
}
func (m *Friendship_UserDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_UserDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_UserDetailRequest proto.InternalMessageInfo

func (m *Friendship_UserDetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Friendship_UserDetailResponse struct {
	Code                 int32                                         `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User                 *Friendship_UserDetailResponse_User           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	AreFriends           bool                                          `protobuf:"varint,4,opt,name=areFriends,proto3" json:"areFriends,omitempty"`
	SentRequest          bool                                          `protobuf:"varint,5,opt,name=sentRequest,proto3" json:"sentRequest,omitempty"`
	PendingRequest       *Friendship_UserDetailResponse_PendingRequest `protobuf:"bytes,6,opt,name=pendingRequest,proto3" json:"pendingRequest,omitempty"`
	ConversationId       uint32                                        `protobuf:"varint,7,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *Friendship_UserDetailResponse) Reset()         { *m = Friendship_UserDetailResponse{} }
func (m *Friendship_UserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_UserDetailResponse) ProtoMessage()    {}
func (*Friendship_UserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{13}
}

func (m *Friendship_UserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_UserDetailResponse.Unmarshal(m, b)
}
func (m *Friendship_UserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_UserDetailResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_UserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_UserDetailResponse.Merge(m, src)
}
func (m *Friendship_UserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_UserDetailResponse.Size(m)
}
func (m *Friendship_UserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_UserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_UserDetailResponse proto.InternalMessageInfo

func (m *Friendship_UserDetailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_UserDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Friendship_UserDetailResponse) GetUser() *Friendship_UserDetailResponse_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Friendship_UserDetailResponse) GetAreFriends() bool {
	if m != nil {
		return m.AreFriends
	}
	return false
}

func (m *Friendship_UserDetailResponse) GetSentRequest() bool {
	if m != nil {
		return m.SentRequest
	}
	return false
}

func (m *Friendship_UserDetailResponse) GetPendingRequest() *Friendship_UserDetailResponse_PendingRequest {
	if m != nil {
		return m.PendingRequest
	}
	return nil
}

func (m *Friendship_UserDetailResponse) GetConversationId() uint32 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type Friendship_UserDetailResponse_User struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_UserDetailResponse_User) Reset()         { *m = Friendship_UserDetailResponse_User{} }
func (m *Friendship_UserDetailResponse_User) String() string { return proto.CompactTextString(m) }
func (*Friendship_UserDetailResponse_User) ProtoMessage()    {}
func (*Friendship_UserDetailResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{13, 0}
}

func (m *Friendship_UserDetailResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_UserDetailResponse_User.Unmarshal(m, b)
}
func (m *Friendship_UserDetailResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_UserDetailResponse_User.Marshal(b, m, deterministic)
}
func (m *Friendship_UserDetailResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_UserDetailResponse_User.Merge(m, src)
}
func (m *Friendship_UserDetailResponse_User) XXX_Size() int {
	return xxx_messageInfo_Friendship_UserDetailResponse_User.Size(m)
}
func (m *Friendship_UserDetailResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_UserDetailResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_UserDetailResponse_User proto.InternalMessageInfo

func (m *Friendship_UserDetailResponse_User) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Friendship_UserDetailResponse_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Friendship_UserDetailResponse_User) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Friendship_UserDetailResponse_User) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Friendship_UserDetailResponse_PendingRequest struct {
	Id                   uint32                                                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId            string                                                `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Creator              *Friendship_UserDetailResponse_PendingRequest_Creator `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	TargetId             string                                                `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	CreateTime           string                                                `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Completed            bool                                                  `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *Friendship_UserDetailResponse_PendingRequest) Reset() {
	*m = Friendship_UserDetailResponse_PendingRequest{}
}
func (m *Friendship_UserDetailResponse_PendingRequest) String() string {
	return proto.CompactTextString(m)
}
func (*Friendship_UserDetailResponse_PendingRequest) ProtoMessage() {}
func (*Friendship_UserDetailResponse_PendingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{13, 1}
}

func (m *Friendship_UserDetailResponse_PendingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest.Unmarshal(m, b)
}
func (m *Friendship_UserDetailResponse_PendingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_UserDetailResponse_PendingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest.Merge(m, src)
}
func (m *Friendship_UserDetailResponse_PendingRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest.Size(m)
}
func (m *Friendship_UserDetailResponse_PendingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest proto.InternalMessageInfo

func (m *Friendship_UserDetailResponse_PendingRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Friendship_UserDetailResponse_PendingRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest) GetCreator() *Friendship_UserDetailResponse_PendingRequest_Creator {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Friendship_UserDetailResponse_PendingRequest) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type Friendship_UserDetailResponse_PendingRequest_Creator struct {
	MakeEmailPublic      bool     `protobuf:"varint,1,opt,name=makeEmailPublic,proto3" json:"makeEmailPublic,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  string   `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgFileKey       uint32   `protobuf:"varint,7,opt,name=headImgFileKey,proto3" json:"headImgFileKey,omitempty"`
	PreferedLanguage     string   `protobuf:"bytes,8,opt,name=preferedLanguage,proto3" json:"preferedLanguage,omitempty"`
	AccountCreateTime    string   `protobuf:"bytes,9,opt,name=accountCreateTime,proto3" json:"accountCreateTime,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,10,opt,name=emailConfirmed,proto3" json:"emailConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) Reset() {
	*m = Friendship_UserDetailResponse_PendingRequest_Creator{}
}
func (m *Friendship_UserDetailResponse_PendingRequest_Creator) String() string {
	return proto.CompactTextString(m)
}
func (*Friendship_UserDetailResponse_PendingRequest_Creator) ProtoMessage() {}
func (*Friendship_UserDetailResponse_PendingRequest_Creator) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{13, 1, 0}
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest_Creator.Unmarshal(m, b)
}
func (m *Friendship_UserDetailResponse_PendingRequest_Creator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest_Creator.Marshal(b, m, deterministic)
}
func (m *Friendship_UserDetailResponse_PendingRequest_Creator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest_Creator.Merge(m, src)
}
func (m *Friendship_UserDetailResponse_PendingRequest_Creator) XXX_Size() int {
	return xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest_Creator.Size(m)
}
func (m *Friendship_UserDetailResponse_PendingRequest_Creator) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest_Creator.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_UserDetailResponse_PendingRequest_Creator proto.InternalMessageInfo

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetMakeEmailPublic() bool {
	if m != nil {
		return m.MakeEmailPublic
	}
	return false
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetHeadImgFileKey() uint32 {
	if m != nil {
		return m.HeadImgFileKey
	}
	return 0
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetPreferedLanguage() string {
	if m != nil {
		return m.PreferedLanguage
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetAccountCreateTime() string {
	if m != nil {
		return m.AccountCreateTime
	}
	return ""
}

func (m *Friendship_UserDetailResponse_PendingRequest_Creator) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

type Friendship_ReportHimRequest struct {
	TargetUserId         string   `protobuf:"bytes,1,opt,name=TargetUserId,proto3" json:"TargetUserId,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_ReportHimRequest) Reset()         { *m = Friendship_ReportHimRequest{} }
func (m *Friendship_ReportHimRequest) String() string { return proto.CompactTextString(m) }
func (*Friendship_ReportHimRequest) ProtoMessage()    {}
func (*Friendship_ReportHimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{14}
}

func (m *Friendship_ReportHimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_ReportHimRequest.Unmarshal(m, b)
}
func (m *Friendship_ReportHimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_ReportHimRequest.Marshal(b, m, deterministic)
}
func (m *Friendship_ReportHimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_ReportHimRequest.Merge(m, src)
}
func (m *Friendship_ReportHimRequest) XXX_Size() int {
	return xxx_messageInfo_Friendship_ReportHimRequest.Size(m)
}
func (m *Friendship_ReportHimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_ReportHimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_ReportHimRequest proto.InternalMessageInfo

func (m *Friendship_ReportHimRequest) GetTargetUserId() string {
	if m != nil {
		return m.TargetUserId
	}
	return ""
}

func (m *Friendship_ReportHimRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Friendship_ReportHimResponse struct {
	Code                 int32    `protobuf:"zigzag32,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friendship_ReportHimResponse) Reset()         { *m = Friendship_ReportHimResponse{} }
func (m *Friendship_ReportHimResponse) String() string { return proto.CompactTextString(m) }
func (*Friendship_ReportHimResponse) ProtoMessage()    {}
func (*Friendship_ReportHimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4164b89dcff7420, []int{15}
}

func (m *Friendship_ReportHimResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friendship_ReportHimResponse.Unmarshal(m, b)
}
func (m *Friendship_ReportHimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friendship_ReportHimResponse.Marshal(b, m, deterministic)
}
func (m *Friendship_ReportHimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friendship_ReportHimResponse.Merge(m, src)
}
func (m *Friendship_ReportHimResponse) XXX_Size() int {
	return xxx_messageInfo_Friendship_ReportHimResponse.Size(m)
}
func (m *Friendship_ReportHimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Friendship_ReportHimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Friendship_ReportHimResponse proto.InternalMessageInfo

func (m *Friendship_ReportHimResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Friendship_ReportHimResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Friendship_MineResponse)(nil), "kahla.Friendship_MineResponse")
	proto.RegisterType((*Friendship_MineResponse_User)(nil), "kahla.Friendship_MineResponse.User")
	proto.RegisterType((*Friendship_MineResponse_Group)(nil), "kahla.Friendship_MineResponse.Group")
	proto.RegisterType((*Friendship_DeleteFriendRequest)(nil), "kahla.Friendship_DeleteFriendRequest")
	proto.RegisterType((*Friendship_DeleteFriendResponse)(nil), "kahla.Friendship_DeleteFriendResponse")
	proto.RegisterType((*Friendship_CreateRequestRequest)(nil), "kahla.Friendship_CreateRequestRequest")
	proto.RegisterType((*Friendship_CreateRequestResponse)(nil), "kahla.Friendship_CreateRequestResponse")
	proto.RegisterType((*Friendship_CompleteRequestRequest)(nil), "kahla.Friendship_CompleteRequestRequest")
	proto.RegisterType((*Friendship_CompleteRequestResponse)(nil), "kahla.Friendship_CompleteRequestResponse")
	proto.RegisterType((*Friendship_MyRequestsResponse)(nil), "kahla.Friendship_MyRequestsResponse")
	proto.RegisterType((*Friendship_MyRequestsResponse_Item)(nil), "kahla.Friendship_MyRequestsResponse.Item")
	proto.RegisterType((*Friendship_MyRequestsResponse_Item_Creator)(nil), "kahla.Friendship_MyRequestsResponse.Item.Creator")
	proto.RegisterType((*Friendship_SearchEverythingRequest)(nil), "kahla.Friendship_SearchEverythingRequest")
	proto.RegisterType((*Friendship_SearchEverythingResponse)(nil), "kahla.Friendship_SearchEverythingResponse")
	proto.RegisterType((*Friendship_SearchEverythingResponse_User)(nil), "kahla.Friendship_SearchEverythingResponse.User")
	proto.RegisterType((*Friendship_SearchEverythingResponse_Group)(nil), "kahla.Friendship_SearchEverythingResponse.Group")
	proto.RegisterType((*Friendship_DiscoverFriendsRequest)(nil), "kahla.Friendship_DiscoverFriendsRequest")
	proto.RegisterType((*Friendship_DiscoverFriendsResponse)(nil), "kahla.Friendship_DiscoverFriendsResponse")
	proto.RegisterType((*Friendship_DiscoverFriendsResponse_Item)(nil), "kahla.Friendship_DiscoverFriendsResponse.Item")
	proto.RegisterType((*Friendship_DiscoverFriendsResponse_Item_TargetUser)(nil), "kahla.Friendship_DiscoverFriendsResponse.Item.TargetUser")
	proto.RegisterType((*Friendship_UserDetailRequest)(nil), "kahla.Friendship_UserDetailRequest")
	proto.RegisterType((*Friendship_UserDetailResponse)(nil), "kahla.Friendship_UserDetailResponse")
	proto.RegisterType((*Friendship_UserDetailResponse_User)(nil), "kahla.Friendship_UserDetailResponse.User")
	proto.RegisterType((*Friendship_UserDetailResponse_PendingRequest)(nil), "kahla.Friendship_UserDetailResponse.PendingRequest")
	proto.RegisterType((*Friendship_UserDetailResponse_PendingRequest_Creator)(nil), "kahla.Friendship_UserDetailResponse.PendingRequest.Creator")
	proto.RegisterType((*Friendship_ReportHimRequest)(nil), "kahla.Friendship_ReportHimRequest")
	proto.RegisterType((*Friendship_ReportHimResponse)(nil), "kahla.Friendship_ReportHimResponse")
}

func init() { proto.RegisterFile("friendship.proto", fileDescriptor_d4164b89dcff7420) }

var fileDescriptor_d4164b89dcff7420 = []byte{
	// 1252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x5f, 0x6f, 0xdb, 0x54,
	0x14, 0x57, 0x52, 0x3b, 0x4d, 0x4f, 0xda, 0xae, 0xbb, 0x9a, 0x86, 0xe5, 0x8d, 0x12, 0xdc, 0x32,
	0xd2, 0x09, 0xb9, 0x5b, 0x27, 0x81, 0x26, 0x60, 0x08, 0xb5, 0xdd, 0x16, 0xba, 0x41, 0x65, 0x3a,
	0xa1, 0xc2, 0x03, 0xba, 0xb5, 0x4f, 0x12, 0xab, 0xf1, 0x1f, 0x6c, 0xa7, 0x6b, 0xbf, 0x08, 0xef,
	0x7c, 0x04, 0x90, 0x78, 0x47, 0x9a, 0x84, 0x78, 0xe2, 0x75, 0x4f, 0x7c, 0x17, 0x74, 0xef, 0xb5,
	0x93, 0xeb, 0x38, 0x69, 0x53, 0xf3, 0x84, 0x94, 0x37, 0x9f, 0x9f, 0xef, 0x39, 0xf7, 0xdc, 0xf3,
	0xff, 0x5e, 0x58, 0xeb, 0x44, 0x2e, 0xfa, 0x4e, 0xdc, 0x73, 0x43, 0x33, 0x8c, 0x82, 0x24, 0x20,
	0xea, 0x29, 0xed, 0xf5, 0xa9, 0xbe, 0x8c, 0xe7, 0x09, 0xfa, 0x8e, 0x00, 0xf5, 0x3b, 0xdd, 0x20,
	0xe8, 0xf6, 0x71, 0x9b, 0x53, 0x27, 0x83, 0xce, 0x36, 0x7a, 0x61, 0x72, 0x21, 0x7e, 0x1a, 0xff,
	0xa8, 0xf0, 0xce, 0xd3, 0xa1, 0x98, 0x1f, 0x5f, 0xba, 0x3e, 0x5a, 0x18, 0x87, 0x81, 0x1f, 0x23,
	0x21, 0xa0, 0xd8, 0x81, 0x83, 0x5a, 0xa5, 0x59, 0x69, 0xdd, 0xb4, 0xf8, 0x37, 0xd1, 0x60, 0xd1,
	0xc3, 0x38, 0xa6, 0x5d, 0xd4, 0xaa, 0xcd, 0x4a, 0x6b, 0xc9, 0xca, 0x48, 0xf2, 0x18, 0xd4, 0x41,
	0x8c, 0x51, 0xac, 0x2d, 0x34, 0x17, 0x5a, 0x8d, 0x9d, 0x0d, 0x93, 0xeb, 0x62, 0x4e, 0x11, 0x6e,
	0xbe, 0x8a, 0x31, 0xb2, 0x04, 0x07, 0xf9, 0x0c, 0x6a, 0xdd, 0x28, 0x18, 0x84, 0xb1, 0xa6, 0x70,
	0xde, 0xcd, 0x2b, 0x78, 0x9f, 0xb1, 0xc5, 0x56, 0xca, 0xa3, 0xff, 0x51, 0x05, 0x85, 0x49, 0x23,
	0x2d, 0xb8, 0xe1, 0xd1, 0x53, 0xdc, 0xf7, 0xa8, 0xdb, 0x3f, 0x1c, 0x9c, 0xf4, 0x5d, 0x9b, 0xab,
	0x5e, 0xb7, 0xc6, 0x61, 0x72, 0x0b, 0x54, 0x64, 0x64, 0x7a, 0x06, 0x41, 0x90, 0x55, 0xa8, 0xba,
	0x8e, 0xb6, 0xc0, 0xa1, 0xaa, 0xeb, 0x90, 0x35, 0x58, 0x38, 0x71, 0x03, 0x4d, 0xe1, 0x00, 0xfb,
	0x24, 0x3a, 0xd4, 0x7d, 0xd7, 0x3e, 0xfd, 0x9a, 0x7a, 0xa8, 0xa9, 0x1c, 0x1e, 0xd2, 0x6c, 0x75,
	0x8c, 0xe7, 0x5a, 0x4d, 0xac, 0x8e, 0xf1, 0x9c, 0xdc, 0x83, 0xd5, 0x1e, 0x52, 0xa7, 0xed, 0x75,
	0x9f, 0xba, 0x7d, 0x3c, 0xc0, 0x0b, 0x6d, 0xb1, 0x59, 0x69, 0xad, 0x58, 0x63, 0x28, 0xb9, 0x0f,
	0x6b, 0x61, 0x84, 0x1d, 0x8c, 0xd0, 0x79, 0x41, 0xfd, 0xee, 0x80, 0x19, 0xb7, 0xce, 0xc5, 0x14,
	0x70, 0xf2, 0x11, 0xdc, 0xa4, 0xb6, 0x1d, 0x0c, 0xfc, 0x64, 0x37, 0x42, 0x9a, 0xe0, 0x91, 0xeb,
	0xa1, 0xb6, 0xc4, 0x17, 0x17, 0x7f, 0x30, 0x0d, 0xf8, 0xd1, 0x76, 0x03, 0xbf, 0xe3, 0x46, 0x1e,
	0x3a, 0x1a, 0x70, 0x83, 0x8c, 0xa1, 0xfa, 0xdb, 0x0a, 0xa8, 0xdc, 0xa8, 0xec, 0x84, 0xae, 0x47,
	0xbb, 0x5c, 0xdb, 0x0a, 0xd7, 0x76, 0x48, 0xb3, 0x78, 0xf0, 0xd9, 0xc9, 0x85, 0xd1, 0xf8, 0x37,
	0x69, 0x42, 0xa3, 0x47, 0xe3, 0x43, 0x1a, 0xc7, 0xaf, 0x83, 0x48, 0x18, 0xaf, 0x6e, 0xc9, 0x10,
	0x8b, 0x98, 0xe0, 0xb5, 0x8f, 0x51, 0xdb, 0x49, 0x2d, 0x99, 0x91, 0xa9, 0xbd, 0x55, 0xbe, 0x0b,
	0xb3, 0xb7, 0x0e, 0xf5, 0x1e, 0x8d, 0x99, 0xe2, 0x11, 0x37, 0x63, 0xdd, 0x1a, 0xd2, 0xe4, 0x63,
	0xb8, 0x6d, 0x07, 0xfe, 0x19, 0x46, 0x31, 0x4d, 0xdc, 0xc0, 0x97, 0x0e, 0xbf, 0xc8, 0x85, 0x4e,
	0xf9, 0x6b, 0x3c, 0x80, 0x75, 0x29, 0x8a, 0xf6, 0xb0, 0x8f, 0x09, 0x0a, 0xc0, 0xc2, 0x9f, 0x06,
	0x18, 0x27, 0xa9, 0x16, 0x95, 0xcc, 0xeb, 0xc6, 0x37, 0xf0, 0xde, 0x54, 0x8e, 0x32, 0x89, 0x61,
	0x3c, 0xcc, 0x09, 0x14, 0xba, 0xa5, 0x9b, 0x4f, 0xd3, 0xa1, 0x03, 0xcd, 0xe9, 0x2c, 0xa5, 0xb2,
	0xf3, 0x16, 0xa8, 0x67, 0xb4, 0x3f, 0x40, 0xee, 0xa1, 0x15, 0x4b, 0x10, 0xc6, 0x01, 0xbc, 0x2f,
	0xef, 0x13, 0x78, 0x21, 0x3b, 0x6d, 0x51, 0xb9, 0xf6, 0x50, 0xb9, 0xb6, 0x43, 0x6e, 0x43, 0xed,
	0x4b, 0xdb, 0xc6, 0x30, 0xe1, 0x7b, 0xd4, 0xad, 0x94, 0x32, 0x2c, 0x30, 0x2e, 0x13, 0x56, 0xca,
	0x76, 0xbf, 0xa9, 0xf0, 0xae, 0x5c, 0x05, 0x2e, 0x52, 0x71, 0x71, 0x49, 0x33, 0x7c, 0x01, 0xaa,
	0x9b, 0xa0, 0x97, 0x15, 0xa9, 0xad, 0x09, 0x85, 0xa6, 0xb0, 0x85, 0xd9, 0x4e, 0xd0, 0xb3, 0x04,
	0x9f, 0xfe, 0x8b, 0x02, 0x0a, 0xa3, 0x25, 0x97, 0x89, 0xe0, 0xbd, 0x0b, 0x4b, 0x36, 0xf3, 0x53,
	0xc0, 0x02, 0x5d, 0xec, 0x3a, 0x02, 0xc8, 0x01, 0x2c, 0xa6, 0x04, 0x77, 0x40, 0x63, 0xe7, 0xe1,
	0xcc, 0x3b, 0x9b, 0xbb, 0x82, 0xd1, 0xca, 0x24, 0xb0, 0x3c, 0x49, 0x68, 0xd4, 0xc5, 0x64, 0x98,
	0x52, 0x43, 0x9a, 0xac, 0x03, 0xd8, 0xa3, 0xdc, 0x10, 0x35, 0x4a, 0x42, 0xb8, 0x9a, 0xa9, 0x67,
	0x9c, 0x34, 0xc9, 0x46, 0x80, 0xfe, 0xa6, 0x0a, 0x8b, 0xe9, 0x76, 0xf3, 0x6a, 0x5a, 0xb6, 0x9a,
	0x1a, 0xdf, 0xe7, 0x12, 0xe1, 0x5b, 0xa4, 0x91, 0xdd, 0xdb, 0x3f, 0xc3, 0xe8, 0x22, 0xe9, 0xb9,
	0x7e, 0x37, 0x4b, 0xab, 0x26, 0x34, 0xc4, 0xaf, 0xb6, 0x1f, 0x0e, 0x92, 0x34, 0xbf, 0x64, 0x88,
	0x85, 0xf6, 0x11, 0x3d, 0x15, 0x31, 0xbc, 0x62, 0xf1, 0x6f, 0xe3, 0x4d, 0x0d, 0x36, 0x2e, 0x15,
	0x5e, 0x2a, 0x2d, 0xd6, 0x01, 0x78, 0x27, 0xde, 0x65, 0x27, 0x4e, 0x4b, 0x84, 0x84, 0x30, 0x5d,
	0x45, 0xb3, 0x15, 0x0b, 0x14, 0xbe, 0x40, 0x86, 0xc8, 0x7e, 0xd6, 0xfd, 0x55, 0x9e, 0x58, 0xdb,
	0xc5, 0xf0, 0x9e, 0xa6, 0x6a, 0x6e, 0x12, 0x78, 0x3e, 0x9c, 0x04, 0x6a, 0x5c, 0xce, 0x83, 0x6b,
	0xc8, 0x99, 0x4f, 0x05, 0xf3, 0xa9, 0x60, 0xc6, 0xa9, 0xe0, 0x93, 0x5c, 0xdf, 0xdb, 0x73, 0x63,
	0x3b, 0x38, 0xc3, 0x28, 0x85, 0xb2, 0x04, 0x25, 0xa0, 0x24, 0x2c, 0xfd, 0xc4, 0x81, 0xf9, 0xb7,
	0xf1, 0xab, 0x9a, 0xcb, 0xed, 0x02, 0x67, 0xa9, 0xec, 0xdb, 0xcb, 0x37, 0x25, 0xb3, 0x18, 0xf3,
	0x53, 0xf6, 0xc9, 0x75, 0xa6, 0x9f, 0xb3, 0xce, 0xb4, 0x09, 0x2b, 0x76, 0xe0, 0x79, 0x81, 0x9f,
	0xae, 0x4e, 0x0f, 0x90, 0x07, 0x89, 0x01, 0xcb, 0x02, 0x78, 0x26, 0xf2, 0x4d, 0x14, 0x99, 0x1c,
	0xc6, 0xdc, 0x18, 0xa3, 0x9f, 0x0d, 0x02, 0x99, 0x1b, 0x25, 0x88, 0x1c, 0x03, 0x88, 0xd6, 0xc3,
	0x52, 0x8d, 0x7b, 0xb2, 0xb1, 0xf3, 0xf8, 0x7a, 0xfa, 0x9b, 0x47, 0x43, 0x01, 0x96, 0x24, 0x4c,
	0xff, 0xb3, 0x0a, 0x30, 0xfa, 0x35, 0x4f, 0xe3, 0xd2, 0xed, 0xc8, 0x84, 0xbb, 0x92, 0x2b, 0x98,
	0x31, 0xf7, 0x30, 0xa1, 0x6e, 0x7f, 0xda, 0xf0, 0xf9, 0xf7, 0x52, 0x6e, 0xe6, 0x92, 0x19, 0x4a,
	0x85, 0xf7, 0xe7, 0xa0, 0xb0, 0xe2, 0x9e, 0x0e, 0x3e, 0x13, 0x46, 0xae, 0xe2, 0x0e, 0xa2, 0x27,
	0x70, 0x36, 0xd6, 0x9b, 0x68, 0x84, 0x59, 0x2c, 0x2b, 0xfc, 0x88, 0x12, 0x32, 0x1e, 0xa4, 0x6a,
	0x31, 0x48, 0x7f, 0x80, 0xd5, 0x10, 0x7d, 0x67, 0xd4, 0x7b, 0xb9, 0x1f, 0x1b, 0x3b, 0x8f, 0x66,
	0x52, 0xe5, 0x30, 0xc7, 0x6a, 0x8d, 0x89, 0x62, 0x5e, 0x90, 0x8b, 0x4c, 0xdb, 0xc9, 0xe2, 0x20,
	0x8f, 0xce, 0xfb, 0xd1, 0x7f, 0xef, 0x47, 0xbf, 0x2b, 0xb0, 0x9a, 0xf7, 0xc6, 0x35, 0xa7, 0xf0,
	0x57, 0xe3, 0x53, 0xf8, 0xa7, 0x25, 0x22, 0x60, 0x3e, 0x8f, 0xff, 0xdf, 0x0a, 0xe0, 0x31, 0xdc,
	0x91, 0x1c, 0x6c, 0x61, 0x18, 0x44, 0xc9, 0x73, 0xd7, 0xcb, 0x62, 0xc8, 0x80, 0xe5, 0x51, 0x9f,
	0x19, 0xde, 0x74, 0x73, 0x18, 0xbb, 0xf3, 0x5a, 0x48, 0xe3, 0xc0, 0x4f, 0x6d, 0x9a, 0x52, 0xc6,
	0x8b, 0x5c, 0x6d, 0x95, 0x44, 0x97, 0xa9, 0x94, 0x3b, 0x6f, 0x6b, 0x00, 0x23, 0x71, 0xe4, 0x09,
	0x28, 0x2f, 0x5d, 0x1f, 0xc9, 0x6d, 0x53, 0xbc, 0xe0, 0x99, 0xd9, 0x0b, 0x9e, 0xb9, 0xef, 0x85,
	0xc9, 0x85, 0xbe, 0x7e, 0xf9, 0x33, 0x19, 0x39, 0x81, 0x65, 0xf9, 0xf9, 0x82, 0x7c, 0x30, 0xa1,
	0x31, 0x17, 0x1f, 0x44, 0xf4, 0x7b, 0x57, 0x2d, 0x13, 0xe2, 0x8d, 0x85, 0xbf, 0x9e, 0x54, 0x08,
	0xc2, 0x4a, 0xee, 0x79, 0x82, 0x4c, 0xe0, 0x9e, 0xf4, 0xe4, 0xa1, 0x7f, 0x78, 0xe5, 0x3a, 0x79,
	0x9b, 0x53, 0xb8, 0x31, 0xf6, 0xa0, 0x40, 0x5a, 0x13, 0x04, 0x4c, 0x7c, 0xc0, 0xd0, 0xb7, 0x66,
	0x58, 0x29, 0x6f, 0xf6, 0x15, 0xc0, 0xe8, 0x2e, 0x3e, 0xd5, 0xfa, 0x9b, 0xb3, 0xdc, 0xe0, 0x89,
	0x0b, 0x6b, 0xe3, 0x17, 0x16, 0xb2, 0x35, 0xcb, 0xa5, 0x46, 0xa8, 0x7e, 0x7f, 0xf6, 0xfb, 0x0f,
	0xe9, 0xc0, 0x8d, 0xb1, 0x39, 0x6b, 0x92, 0x8d, 0x26, 0x0f, 0xbb, 0x93, 0x6c, 0x34, 0x6d, 0xb8,
	0xfd, 0x0e, 0x60, 0x54, 0x24, 0xc9, 0xc6, 0xe5, 0x25, 0x54, 0x48, 0xdf, 0x9c, 0xa5, 0xce, 0x92,
	0x63, 0x58, 0x1a, 0x66, 0x10, 0x31, 0x8a, 0x2c, 0xe3, 0x99, 0xab, 0x6f, 0x5c, 0xba, 0x46, 0x72,
	0xe9, 0x49, 0x8d, 0x3b, 0xef, 0xd1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0x29, 0x1b, 0x69,
	0x33, 0x17, 0x00, 0x00,
}

// Generated by go-rest-client
type FriendshipService struct {
	client  *http.Client
	baseUrl string
}

func NewFriendshipService(client *http.Client, baseUrl string) *FriendshipService {
	return &FriendshipService{
		client:  client,
		baseUrl: baseUrl,
	}
}
func (s *FriendshipService) Mine() (*Friendship_MineResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Friendship/Mine", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_MineResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) DeleteFriend(in *Friendship_DeleteFriendRequest) (*Friendship_DeleteFriendResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("id", in.Id)
	req, err := http.NewRequest("POST", s.baseUrl+"/Friendship/DeleteFriend", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_DeleteFriendResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) CreateRequest(in *Friendship_CreateRequestRequest) (*Friendship_CreateRequestResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("id", in.Id)
	req, err := http.NewRequest("POST", s.baseUrl+"/Friendship/CreateRequest", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_CreateRequestResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) CompleteRequest(in *Friendship_CompleteRequestRequest) (*Friendship_CompleteRequestResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("Id", in.Id)
	v.Add("Accept", strconv.FormatBool(in.Accept))
	req, err := http.NewRequest("POST", s.baseUrl+"/Friendship/CompleteRequest", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_CompleteRequestResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) MyRequests() (*Friendship_MyRequestsResponse, *http.Response, error) {
	req, err := http.NewRequest("GET", s.baseUrl+"/Friendship/MyRequests", nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_MyRequestsResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) SearchEverything(in *Friendship_SearchEverythingRequest) (*Friendship_SearchEverythingResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("SearchInput", in.SearchInput)
	v.Add("Take", strconv.FormatUint(uint64(in.Take), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Friendship/SearchEverything?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_SearchEverythingResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) DiscoverFriends(in *Friendship_DiscoverFriendsRequest) (*Friendship_DiscoverFriendsResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("take", strconv.FormatUint(uint64(in.Take), 10))
	req, err := http.NewRequest("GET", s.baseUrl+"/Friendship/DiscoverFriends?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_DiscoverFriendsResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) UserDetail(in *Friendship_UserDetailRequest) (*Friendship_UserDetailResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("id", in.Id)
	req, err := http.NewRequest("GET", s.baseUrl+"/Friendship/UserDetail?"+v.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_UserDetailResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *FriendshipService) ReportHim(in *Friendship_ReportHimRequest) (*Friendship_ReportHimResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("TargetUserId", in.TargetUserId)
	v.Add("Reason", in.Reason)
	req, err := http.NewRequest("POST", s.baseUrl+"/Friendship/ReportHim", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Friendship_ReportHimResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
