// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groups.proto

package kahla

import (
	json "encoding/json"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	http "net/http"
	url "net/url"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Groups_CreateGroupConversationRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	JoinPassword         string   `protobuf:"bytes,2,opt,name=JoinPassword,proto3" json:"JoinPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_CreateGroupConversationRequest) Reset()         { *m = Groups_CreateGroupConversationRequest{} }
func (m *Groups_CreateGroupConversationRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_CreateGroupConversationRequest) ProtoMessage()    {}
func (*Groups_CreateGroupConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{0}
}

func (m *Groups_CreateGroupConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_CreateGroupConversationRequest.Unmarshal(m, b)
}
func (m *Groups_CreateGroupConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_CreateGroupConversationRequest.Marshal(b, m, deterministic)
}
func (m *Groups_CreateGroupConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_CreateGroupConversationRequest.Merge(m, src)
}
func (m *Groups_CreateGroupConversationRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_CreateGroupConversationRequest.Size(m)
}
func (m *Groups_CreateGroupConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_CreateGroupConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_CreateGroupConversationRequest proto.InternalMessageInfo

func (m *Groups_CreateGroupConversationRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_CreateGroupConversationRequest) GetJoinPassword() string {
	if m != nil {
		return m.JoinPassword
	}
	return ""
}

type Groups_CreateGroupConversationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_CreateGroupConversationResponse) Reset() {
	*m = Groups_CreateGroupConversationResponse{}
}
func (m *Groups_CreateGroupConversationResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_CreateGroupConversationResponse) ProtoMessage()    {}
func (*Groups_CreateGroupConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{1}
}

func (m *Groups_CreateGroupConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_CreateGroupConversationResponse.Unmarshal(m, b)
}
func (m *Groups_CreateGroupConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_CreateGroupConversationResponse.Marshal(b, m, deterministic)
}
func (m *Groups_CreateGroupConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_CreateGroupConversationResponse.Merge(m, src)
}
func (m *Groups_CreateGroupConversationResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_CreateGroupConversationResponse.Size(m)
}
func (m *Groups_CreateGroupConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_CreateGroupConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_CreateGroupConversationResponse proto.InternalMessageInfo

type Groups_JoinGroupRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	JoinPassword         string   `protobuf:"bytes,2,opt,name=joinPassword,proto3" json:"joinPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_JoinGroupRequest) Reset()         { *m = Groups_JoinGroupRequest{} }
func (m *Groups_JoinGroupRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_JoinGroupRequest) ProtoMessage()    {}
func (*Groups_JoinGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{2}
}

func (m *Groups_JoinGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_JoinGroupRequest.Unmarshal(m, b)
}
func (m *Groups_JoinGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_JoinGroupRequest.Marshal(b, m, deterministic)
}
func (m *Groups_JoinGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_JoinGroupRequest.Merge(m, src)
}
func (m *Groups_JoinGroupRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_JoinGroupRequest.Size(m)
}
func (m *Groups_JoinGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_JoinGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_JoinGroupRequest proto.InternalMessageInfo

func (m *Groups_JoinGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_JoinGroupRequest) GetJoinPassword() string {
	if m != nil {
		return m.JoinPassword
	}
	return ""
}

type Groups_JoinGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_JoinGroupResponse) Reset()         { *m = Groups_JoinGroupResponse{} }
func (m *Groups_JoinGroupResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_JoinGroupResponse) ProtoMessage()    {}
func (*Groups_JoinGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{3}
}

func (m *Groups_JoinGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_JoinGroupResponse.Unmarshal(m, b)
}
func (m *Groups_JoinGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_JoinGroupResponse.Marshal(b, m, deterministic)
}
func (m *Groups_JoinGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_JoinGroupResponse.Merge(m, src)
}
func (m *Groups_JoinGroupResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_JoinGroupResponse.Size(m)
}
func (m *Groups_JoinGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_JoinGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_JoinGroupResponse proto.InternalMessageInfo

type Groups_TransferGroupOwnerRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	TargetUserId         string   `protobuf:"bytes,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_TransferGroupOwnerRequest) Reset()         { *m = Groups_TransferGroupOwnerRequest{} }
func (m *Groups_TransferGroupOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_TransferGroupOwnerRequest) ProtoMessage()    {}
func (*Groups_TransferGroupOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{4}
}

func (m *Groups_TransferGroupOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_TransferGroupOwnerRequest.Unmarshal(m, b)
}
func (m *Groups_TransferGroupOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_TransferGroupOwnerRequest.Marshal(b, m, deterministic)
}
func (m *Groups_TransferGroupOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_TransferGroupOwnerRequest.Merge(m, src)
}
func (m *Groups_TransferGroupOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_TransferGroupOwnerRequest.Size(m)
}
func (m *Groups_TransferGroupOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_TransferGroupOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_TransferGroupOwnerRequest proto.InternalMessageInfo

func (m *Groups_TransferGroupOwnerRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_TransferGroupOwnerRequest) GetTargetUserId() string {
	if m != nil {
		return m.TargetUserId
	}
	return ""
}

type Groups_TransferGroupOwnerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_TransferGroupOwnerResponse) Reset()         { *m = Groups_TransferGroupOwnerResponse{} }
func (m *Groups_TransferGroupOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_TransferGroupOwnerResponse) ProtoMessage()    {}
func (*Groups_TransferGroupOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{5}
}

func (m *Groups_TransferGroupOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_TransferGroupOwnerResponse.Unmarshal(m, b)
}
func (m *Groups_TransferGroupOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_TransferGroupOwnerResponse.Marshal(b, m, deterministic)
}
func (m *Groups_TransferGroupOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_TransferGroupOwnerResponse.Merge(m, src)
}
func (m *Groups_TransferGroupOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_TransferGroupOwnerResponse.Size(m)
}
func (m *Groups_TransferGroupOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_TransferGroupOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_TransferGroupOwnerResponse proto.InternalMessageInfo

type Groups_KickMemberRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	TargetUserId         string   `protobuf:"bytes,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_KickMemberRequest) Reset()         { *m = Groups_KickMemberRequest{} }
func (m *Groups_KickMemberRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_KickMemberRequest) ProtoMessage()    {}
func (*Groups_KickMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{6}
}

func (m *Groups_KickMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_KickMemberRequest.Unmarshal(m, b)
}
func (m *Groups_KickMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_KickMemberRequest.Marshal(b, m, deterministic)
}
func (m *Groups_KickMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_KickMemberRequest.Merge(m, src)
}
func (m *Groups_KickMemberRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_KickMemberRequest.Size(m)
}
func (m *Groups_KickMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_KickMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_KickMemberRequest proto.InternalMessageInfo

func (m *Groups_KickMemberRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_KickMemberRequest) GetTargetUserId() string {
	if m != nil {
		return m.TargetUserId
	}
	return ""
}

type Groups_KickMemberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_KickMemberResponse) Reset()         { *m = Groups_KickMemberResponse{} }
func (m *Groups_KickMemberResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_KickMemberResponse) ProtoMessage()    {}
func (*Groups_KickMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{7}
}

func (m *Groups_KickMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_KickMemberResponse.Unmarshal(m, b)
}
func (m *Groups_KickMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_KickMemberResponse.Marshal(b, m, deterministic)
}
func (m *Groups_KickMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_KickMemberResponse.Merge(m, src)
}
func (m *Groups_KickMemberResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_KickMemberResponse.Size(m)
}
func (m *Groups_KickMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_KickMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_KickMemberResponse proto.InternalMessageInfo

type Groups_LeaveGroupRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_LeaveGroupRequest) Reset()         { *m = Groups_LeaveGroupRequest{} }
func (m *Groups_LeaveGroupRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_LeaveGroupRequest) ProtoMessage()    {}
func (*Groups_LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{8}
}

func (m *Groups_LeaveGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_LeaveGroupRequest.Unmarshal(m, b)
}
func (m *Groups_LeaveGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_LeaveGroupRequest.Marshal(b, m, deterministic)
}
func (m *Groups_LeaveGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_LeaveGroupRequest.Merge(m, src)
}
func (m *Groups_LeaveGroupRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_LeaveGroupRequest.Size(m)
}
func (m *Groups_LeaveGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_LeaveGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_LeaveGroupRequest proto.InternalMessageInfo

func (m *Groups_LeaveGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type Groups_LeaveGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_LeaveGroupResponse) Reset()         { *m = Groups_LeaveGroupResponse{} }
func (m *Groups_LeaveGroupResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_LeaveGroupResponse) ProtoMessage()    {}
func (*Groups_LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{9}
}

func (m *Groups_LeaveGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_LeaveGroupResponse.Unmarshal(m, b)
}
func (m *Groups_LeaveGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_LeaveGroupResponse.Marshal(b, m, deterministic)
}
func (m *Groups_LeaveGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_LeaveGroupResponse.Merge(m, src)
}
func (m *Groups_LeaveGroupResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_LeaveGroupResponse.Size(m)
}
func (m *Groups_LeaveGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_LeaveGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_LeaveGroupResponse proto.InternalMessageInfo

type Groups_SetGroupMutedRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	SetMuted             bool     `protobuf:"varint,2,opt,name=setMuted,proto3" json:"setMuted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_SetGroupMutedRequest) Reset()         { *m = Groups_SetGroupMutedRequest{} }
func (m *Groups_SetGroupMutedRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_SetGroupMutedRequest) ProtoMessage()    {}
func (*Groups_SetGroupMutedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{10}
}

func (m *Groups_SetGroupMutedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_SetGroupMutedRequest.Unmarshal(m, b)
}
func (m *Groups_SetGroupMutedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_SetGroupMutedRequest.Marshal(b, m, deterministic)
}
func (m *Groups_SetGroupMutedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_SetGroupMutedRequest.Merge(m, src)
}
func (m *Groups_SetGroupMutedRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_SetGroupMutedRequest.Size(m)
}
func (m *Groups_SetGroupMutedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_SetGroupMutedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_SetGroupMutedRequest proto.InternalMessageInfo

func (m *Groups_SetGroupMutedRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_SetGroupMutedRequest) GetSetMuted() bool {
	if m != nil {
		return m.SetMuted
	}
	return false
}

type Groups_SetGroupMutedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_SetGroupMutedResponse) Reset()         { *m = Groups_SetGroupMutedResponse{} }
func (m *Groups_SetGroupMutedResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_SetGroupMutedResponse) ProtoMessage()    {}
func (*Groups_SetGroupMutedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{11}
}

func (m *Groups_SetGroupMutedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_SetGroupMutedResponse.Unmarshal(m, b)
}
func (m *Groups_SetGroupMutedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_SetGroupMutedResponse.Marshal(b, m, deterministic)
}
func (m *Groups_SetGroupMutedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_SetGroupMutedResponse.Merge(m, src)
}
func (m *Groups_SetGroupMutedResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_SetGroupMutedResponse.Size(m)
}
func (m *Groups_SetGroupMutedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_SetGroupMutedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_SetGroupMutedResponse proto.InternalMessageInfo

type Groups_UpdateGroupInfoRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=NewName,proto3" json:"NewName,omitempty"`
	AvatarKey            uint32   `protobuf:"varint,3,opt,name=AvatarKey,proto3" json:"AvatarKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_UpdateGroupInfoRequest) Reset()         { *m = Groups_UpdateGroupInfoRequest{} }
func (m *Groups_UpdateGroupInfoRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_UpdateGroupInfoRequest) ProtoMessage()    {}
func (*Groups_UpdateGroupInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{12}
}

func (m *Groups_UpdateGroupInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_UpdateGroupInfoRequest.Unmarshal(m, b)
}
func (m *Groups_UpdateGroupInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_UpdateGroupInfoRequest.Marshal(b, m, deterministic)
}
func (m *Groups_UpdateGroupInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_UpdateGroupInfoRequest.Merge(m, src)
}
func (m *Groups_UpdateGroupInfoRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_UpdateGroupInfoRequest.Size(m)
}
func (m *Groups_UpdateGroupInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_UpdateGroupInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_UpdateGroupInfoRequest proto.InternalMessageInfo

func (m *Groups_UpdateGroupInfoRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_UpdateGroupInfoRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *Groups_UpdateGroupInfoRequest) GetAvatarKey() uint32 {
	if m != nil {
		return m.AvatarKey
	}
	return 0
}

type Groups_UpdateGroupInfoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_UpdateGroupInfoResponse) Reset()         { *m = Groups_UpdateGroupInfoResponse{} }
func (m *Groups_UpdateGroupInfoResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_UpdateGroupInfoResponse) ProtoMessage()    {}
func (*Groups_UpdateGroupInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{13}
}

func (m *Groups_UpdateGroupInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_UpdateGroupInfoResponse.Unmarshal(m, b)
}
func (m *Groups_UpdateGroupInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_UpdateGroupInfoResponse.Marshal(b, m, deterministic)
}
func (m *Groups_UpdateGroupInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_UpdateGroupInfoResponse.Merge(m, src)
}
func (m *Groups_UpdateGroupInfoResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_UpdateGroupInfoResponse.Size(m)
}
func (m *Groups_UpdateGroupInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_UpdateGroupInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_UpdateGroupInfoResponse proto.InternalMessageInfo

type Groups_UpdateGroupPasswordRequest struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	NewJoinPassword      string   `protobuf:"bytes,2,opt,name=NewJoinPassword,proto3" json:"NewJoinPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_UpdateGroupPasswordRequest) Reset()         { *m = Groups_UpdateGroupPasswordRequest{} }
func (m *Groups_UpdateGroupPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*Groups_UpdateGroupPasswordRequest) ProtoMessage()    {}
func (*Groups_UpdateGroupPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{14}
}

func (m *Groups_UpdateGroupPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_UpdateGroupPasswordRequest.Unmarshal(m, b)
}
func (m *Groups_UpdateGroupPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_UpdateGroupPasswordRequest.Marshal(b, m, deterministic)
}
func (m *Groups_UpdateGroupPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_UpdateGroupPasswordRequest.Merge(m, src)
}
func (m *Groups_UpdateGroupPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_Groups_UpdateGroupPasswordRequest.Size(m)
}
func (m *Groups_UpdateGroupPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_UpdateGroupPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_UpdateGroupPasswordRequest proto.InternalMessageInfo

func (m *Groups_UpdateGroupPasswordRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Groups_UpdateGroupPasswordRequest) GetNewJoinPassword() string {
	if m != nil {
		return m.NewJoinPassword
	}
	return ""
}

type Groups_UpdateGroupPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Groups_UpdateGroupPasswordResponse) Reset()         { *m = Groups_UpdateGroupPasswordResponse{} }
func (m *Groups_UpdateGroupPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*Groups_UpdateGroupPasswordResponse) ProtoMessage()    {}
func (*Groups_UpdateGroupPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{15}
}

func (m *Groups_UpdateGroupPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups_UpdateGroupPasswordResponse.Unmarshal(m, b)
}
func (m *Groups_UpdateGroupPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups_UpdateGroupPasswordResponse.Marshal(b, m, deterministic)
}
func (m *Groups_UpdateGroupPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups_UpdateGroupPasswordResponse.Merge(m, src)
}
func (m *Groups_UpdateGroupPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_Groups_UpdateGroupPasswordResponse.Size(m)
}
func (m *Groups_UpdateGroupPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups_UpdateGroupPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Groups_UpdateGroupPasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Groups_CreateGroupConversationRequest)(nil), "kahla.Groups_CreateGroupConversationRequest")
	proto.RegisterType((*Groups_CreateGroupConversationResponse)(nil), "kahla.Groups_CreateGroupConversationResponse")
	proto.RegisterType((*Groups_JoinGroupRequest)(nil), "kahla.Groups_JoinGroupRequest")
	proto.RegisterType((*Groups_JoinGroupResponse)(nil), "kahla.Groups_JoinGroupResponse")
	proto.RegisterType((*Groups_TransferGroupOwnerRequest)(nil), "kahla.Groups_TransferGroupOwnerRequest")
	proto.RegisterType((*Groups_TransferGroupOwnerResponse)(nil), "kahla.Groups_TransferGroupOwnerResponse")
	proto.RegisterType((*Groups_KickMemberRequest)(nil), "kahla.Groups_KickMemberRequest")
	proto.RegisterType((*Groups_KickMemberResponse)(nil), "kahla.Groups_KickMemberResponse")
	proto.RegisterType((*Groups_LeaveGroupRequest)(nil), "kahla.Groups_LeaveGroupRequest")
	proto.RegisterType((*Groups_LeaveGroupResponse)(nil), "kahla.Groups_LeaveGroupResponse")
	proto.RegisterType((*Groups_SetGroupMutedRequest)(nil), "kahla.Groups_SetGroupMutedRequest")
	proto.RegisterType((*Groups_SetGroupMutedResponse)(nil), "kahla.Groups_SetGroupMutedResponse")
	proto.RegisterType((*Groups_UpdateGroupInfoRequest)(nil), "kahla.Groups_UpdateGroupInfoRequest")
	proto.RegisterType((*Groups_UpdateGroupInfoResponse)(nil), "kahla.Groups_UpdateGroupInfoResponse")
	proto.RegisterType((*Groups_UpdateGroupPasswordRequest)(nil), "kahla.Groups_UpdateGroupPasswordRequest")
	proto.RegisterType((*Groups_UpdateGroupPasswordResponse)(nil), "kahla.Groups_UpdateGroupPasswordResponse")
}

func init() { proto.RegisterFile("groups.proto", fileDescriptor_6616980d7c5e2870) }

var fileDescriptor_6616980d7c5e2870 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x55, 0xa8, 0x08, 0xcd, 0x28, 0x55, 0x25, 0x73, 0xe8, 0xe2, 0x96, 0xb0, 0xb8, 0x2d, 0x2c,
	0x12, 0xe4, 0x00, 0x17, 0x4e, 0x48, 0xa8, 0x07, 0x54, 0x4a, 0x03, 0x84, 0x56, 0x1c, 0x00, 0x21,
	0xb7, 0x3b, 0x0d, 0x21, 0xed, 0x3a, 0xd8, 0x4e, 0x02, 0xe2, 0x83, 0xf8, 0x15, 0x3e, 0x0b, 0xd5,
	0x71, 0x36, 0x5e, 0x67, 0x37, 0xf1, 0x81, 0x5b, 0x3c, 0xf3, 0xe6, 0xbd, 0xb7, 0xd6, 0x3c, 0x07,
	0x9a, 0x3d, 0x29, 0x46, 0x43, 0xd5, 0x1e, 0x4a, 0xa1, 0x05, 0xb9, 0x39, 0xe0, 0xdf, 0x2e, 0x39,
	0x6d, 0xe2, 0x4f, 0x8d, 0x59, 0x3a, 0x2d, 0xb2, 0x3e, 0xec, 0xbf, 0x32, 0xa0, 0xaf, 0x07, 0x12,
	0xb9, 0x46, 0x73, 0x38, 0x10, 0xd9, 0x18, 0xa5, 0xe2, 0xba, 0x2f, 0xb2, 0x2e, 0xfe, 0x18, 0xa1,
	0xd2, 0x64, 0x07, 0x1a, 0xa6, 0xd7, 0xe1, 0x57, 0x18, 0xd5, 0xe2, 0x5a, 0xd2, 0xe8, 0xce, 0x0b,
	0x84, 0x41, 0xf3, 0xb5, 0xe8, 0x67, 0xef, 0xb8, 0x52, 0x13, 0x21, 0xd3, 0xe8, 0x86, 0x01, 0x14,
	0x6a, 0x2c, 0x81, 0x07, 0xab, 0xa4, 0xd4, 0x50, 0x64, 0x0a, 0xd9, 0x27, 0xd8, 0xb2, 0xc8, 0x6b,
	0x02, 0xf3, 0xd3, 0xb1, 0xd1, 0xf3, 0x6d, 0xf4, 0x5c, 0x1b, 0xdf, 0x4b, 0x6c, 0xb8, 0x35, 0x46,
	0x21, 0x5a, 0x24, 0xb7, 0xc2, 0x29, 0xc4, 0xb6, 0x77, 0x22, 0x79, 0xa6, 0x2e, 0x50, 0x9a, 0xe3,
	0xdb, 0x49, 0x86, 0x32, 0xd8, 0x81, 0xe6, 0xb2, 0x87, 0xfa, 0x54, 0xa1, 0x3c, 0xcc, 0x1d, 0xb8,
	0x35, 0xb6, 0x0b, 0xf7, 0x97, 0xa8, 0x58, 0x2b, 0x9f, 0x73, 0x9b, 0x47, 0xfd, 0xf3, 0xc1, 0x31,
	0x5e, 0x9d, 0xfd, 0x4f, 0x0b, 0xdb, 0x70, 0xa7, 0x84, 0xdd, 0x4a, 0x3f, 0xcf, 0xa5, 0xdf, 0x20,
	0x1f, 0x63, 0xf8, 0xfd, 0x3b, 0xb4, 0xee, 0xa4, 0xa5, 0xfd, 0x08, 0xdb, 0xb6, 0xf9, 0x01, 0xb5,
	0xf9, 0x75, 0x3c, 0xd2, 0x98, 0x86, 0x7d, 0x14, 0x85, 0x75, 0x85, 0xda, 0x0c, 0x98, 0x0f, 0x5a,
	0xef, 0xe6, 0x67, 0xd6, 0x82, 0x9d, 0x72, 0x62, 0x2b, 0x3c, 0x82, 0xbb, 0xb6, 0x7f, 0x3a, 0x4c,
	0x67, 0x8b, 0x77, 0x98, 0x5d, 0x88, 0xb0, 0xdd, 0x8e, 0xe0, 0x56, 0x07, 0x27, 0xa6, 0x37, 0xbd,
	0xca, 0xd9, 0xf1, 0x7a, 0xee, 0xe5, 0x98, 0x6b, 0x2e, 0x8f, 0xf0, 0x57, 0xb4, 0x16, 0xd7, 0x92,
	0x8d, 0xee, 0xbc, 0xc0, 0x62, 0x68, 0x55, 0xc9, 0x5a, 0x63, 0x83, 0x7c, 0x11, 0x1c, 0xc4, 0x6c,
	0x51, 0xc3, 0xcc, 0x25, 0xb0, 0xd9, 0xc1, 0x49, 0x49, 0xf6, 0xfc, 0x32, 0xdb, 0x03, 0xb6, 0x4c,
	0x6c, 0x6a, 0xe9, 0xe9, 0x9f, 0x3a, 0xd4, 0xa7, 0x30, 0xf2, 0x1b, 0xb6, 0x2a, 0x82, 0x4a, 0x1e,
	0xb7, 0xcd, 0x5b, 0xd2, 0x0e, 0x7a, 0x3a, 0xe8, 0x93, 0x40, 0xb4, 0xbd, 0x95, 0xb5, 0xbf, 0x2f,
	0x6a, 0xe4, 0x3d, 0x34, 0xf2, 0x78, 0x92, 0x56, 0x91, 0xc0, 0x7f, 0x14, 0xe8, 0xbd, 0xca, 0xbe,
	0x4b, 0x79, 0x09, 0x64, 0x31, 0x6f, 0xe4, 0x61, 0x71, 0xb6, 0x32, 0xf7, 0x34, 0x59, 0x0d, 0x74,
	0xd5, 0x4e, 0x00, 0xe6, 0xd1, 0x22, 0x9e, 0xc3, 0x85, 0x48, 0xd3, 0xb8, 0x1a, 0xe0, 0xb1, 0xce,
	0x93, 0xe5, 0xb3, 0x2e, 0xa4, 0xd5, 0x67, 0x2d, 0x09, 0xa5, 0x61, 0xfd, 0x02, 0x1b, 0x85, 0xe4,
	0x10, 0x56, 0x9c, 0x2b, 0xcb, 0x2b, 0xdd, 0x5d, 0x8a, 0x71, 0xe9, 0xcf, 0x61, 0xd3, 0x4b, 0x00,
	0xd9, 0x2b, 0x0e, 0x97, 0xe7, 0x92, 0xee, 0xaf, 0x40, 0xb9, 0x22, 0x02, 0x6e, 0x97, 0xec, 0x35,
	0x49, 0x2a, 0x29, 0xbc, 0x9c, 0xd1, 0x47, 0x01, 0x48, 0x47, 0xf0, 0xac, 0x6e, 0xfe, 0x40, 0x9f,
	0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x82, 0x4a, 0xbb, 0x77, 0x65, 0x07, 0x00, 0x00,
}

// Generated by go-rest-client
type GroupsService struct {
	client  *http.Client
	baseUrl string
}

func NewGroupsService(client *http.Client, baseUrl string) *GroupsService {
	return &GroupsService{
		client:  client,
		baseUrl: baseUrl,
	}
}
func (s *GroupsService) CreateGroupConversation(in *Groups_CreateGroupConversationRequest) (*Groups_CreateGroupConversationResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("GroupName", in.GroupName)
	v.Add("JoinPassword", in.JoinPassword)
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/CreateGroupConversation", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_CreateGroupConversationResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) JoinGroup(in *Groups_JoinGroupRequest) (*Groups_JoinGroupResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("groupName", in.GroupName)
	v.Add("joinPassword", in.JoinPassword)
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/JoinGroup", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_JoinGroupResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) TransferGroupOwner(in *Groups_TransferGroupOwnerRequest) (*Groups_TransferGroupOwnerResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("groupName", in.GroupName)
	v.Add("targetUserId", in.TargetUserId)
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/TransferGroupOwner", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_TransferGroupOwnerResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) KickMember(in *Groups_KickMemberRequest) (*Groups_KickMemberResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("groupName", in.GroupName)
	v.Add("targetUserId", in.TargetUserId)
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/KickMember", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_KickMemberResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) LeaveGroup(in *Groups_LeaveGroupRequest) (*Groups_LeaveGroupResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("groupName", in.GroupName)
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/LeaveGroup", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_LeaveGroupResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) SetGroupMuted(in *Groups_SetGroupMutedRequest) (*Groups_SetGroupMutedResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("groupName", in.GroupName)
	v.Add("setMuted", strconv.FormatBool(in.SetMuted))
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/SetGroupMuted", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_SetGroupMutedResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) UpdateGroupInfo(in *Groups_UpdateGroupInfoRequest) (*Groups_UpdateGroupInfoResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("GroupName", in.GroupName)
	v.Add("NewName", in.NewName)
	v.Add("AvatarKey", strconv.FormatUint(uint64(in.AvatarKey), 10))
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/UpdateGroupInfo", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_UpdateGroupInfoResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
func (s *GroupsService) UpdateGroupPassword(in *Groups_UpdateGroupPasswordRequest) (*Groups_UpdateGroupPasswordResponse, *http.Response, error) {
	v := url.Values{}
	v.Add("GroupName", in.GroupName)
	v.Add("NewJoinPassword", in.NewJoinPassword)
	req, err := http.NewRequest("POST", s.baseUrl+"/Groups/UpdateGroupPassword", strings.NewReader(v.Encode()))
	if err != nil {
		return nil, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := s.client.Do(req)
	if err != nil {
		return nil, resp, err
	}
	defer resp.Body.Close()
	response := &Groups_UpdateGroupPasswordResponse{}
	err = json.NewDecoder(resp.Body).Decode(response)
	if err != nil {
		return response, resp, err
	}
	return response, resp, nil
}
